.TH imlib2-config 1 "13 Nov 2000" libast-config
.SH NAME
.HP
libast-config - libast build information script
.SH SYNOPSIS
.HP 
libast-config [options]
.P
.SH DESCRIPTION
.HP
.I libast-config 
is a script that's used by make and other build enviroments to
gather libast information.
.HP
Run
.I libast-config
for additional information.
