#!/usr/bin/env python
#
# Copyright (C) 2009 Samsung Electronics.
#
# This file is part of Editje.
#
# Editje is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Editje is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Editje.  If not, see
# <http://www.gnu.org/licenses/>.

import os
import sys

import elementary

from editje.editje import Editje
from editje.openfile import OpenFile
from editje.swapfile import SwapFile

if __name__ == "__main__":
    elementary.init()
    elementary.finger_size_set(15)
    elementary.policy_set(elementary.ELM_POLICY_QUIT,
                          elementary.ELM_POLICY_QUIT_LAST_WINDOW_CLOSED)

    files = sys.argv[1:]
    if files:
        count = 0
        for file in files:
            try:
                sf = SwapFile()
                sf.file = os.path.realpath(file)
                sf.open()
            except Exception as e:
                print "Error with file", file, ":", e
                continue

            editje = Editje(sf)
            editje.show()
            count += 1
        if not count:
            exit(1)
    else:
        OpenFile().show()

    elementary.run()
    elementary.shutdown()
