#!/usr/bin/env python
#
# Copyright (C) 2009 Samsung Electronics.
#
# This file is part of Editje.
#
# Editje is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Editje is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Editje.  If not, see
# <http://www.gnu.org/licenses/>.

import sys

import elementary

from editje.editje import Editje
from editje.openfile import OpenFile

if __name__ == "__main__":
    elementary.init()
    elementary.finger_size_set(15)
    elementary.policy_set(elementary.ELM_POLICY_QUIT,
                          elementary.ELM_POLICY_QUIT_LAST_WINDOW_CLOSED)

    if len(sys.argv) > 1:
        editje = Editje()
        editje.file = sys.argv[1]
        if len(sys.argv) > 2:
            editje.group = sys.argv[2]
        else:
            editje.select_group()
        editje.show()
    else:
        OpenFile().show()

    elementary.run()
    elementary.shutdown()
