#!/usr/bin/env bash
# Entrance PostSession script.
# Contains things which are to be ran after session is started.
# After this script, entrance ends and system is rebooted,
# shutted down, entrance is started again or something.
# You can write here for example deletion of some files,
# cleanup of some directory etc.. 
# make the use for this script yourself.
# Author: quaker66 <quaker66@gmail.com>
exit 0
