#!/bin/sh

enlightenment_remote -module-unload emu
#./autogen.sh --prefix=/opt/e17
make && sudo make install && sudo /sbin/ldconfig && enlightenment_remote -module-load emu  && enlightenment_remote -module-enable emu 
