#ifndef ENGRAVE_ENUMS_H
#define ENGRAVE_ENUMS_H

typedef enum _Engrave_Image_Type Engrave_Image_Type;
typedef enum _Engrave_Part_Type Engrave_Part_Type;
typedef enum _Engrave_Text_Effect Engrave_Text_Effect;
typedef enum _Engrave_Action Engrave_Action;
typedef enum _Engrave_Transition Engrave_Transition;
typedef enum _Engrave_Aspect_Preference Engrave_Aspect_Preference;
typedef enum _Engrave_Parse_Section Engrave_Parse_Section;

enum _Engrave_Image_Type
{
  ENGRAVE_IMAGE_TYPE_RAW,
  ENGRAVE_IMAGE_TYPE_COMP,
  ENGRAVE_IMAGE_TYPE_LOSSY,
  ENGRAVE_IMAGE_TYPE_EXTERNAL,
  ENGRAVE_IMAGE_TYPE_NUM

};

enum _Engrave_Part_Type
{
  ENGRAVE_PART_TYPE_IMAGE,
  ENGRAVE_PART_TYPE_TEXT,
  ENGRAVE_PART_TYPE_RECT,
  ENGRAVE_PART_TYPE_SWALLOW,
  ENGRAVE_PART_TYPE_NUM
};

enum _Engrave_Text_Effect
{
  ENGRAVE_TEXT_EFFECT_NONE,
  ENGRAVE_TEXT_EFFECT_PLAIN,
  ENGRAVE_TEXT_EFFECT_OUTLINE,
  ENGRAVE_TEXT_EFFECT_SOFT_OUTLINE,
  ENGRAVE_TEXT_EFFECT_SHADOW,
  ENGRAVE_TEXT_EFFECT_OUTLINE_SHADOW,
  ENGRAVE_TEXT_EFFECT_SOFT_SHADOW,
  ENGRAVE_TEXT_EFFECT_OUTLINE_SOFT_SHADOW,
  ENGRAVE_TEXT_EFFECT_NUM
};

enum _Engrave_Action
{
  ENGRAVE_ACTION_STATE_SET,
  ENGRAVE_ACTION_STOP,
  ENGRAVE_ACTION_SIGNAL_EMIT,
  ENGRAVE_ACTION_DRAG_VAL_SET,
  ENGRAVE_ACTION_DRAG_VAL_STEP,
  ENGRAVE_ACTION_DRAG_VAL_PAGE,
  ENGRAVE_ACTION_SCRIPT,
  ENGRAVE_ACTION_NUM
};

enum _Engrave_Transition
{
  ENGRAVE_TRANSITION_LINEAR,
  ENGRAVE_TRANSITION_SINUSOIDAL,
  ENGRAVE_TRANSITION_ACCELERATE,
  ENGRAVE_TRANSITION_DECELERATE,
  ENGRAVE_TRANSITION_NUM
};

enum _Engrave_Aspect_Preference
{
  ENGRAVE_ASPECT_PREFERENCE_NONE,
  ENGRAVE_ASPECT_PREFERENCE_VERTICAL,
  ENGRAVE_ASPECT_PREFERENCE_HORIZONTAL,
  ENGRAVE_ASPECT_PREFERENCE_BOTH,
  ENGRAVE_ASPECT_PREFERENCE_NUM
};

#endif

