debian/tmp/usr/include/ecore-*/Ecore*.h
debian/tmp/usr/lib/libecore*.a
debian/tmp/usr/lib/libecore*.la
debian/tmp/usr/lib/libecore.so
debian/tmp/usr/lib/libecore_con.so
debian/tmp/usr/lib/libecore_evas.so
# Conditionally installed from debian/rules (Linux-only):
# debian/tmp/usr/lib/libecore_fb.so
debian/tmp/usr/lib/libecore_file.so
debian/tmp/usr/lib/libecore_imf_evas.so
debian/tmp/usr/lib/libecore_imf.so
debian/tmp/usr/lib/libecore_input.so
debian/tmp/usr/lib/libecore_input_evas.so
debian/tmp/usr/lib/libecore_ipc.so
debian/tmp/usr/lib/libecore_x.so
debian/tmp/usr/lib/pkgconfig/ecore*.pc
