#!/bin/bash
#
# Begin e17mod-tclock.SlackBuild

NAME=e17mod-tclock
BUILD=1jp
CWD=$(pwd)

# Get functions
. ../functions
set_env

# Go to source code
cd ../../../E-MODULES-EXTRA/tclock
prepare_src

# Configure
CFLAGS=${SCFLAGS} CXXFLAGS=${SCFLAGS} \
  ./autogen.sh \
    --prefix=/usr \
    --libdir=${LIBDIR} \
    --build=${ARCH}-slackware-linux

# Install
make_install
install_doc AUTHORS COPYING* INSTALL

# Build the package
post_clean
pack_slack

# End e17mod-tclock.SlackBuild
