#!/bin/sh
rm -rf ./doc/html ./doc/latex ./doc/man
mkdir -p ./doc/html ./doc/latex ./doc/man 2>/dev/null
doxygen
#cp doc/img/*.png doc/html/
rm -f ekeko_docs.tar eina_docs.tar.gz
tar -cvf ekeko_docs.tar doc/html doc/man doc/latex
gzip -9f ekeko_docs.tar
exit 0
