.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ELSA 1 "Jun 19, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
\fBelsa \fP- EFL login manager
.SH SYNOPSIS
.B elsa
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B elsa
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBelsa\fP is a login manager based on the Enlightenment Foundation Libraries.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show version of program.
.TP
.B \-n, \-\-nodaemon
Don't daemonize.
.TP
.B \-R, \-\-copyright
Show the copyright information.
.TP
.B \-L, \-\-license
Show the license information.
.SH SEE ALSO
Nothing yet?
.SH AUTHOR
elsa was written by Michael Bouchaud <michael.bouchaud@gmail.com>.
.PP
This manual page was written by Daniel Dehennin <daniel.dehennin@baby-gnu.org>,
for the Debian project (and may be used by others).
