<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplicationThemeGroup extends BaseApplicationThemeGroup
{
	public function save(Doctrine_Connection $conn = null) {
    	if (!$this->exists()) {
			$this->setCreatedAt(date('Y-m-d H:i:s'));
    	}
		$this->setUpdatedAt(date('Y-m-d H:i:s'));
		parent::save($conn);
	}
	
	public static function update($values, $user) {
		$applicationThemeGroup = new ApplicationThemeGroup();
		$applicationThemeGroup->setApplicationId($values['application_id']);
		$applicationThemeGroup->setThemeGroupId($values['theme_group_id']);
		$applicationThemeGroup->save();
		return $applicationThemeGroup;
	}
}
