<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Madule extends BaseMadule
{
	public static function getByName($name) {
		$q = new Doctrine_Query();
		return $q->select('m.*')
					->from('Madule m')
					->where('name = ?', array($name))
					->fetchOne();
	}
	
	public static function getAsOptions()
	{
		$q = new Doctrine_Query();
		$q = $q->select('m.*')
				->from('Madule m');
		$q = $q->addWhere('approved = ?', array(true));
		$modules = $q->execute();
		$options = array();
		foreach ($modules as $module)
			$options[$module->getId()] = $module->getName();
		return $options;
	}
	
	public function getFolderPath()
	{
		if (sfConfig::get('sf_environment') == 'prod')
			return sfConfig::get('sf_root_dir').DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'html'.DIRECTORY_SEPARATOR.'files'.DIRECTORY_SEPARATOR.'module'.DIRECTORY_SEPARATOR.$this->getId().DIRECTORY_SEPARATOR;
		else
			return sfConfig::get('sf_root_dir').DIRECTORY_SEPARATOR.'web'.DIRECTORY_SEPARATOR.'files'.DIRECTORY_SEPARATOR.'module'.DIRECTORY_SEPARATOR.$this->getId().DIRECTORY_SEPARATOR;
	}
	
	public function getUrlPath()
	{
		return '/files/module/'.$this->getId().'/';
	}
	
	public function getShowPath()
	{
		return '/module/show/'.$this->getId();
	}
	
	public function getSourceDisplayUrl()
	{
		$url = $this->getSourceUrl();
		if (stripos($url, 'E16')===0 
			|| stripos($url, 'e')===0
			|| stripos($url, 'E-MODULES-EXTRA')===0
			|| stripos($url, 'eterm')===0
			|| stripos($url, 'MISC')===0)
			return '/home/cvs/path/'.urlencode(str_replace('/', '|', $url));
		return $url;
	}
	
	public function getXML($rss = false)
	{
		if ($rss) {
			$output = 	'<item>' .
							'<title>'.htmlspecialchars($this->getName()).'</title>' .
							'<link>'.htmlspecialchars(Tools::get('url').'/module/show/'.$this->getId()).'</link>' .
							'<description>'.
								htmlspecialchars('	<a href="'.Tools::get('url').'/module/show/'.$this->getId().'">' .
														'<img src="'.Tools::get('url').$this->getUrlPath().'smallthumb.png" alt="Thumbnail">' .
													'</a><br/>'.
												$this->getDescription()).'</description>' .
							'<pubDate>'.date('r', strtotime($this->getUpdatedAt())).'</pubDate>' .
							'<guid>'.htmlspecialchars(Tools::get('url').'/module/show/'.$this->getId()).'</guid>' .
						'</item>';
		} else {
			$output = '<module>';
			$output .= '<id>'.$this->getId().'</id>';
			$output .= '<name>'.htmlspecialchars($this->getName()).'</name>';
			$output .= '<description>'.htmlspecialchars($this->getDescription()).'</description>';
			$output .= '<url>'.htmlspecialchars($this->getSourceUrl()).'</url>';
			$output .= '<thumbnail>'.htmlspecialchars(Tools::get('url').$this->getUrlPath().'smallthumb.png').'</thumbnail>';
			$output .= '<screenshot>'.htmlspecialchars(Tools::get('url').$this->getUrlPath().'screenshot.png').'</screenshot>';
			$output .= '<rating>'.$this->getRating().'</rating>';
			$output .= '<application_id>'.$this->getApplicationId().'</application_id>';
			$output .= '<user_id>'.$this->getUserId().'</user_id>';
			$output .= '<created_at>'.$this->getCreatedAt().'</created_at>';
			$output .= '<updated_at>'.$this->getUpdatedAt().'</updated_at>';
			$output .= '</module>';
		}
		return $output;
	}
	
	public function clearThemeGroups()
	{
		$maduleThemeGroups = $this->getMaduleThemeGroups();
		foreach ($maduleThemeGroups as $maduleThemeGroup)
			$maduleThemeGroup->delete();
	}
	
	public function addThemeGroup($name)
	{
	  	$name = trim($name);
	  	$q = new Doctrine_Query();
	    $maduleThemeGroup = $q->select('mt.*')
	    				->from('MaduleThemeGroup mt, mt.ThemeGroup t')
	    				->addWhere('mt.madule_id = ? and t.name = ?', array($this->getId(), $name))
	    				->fetchOne();
	    if (!$maduleThemeGroup) {
	  		$q = new Doctrine_Query();
		    $themeGroup = $q->select('t.*')
		    				->from('ThemeGroup t')
		    				->addWhere('t.name = ?', array($name))
		    				->fetchOne();
		    if (!$themeGroup) {
		    	$themeGroup = new ThemeGroup();
		    	$themeGroup->setName($name);
		    	$themeGroup->save();
		    }
		    $maduleThemeGroup = new MaduleThemeGroup();
		    $maduleThemeGroup->setThemeGroupId($themeGroup->getId());
		    $maduleThemeGroup->setMaduleId($this->getId());
		    $maduleThemeGroup->save();
	    }
	    return $maduleThemeGroup;
	}
	
	public function save(Doctrine_Connection $conn = null) {
    	if (!$this->exists()) {
			$this->setCreatedAt(date('Y-m-d H:i:s'));
    	}
    	$modified = $this->getModified();
    	if (!isset($modified['downloads'])&&!isset($modified['rating']))
			$this->setUpdatedAt(date('Y-m-d H:i:s'));
		parent::save($conn);
	}
	
	public function updateRating() {
		$ratings = $this->getRatings();
		$total = 0;
		if (!$ratings->count())
			return 0;
		foreach ($ratings as $rating)
			$total += $rating->getValue();
		$this->setRating($total / $ratings->count());
		$this->save(); 
	}
	
	public static function update($values, $user)
	{
		$id = $values['id'];
		if ($id) {
			$q = new Doctrine_Query();
			$q = $q->select('m.*')
					->from('Madule m');
			$q = $q->addWhere('id = ?', array($id));
			if (!$user->getRole()==User::ADMIN)
				$q = $q->addWhere('user_id = ?', array($user->getId()));
			$module = $q->fetchOne();
		} else
			$module = new Madule();
		if ($module) {
			$module->setName($values['name']);
			$module->setDescription($values['description']);
			$module->setSourceUrl($values['source_url']);
			if (!$module->getUserId())
				$module->setUserId($user->getId());
			$module->setApplicationId($values['application_id']);
			$module->setApproved(false);
			$module->save();
			$folderpath = $module->getFolderPath();
			if (!is_dir($folderpath))
				mkdir($folderpath);
			$screenshot = $values['screenshot'];
			if ($screenshot) {
				$screenshotpath = $folderpath.$module->getId().$screenshot->getOriginalName();
				$screenshot->save($screenshotpath);
				$smallThumb = new Thumbnail($screenshotpath);
				if ($smallThumb->getCurrentWidth() > 150 || $smallThumb->getCurrentHeight() > 150)
					$smallThumb->resize(150, 150);
				$smallThumb->show(100, $folderpath.'smallthumb.png');
				$bigThumb = new Thumbnail($screenshotpath);
				if ($bigThumb->getCurrentWidth() > 500 || $bigThumb->getCurrentHeight() > 500)
					$bigThumb->resize(500, 500);
				$bigThumb->show(100, $folderpath.'bigthumb.png');
				$screenshot = new Thumbnail($screenshotpath);
				$screenshot->show(100, $folderpath.'screenshot.png');
				unlink($screenshotpath);
			}
			return $module;
		}
		return null;
	}
}
