<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Rating extends BaseRating
{
	const APPLICATION = 1;
	const MODULE = 2;
	const THEME = 3;

	public function getObject() {
		if ($this->getApplicationId())
			return $this->getApplication();
		if ($this->getMaduleId())
			return $this->getMadule();
		if ($this->getThemeId())
			return $this->getTheme();
		return null;
	}
	
	public function save(Doctrine_Connection $conn = null) {
		parent::save($conn);
		
    	$object = $this->getObject();
    	if ($object)
    		$object->updateRating();
	}

}