<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ThemeThemeGroup extends BaseThemeThemeGroup
{
	public function save(Doctrine_Connection $conn = null) {
    	if (!$this->exists()) {
			$this->setCreatedAt(date('Y-m-d H:i:s'));
    	}
		$this->setUpdatedAt(date('Y-m-d H:i:s'));
		parent::save($conn);
	}
}
