/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "callbacks.h"

GtkWidget *main_window;
char *db_file = NULL;

int
main (int argc, char *argv[])
{
  GtkWidget *window;
  GtkWidget *keyname;
  GtkWidget *fileselection;

  if (argc > 1) db_file = g_strdup(argv[1]);

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  main_window = create_window ();
  new_db(main_window, db_file);
  init_type_menu();
  gtk_widget_show (main_window);

  gtk_main ();
  return 0;
}

