#!/usr/bin/perl

# A simple contact manager / calander for the ipaq
# Copyright 2001 Geoff 'Mandrake' Harrison <mandrake@mandrake.net>
# All Rights Reserved
# http://mandrake.net

use Gtk;
use Gtk::Atoms;
use Gtk::Keysyms;

init Gtk;

$last_row = -1;
$prefs{hide_complete_todo} = 1;
$prefs{show_details} = 0;
$editing_contact = 0;

sub exit_application {

	open CONTACTS, ">$ENV{HOME}/.contacts/contacts";
	foreach(@contacts) {
		my %ctct = %$_;
		if($ctct{name} ne "") {
			print CONTACTS "$ctct{name}::$ctct{mobile}::$ctct{home}::$ctct{work}::$ctct{pager}::$ctct{address1}::$ctct{address2}::$ctct{city}::$ctct{state}::$ctct{zipcode}::$ctct{birthday}::$ctct{anniversary}::$ctct{email}\n";
		}
	}
	close CONTACTS;
	open TODOLIST, ">$ENV{HOME}/.contacts/todo";
	foreach(@todolist) {
		my %item = %$_;
		chomp $item{startdate};
		chomp $item{enddate};
		print TODOLIST
			"$item{text}::$item{startdate}::$item{enddate}::$item{priority}\n";
	}
	close TODOLIST;
	open NOTESFILE, ">$ENV{HOME}/.contacts/notes";
	print NOTESFILE $notes_text->get_chars(0,$notes_text->get_length);
	close NOTESFILE;
	Gtk->exit(0);
}

sub selected_contact {

	my($widget,$row,$col,$event) = @_;  

	if($last_row == $row) {
		my $ptr = $contacts[$row];
		$editing_contact = $ptr;
		foreach(keys(%contact)) {
			$contact{$_}->set_text($$ptr{$_});
		}
		$notebook->set_page(4);
		return;
	}
	$last_row = $row;

}

sub add_new_contact {
	my %ctct;
	$editing_contact = \%ctct;
	foreach(keys(%contact)) {
		$contact{$_}->set_text("");
	}
	$notebook->set_page(4);
	push @contacts, \%ctct;
	$contact_clist->append("","");

}

sub delete_contact {
	if($last_row >= 0) {
		splice(@contacts,$last_row,1);
		$contact_clist->remove($last_row);
		$last_row = -1;
	}

}

sub toggle_show_completed {
	if($prefs{hide_complete_todo}) {
		$prefs{hide_complete_todo} = 0;
		foreach(@todolist) {
			my %item = %$_;
			$item{checkbox}->show();
		}
	} else {
		$prefs{hide_complete_todo} = 1;
		foreach(@todolist) {
			my %item = %$_;
			if($item{enddate} ne "") {
				$item{checkbox}->hide();
			} else {
				$item{checkbox}->show();
			}
		}
	}

}

sub refresh_contacts {
	my $i;
	foreach $ptr (@contacts) {
		my $num;
		$contact_clist->set_text($i,0,"$$ptr{name}");
		if($$ptr{mobile}) {
			$num = $$ptr{mobile};
		} elsif($$ptr{home}) {
			$num = $$ptr{home};
		} elsif($$ptr{work}) {
			$num = $$ptr{work};
		} elsif($$ptr{pager}) {
			$num = $$ptr{pager};
		} else {
			$num = "none";
		}
		$contact_clist->set_text($i,1,"$num");
		$i++;
	}
	$contact_clist->columns_autosize();

}

sub add_new_todo {

	$todo{text}->set_text("");
	$todo{startdate}->set_text(`date`);
	$todo{priority}->set_text("3");
	$notebook->set_page(5);
	$todo{text}->grab_focus();

}

sub modified_element {
	my ($widget,$which) = @_;

	$$editing_contact{$which} = $widget->get_text();
}

sub toggle_todo_item {
	my($widget, $item) = @_;

	if($$item{enddate} ne "") {
		$$item{enddate} = "";
		if($prefs{hide_complete_todo}) {
			$$item{checkbox}->show();
		}
	} else {
		$$item{enddate} = `date`;
		chomp($$item{enddate});
		if($prefs{hide_complete_todo}) {
			$$item{checkbox}->hide();
		}
	}

}

sub toggle_show_details {
	if(!$prefs{show_details}) {
		$prefs{show_details} = 1;
		foreach(@todolist) {
			my $item = $_;
			$$item{checkbox}->destroy;
			$$item{checkbox} = new Gtk::CheckButton;
		   	my $label = new Gtk::Label "$$item{text}\nstarted: $$item{startdate}\nended:$$item{enddate}\nPriority: $$item{priority}";
			$label->show();
			$$item{checkbox}->add($label);
			$label->set_alignment(0,0);
			$todo{vbox}->pack_start($$item{checkbox},0,0,3);
			if($prefs{hide_complete_todo}) {
				if($$item{enddate} ne "") {
					$$item{checkbox}->hide();
				} else {
					$$item{checkbox}->show();
				}
			} else {
				$$item{checkbox}->show();
			}
			if($$item{enddate} ne "") {
				$$item{checkbox}->set_active(1);
			}
			$$item{checkbox}->signal_connect('toggled',\&toggle_todo_item,$item);
		}
	} else {
		$prefs{show_details} = 0;
		foreach(@todolist) {
			my $item = $_;
			$$item{checkbox}->destroy;
			$$item{checkbox} = new Gtk::CheckButton "$$item{text}";
			$todo{vbox}->pack_start($$item{checkbox},0,0,3);
			if($prefs{hide_complete_todo}) {
				if($$item{enddate} ne "") {
					$$item{checkbox}->hide();
				} else {
					$$item{checkbox}->show();
				}
			} else {
				$$item{checkbox}->show();
			}
			if($$item{enddate} ne "") {
				$$item{checkbox}->set_active(1);
			}
			$$item{checkbox}->signal_connect('toggled',\&toggle_todo_item,$item);
		}
	}

}

sub add_new_todo_item {

	my %item;
	$item{text} = $todo{text}->get_text();
	$item{startdate} = $todo{startdate}->get_text();
	$item{enddate} = $todo{enddate}->get_text();
	$item{priority} = $todo{priority}->get_text();
	$item{checkbox} = new Gtk::CheckButton "$item{text}";
	$todo{vbox}->pack_start($item{checkbox},0,0,3);
	if(($item{enddate} ne "") && $prefs{hide_complete_todo}) {
		$item{checkbox}->set_active(1);
	} else {
		$item{checkbox}->show();
	}
	$item{checkbox}->signal_connect('toggled',\&toggle_todo_item, \%item);
	push @todolist,\%item;

	$notebook->set_page(2);

}

sub create_contacts_page {

	my $page = new Gtk::VBox(0,0);
	
	my $scrolled_window = new Gtk::ScrolledWindow(undef,undef);
	$scrolled_window->set_policy('never','always');
	$page->pack_start($scrolled_window,1,1,0);
	$scrolled_window->show();

	my $clist = new_with_titles Gtk::CList("Name","Number");
	$scrolled_window->add($clist);
	$clist->show();
	$clist->set_selection_mode('extended');
	$clist->signal_connect('select-row',\&selected_contact);
	$contact_clist = $clist;

	open CONTACTS, "$ENV{HOME}/.contacts/contacts";
	while(<CONTACTS>) {
		my %ctct;
		my $num;
		chomp;
		($ctct{name},$ctct{mobile},$ctct{home},$ctct{work},$ctct{pager},$ctct{address1},$ctct{address2},$ctct{city},$ctct{state},$ctct{zipcode},$ctct{birthday},$ctct{anniversary},$ctct{email}) = split /\:\:/;
		if($ctct{mobile}) {
			$num = $ctct{mobile};
		} elsif($ctct{home}) {
			$num = $ctct{home};
		} elsif($ctct{work}) {
			$num = $ctct{work};
		} elsif($ctct{pager}) {
			$num = $ctct{pager};
		} else {
			$num = "none";
		}
		$clist->append("$ctct{name}","$num");
		push @contacts,\%ctct;

	}
	$clist->columns_autosize();

	my $hbox = new Gtk::HBox(0,0);
	$page->pack_start($hbox,0,1,0);
	$hbox->show();

	my $button = new Gtk::Button "Add";
	$hbox->pack_start($button,1,1,0);
	$button->show();
	$button->signal_connect('clicked',\&add_new_contact);

	$button = new Gtk::Button "Delete";
	$hbox->pack_start($button,1,1,0);
	$button->show();
	$button->signal_connect('clicked',\&delete_contact);

	$page->show();
	return $page;
}

sub create_calendar_page {

	my $page = new Gtk::VBox(0,0);
	$page->set_border_width(5);
	
	$str = `cal`;
	my ($monthyear,$daysofweek,@lines) = split /\n/, $str;
	my ($blank,$month, $year) = split /\s+/,$monthyear;

	my $label = new Gtk::Label "$month, $year";
	$page->pack_start($label,0,1,0);
	$label->show();

	my $alignment = new Gtk::Alignment(0.5,0.5);
	my $table = new Gtk::Table(7,4,1);
	$page->pack_start($alignment,1,1,0);
	$alignment->add($table);
	$alignment->show();
	$table->show();

	my $element = 0;
	foreach("Su","Mo","Tu","We","Th","Fr","Sa") {
		$label = new Gtk::Label "$_";
		$table->attach($label,$element,$element+1,0,1,[-fill],[-fill],2,2);
		$label->show();
		$element++;
	}

	$row = 1;
	foreach $line (@lines) {
		$element = 0;
		@elements = unpack "a3a3a3a3a3a3a3", $line;
		foreach(@elements) {
			if($_ > 0) {
				$_ =~ s/\s+//g;
				my $button = new Gtk::Button " $_ ";
				$table->attach($button,$element,$element+1,$row,$row+1,[-expand,-fill],[-expand,-fill],2,2);
				$button->show();
			} else {
				my $label = new Gtk::Label "$_";
				$table->attach($label,$element,$element+1,$row,$row+1,[-expand,-fill],[-expand,-fill],2,2);
				$label->show();
			}
			$element++;
		}
		$row++;
	}

	$page->show();
	return $page;
}

sub create_todo_page {

	my $page = new Gtk::VBox(0,0);
	
	my $scrolled_window = new Gtk::ScrolledWindow(undef,undef);
	$scrolled_window->set_policy('never','always');
	$page->pack_start($scrolled_window,1,1,0);
	$scrolled_window->show();

	my $vbox = new Gtk::VBox(0,0);
	$scrolled_window->add_with_viewport($vbox);
	$vbox->show();

	open TODOLIST,"$ENV{HOME}/.contacts/todo";
	while(<TODOLIST>) {
		my %todoitem;
		chomp;
		($todoitem{text},$todoitem{startdate},$todoitem{enddate},$todoitem{priority})
			= split /\:\:/;
		if($prefs{show_details}) {
			$todoitem{checkbox} = new Gtk::CheckButton;
		   	my $label = new Gtk::Label "$todoitem{text}\nstarted: $todoitem{startdate}\nended:$todoitem{enddate}\nPriority: $todoitem{priority}";
			$label->show();
			$todoitem{checkbox}->add($label);
			$label->set_alignment(0,0);
		} else {
			$todoitem{checkbox} = new Gtk::CheckButton $todoitem{text};
		}
		$vbox->pack_start($todoitem{checkbox},0,0,3);
		$todoitem{checkbox}->can_focus(0);
		if(($todoitem{enddate} ne "") && $prefs{hide_complete_todo}) {
			$todoitem{checkbox}->set_active(1);
		} else {
			$todoitem{checkbox}->show();
		}
		$todoitem{checkbox}->signal_connect('toggled',\&toggle_todo_item,\%todoitem);

		push @todolist, \%todoitem;

	}
	close TODOLIST;

	$todo{vbox} = $vbox;

	my $hbox = new Gtk::HBox(0,0);
	$page->pack_start($hbox,0,1,0);
	$hbox->show();

	my $button = new Gtk::Button "Add";
	$hbox->pack_start($button,1,1,0);
	$button->show();
	$button->signal_connect('clicked', \&add_new_todo);

	$button = new Gtk::ToggleButton "Details";
	$hbox->pack_start($button,1,1,0);
	$button->show();
	$button->signal_connect('clicked', \&toggle_show_details);

	$button = new Gtk::ToggleButton "View Completed";
	$hbox->pack_start($button,1,1,0);
	$button->show();
	$button->signal_connect('clicked', \&toggle_show_completed);

	$page->show();
	return $page;
}

sub create_notes_page {

	my $page = new Gtk::VBox(0,0);
	
	my $scrolled_window = new Gtk::ScrolledWindow(undef,undef);
	$scrolled_window->set_policy('never','always');
	$page->pack_start($scrolled_window,1,1,0);
	$scrolled_window->show();

	$notes_text = new Gtk::Text;
	$notes_text->set_word_wrap(0);
	$notes_text->show();
	$notes_text->set_editable(1);
	$scrolled_window->add($notes_text);

	if(-e "$ENV{HOME}/.contacts/notes") {
		open NOTESFILE, "<$ENV{HOME}/.contacts/notes";
		while(<NOTESFILE>) {
			$notes_text->insert(undef,$notes_text->style->black,undef,$_);
		}
		close NOTESFILE;
	}
	$page->show();
	return $page;
}

sub create_contact_detail_page {

	my $page = new Gtk::VBox(0,0);
	
	my $scrolled_window = new Gtk::ScrolledWindow(undef,undef);
	$scrolled_window->set_policy('never','always');
	$page->pack_start($scrolled_window,1,1,0);
	$scrolled_window->show();

	my $table = new Gtk::Table(0,0,0);
	$scrolled_window->add_with_viewport($table);
	$table->show();

	my $label = new Gtk::Label "Name:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,0,1,[-fill],0,0,0);
	$label->show();

	$contact{name} = new Gtk::Entry;
	$table->attach($contact{name},1,2,0,1,[-expand,-fill],[-fill],0,0);
	$contact{name}->show();
	$contact{name}->signal_connect('changed',\&modified_element,"name");

	$label = new Gtk::Label "Mobile Phone:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,1,2,[-fill],0,0,0);
	$label->show();

	$contact{mobile} = new Gtk::Entry;
	$table->attach($contact{mobile},1,2,1,2,[-expand,-fill],[-fill],0,0);
	$contact{mobile}->show();
	$contact{mobile}->signal_connect('changed',\&modified_element,"mobile");

	$label = new Gtk::Label "Home Phone:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,2,3,[-fill],0,0,0);
	$label->show();

	$contact{home} = new Gtk::Entry;
	$table->attach($contact{home},1,2,2,3,[-expand,-fill],[-fill],0,0);
	$contact{home}->show();
	$contact{home}->signal_connect('changed',\&modified_element,"home");

	$label = new Gtk::Label "Work Phone:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,3,4,[-fill],0,0,0);
	$label->show();

	$contact{work} = new Gtk::Entry;
	$table->attach($contact{work},1,2,3,4,[-expand,-fill],[-fill],0,0);
	$contact{work}->show();
	$contact{work}->signal_connect('changed',\&modified_element,"work");

	$label = new Gtk::Label "Pager:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,4,5,[-fill],0,0,0);
	$label->show();

	$contact{pager} = new Gtk::Entry;
	$table->attach($contact{pager},1,2,4,5,[-expand,-fill],[-fill],0,0);
	$contact{pager}->show();
	$contact{pager}->signal_connect('changed',\&modified_element,"pager");

	$label = new Gtk::Label " Address Line 1:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,5,6,[-fill],0,0,0);
	$label->show();

	$contact{address1} = new Gtk::Entry;
	$table->attach($contact{address1},1,2,5,6,[-expand,-fill],[-fill],0,0);
	$contact{address1}->show();
	$contact{address1}->signal_connect('changed',\&modified_element,"address1");

	$label = new Gtk::Label " Address Line 2:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,6,7,[-fill],0,0,0);
	$label->show();

	$contact{address2} = new Gtk::Entry;
	$table->attach($contact{address2},1,2,6,7,[-fill],[-fill,-expand],0,0);
	$contact{address2}->show();
	$contact{address2}->signal_connect('changed',\&modified_element,"address2");

	$label = new Gtk::Label "City:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,7,8,[-fill],0,0,0);
	$label->show();

	$contact{city} = new Gtk::Entry;
	$table->attach($contact{city},1,2,7,8,[-fill],[-fill,-expand],0,0);
	$contact{city}->show();
	$contact{city}->signal_connect('changed',\&modified_element,"city");

	$label = new Gtk::Label "State:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,8,9,[-fill],0,0,0);
	$label->show();

	$contact{state} = new Gtk::Entry;
	$table->attach($contact{state},1,2,8,9,[-fill],[-fill,-expand],0,0);
	$contact{state}->show();
	$contact{state}->signal_connect('changed',\&modified_element,"state");

	$label = new Gtk::Label "Zip Code:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,9,10,[-fill],0,0,0);
	$label->show();

	$contact{zipcode} = new Gtk::Entry;
	$table->attach($contact{zipcode},1,2,9,10,[-fill],[-fill,-expand],0,0);
	$contact{zipcode}->show();
	$contact{zipcode}->signal_connect('changed',\&modified_element,"zipcode");

	$label = new Gtk::Label "Birthday:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,10,11,[-fill],0,0,0);
	$label->show();

	$contact{birthday} = new Gtk::Entry;
	$table->attach($contact{birthday},1,2,10,11,[-fill],[-fill,-expand],0,0);
	$contact{birthday}->show();
	$contact{birthday}->signal_connect('changed',\&modified_element,"birthday");

	$label = new Gtk::Label " Anniversary:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,11,12,[-fill],0,0,0);
	$label->show();

	$contact{anniversary} = new Gtk::Entry;
	$table->attach($contact{anniversary},1,2,11,12,[-fill],[-fill,-expand],0,0);
	$contact{anniversary}->show();
	$contact{anniversary}->signal_connect('changed',\&modified_element,"anniversary");

	$label = new Gtk::Label "Email Address:";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,12,13,[-fill],0,0,0);
	$label->show();

	$contact{email} = new Gtk::Entry;
	$table->attach($contact{email},1,2,12,13,[-fill],[-fill,-expand],0,0);
	$contact{email}->show();
	$contact{email}->signal_connect('changed',\&modified_element,"email");

	my $button = new Gtk::Button "Return to Contact List";
	$page->pack_start($button,0,1,0);
	$button->show();
	$button->signal_connect('clicked', sub { &refresh_contacts; $notebook->set_page(0); });

	$page->show();
	return $page;
}

sub create_new_todo_page {
	my $page = new Gtk::VBox(0,0);
	
	my $table = new Gtk::Table(2,2,0);
	$page->pack_start($table,1,1,0);
	$table->show();

	my $label = new Gtk::Label "Todo: ";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,0,1,[-fill],0,0,0);
	$label->show();

	$todo{text} = new Gtk::Entry;
	$table->attach($todo{text},1,2,0,1,[-expand,-fill],[-fill],0,0);
	$todo{text}->show();

	$label = new Gtk::Label " Added: ";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,1,2,[-fill],0,0,0);
	$label->show();

	$todo{startdate} = new Gtk::Entry;
	$table->attach($todo{startdate},1,2,1,2,[-expand,-fill],[-fill],0,0);
	$todo{startdate}->show();

	$label = new Gtk::Label " Completed: ";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,2,3,[-fill],0,0,0);
	$label->show();

	$todo{enddate} = new Gtk::Entry;
	$table->attach($todo{enddate},1,2,2,3,[-expand,-fill],[-fill],0,0);
	$todo{enddate}->show();

	$label = new Gtk::Label " Priority: ";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,3,4,[-fill],0,0,0);
	$label->show();

	$todo{priority} = new Gtk::Entry;
	$table->attach($todo{priority},1,2,3,4,[-expand,-fill],[-fill],0,0);
	$todo{priority}->show();

	my $hbox = new Gtk::HBox(0,0);
	$page->pack_start($hbox,0,1,0);
	$hbox->show();

	my $button = new Gtk::Button "Add This Item";
	$hbox->pack_start($button,1,1,0);
	$button->show();
	$button->signal_connect('clicked', \&add_new_todo_item);

	$button = new Gtk::Button "Cancel";
	$hbox->pack_start($button,1,1,0);
	$button->signal_connect('clicked', sub { $notebook->set_page(2);});
	$button->show();

	$page->show();
	return $page;
}

sub create_main_window {
	my $main_vbox = new Gtk::VBox(0,0);
	$main_vbox->show();

	my $omenu = new Gtk::OptionMenu;
	my $menu  = new Gtk::Menu;

	$omenu->set_menu($menu);
	$omenu->show();
	$menu->show();

	my $menuitem = new Gtk::MenuItem("Contacts");
	$menuitem->signal_connect('activate', sub { &refresh_contacts; $notebook->set_page(0); });
	$menuitem->show();
	$menu->append($menuitem);
	$omenu->set_history(0);

	$menuitem = new Gtk::MenuItem("Calendar");
	$menuitem->signal_connect('activate', sub { $notebook->set_page(1); });
	$menuitem->show();
	$menu->append($menuitem);

	$menuitem = new Gtk::MenuItem("Todo List");
	$menuitem->signal_connect('activate', sub { $notebook->set_page(2); });
	$menuitem->show();
	$menu->append($menuitem);

	$menuitem = new Gtk::MenuItem("Notes");
	$menuitem->signal_connect('activate', sub { $notebook->set_page(3);
			$notes_text->grab_focus();});
	$menuitem->show();
	$menu->append($menuitem);

	$main_vbox->pack_start($omenu,0,1,0);

	$notebook = new Gtk::Notebook;
	$notebook->append_page(create_contacts_page());
	$notebook->append_page(create_calendar_page());
	$notebook->append_page(create_todo_page());
	$notebook->append_page(create_notes_page());
	$notebook->append_page(create_contact_detail_page());
	$notebook->append_page(create_new_todo_page());
	$notebook->show();
	$notebook->set_show_border(0);
	$notebook->set_show_tabs(0);
	$main_vbox->pack_start($notebook,1,1,0);

	return $main_vbox;
}

if(!(-e "$ENV{HOME}/.contacts")) {
	mkdir "$ENV{HOME}/.contacts", 0700;
}
$main_window = new Gtk::Window '-toplevel';
$main_window->set_title("Personal Information Manager");
$main_window->set_policy(1,1,0);

$main_window->add(create_main_window());

$main_window->signal_connect('destroy',\&exit_application);
$main_window->signal_connect('delete_event',\&exit_application);

$main_window->show();

Gtk->main();
