#!/bin/bash

indent -i3 -bl -bad -nbap -sob -ncdb -di20 -nbc -lp -nce -npcs -sc -ncs -l80 \
*.c *.h >& /dev/null

if [ "$1" = "commit" -o "$1" = "ci" -o "$1" = "com" ]; then
  echo "#define E_CHECKOUT_DATE \"\$Date\$\"" > timestamp.h
fi
cvs -z3 $@

if [ $USER = raster ]; then 
 indent -i3 -bl -bad -nbap -sob -ncdb -di20 -nbc -lp -nce -npcs -sc -ncs -l80 \
 *.c *.h >& /dev/null
elif [ $USER = kimball ]; then
 indent -bad -bap -bli0 -cli0 -ss -di20 -nbc -lp -i4 -ts4 -ncs -nce -npcs \
 -sc -ncdb *.c *.h 1>/dev/null 2>&1
elif [ $USER = mike ]; then 
 indent -i2 -bl -bad -nbap -sob -ncdb -di20 -nbc -lp -nce -npcs -sc -ncs -l80 \
 *.c *.h >& /dev/null
fi


rm *~
touch timestamp.h
