#!/bin/sh

doxygen

if [ "$1" = "-graph" ];
then
	perl tools/inherit.pl doc/xml
fi

if [ ! -e doc/html/images ]; then
    mkdir -p doc/html/images
fi

cp doc/images/*.png doc/images/*.gif doc/html/images
