#!/bin/bash

# Codenames for Debian suites according to their alias. Update these when
# needed.
UNSTABLE_CODENAME="sid"
TESTING_CODENAME="squeeze"
STABLE_CODENAME="lenny"

# List of Debian suites.
DEBIAN_SUITES=($UNSTABLE_CODENAME $TESTING_CODENAME $STABLE_CODENAME
    "unstable" "testing" "stable")

# List of Ubuntu suites. Update these when needed.
UBUNTU_SUITES=("karmic" "jaunty" "intrepid" "hardy")

# Mirrors to use. Update these to your preferred mirror.
DEBIAN_MIRROR="ftp.debian.org"
UBUNTU_MIRROR="archive.ubuntu.com"
UBUNTU_PORTS_MIRROR="ports.ubuntu.com"

# Optionally set the architecture to the host architecture if none set. Note
# that you can set your own default (i.e. ${ARCH:="i386"}).
: ${ARCH:="$(dpkg --print-architecture)"}

# Set the PBUILDERPLACE if none set.
if [ -z "$PBUILDERPLACE" ]; then
	PBUILDERPLACE="/var/cache/pbuilder"
fi

NAME="$DIST"
if [ -n "${ARCH}" ]; then
    NAME="$DIST-$ARCH"
    DEBOOTSTRAPOPTS=("--arch" "$ARCH" "${DEBOOTSTRAPOPTS[@]}")
fi

DISTRIBUTION="$DIST"
BASETGZ="$PBUILDERPLACE/$NAME-base.tgz"
BUILDRESULT="$PBUILDERPLACE/$NAME/result/"
APTCACHE="$PBUILDERPLACE/$NAME/aptcache/"
BUILDPLACE="$PBUILDERPLACE/build/"

if $(echo ${DEBIAN_SUITES[@]} | grep -q "$DIST"); then
    # Debian configuration
    MIRRORSITE="http://$DEBIAN_MIRROR/debian/"
    COMPONENTS="main contrib non-free"
elif $(echo ${UBUNTU_SUITES[@]} | grep -q "$DIST"); then
    # Ubuntu configuration
    MIRRORSITE="http://$UBUNTU_MIRROR/ubuntu/"
    COMPONENTS="main restricted universe multiverse"
else
    echo "Unknown distribution: $DIST"
    exit 1
fi

case $ARCH in
	armel|lpia)
		if $(echo ${UBUNTU_SUITES[@]} | grep -q "$DIST"); then
    			MIRRORSITE="http://$UBUNTU_PORTS_MIRROR/ubuntu-ports/"
		fi
	;;
esac

OTHERMIRROR="deb file://$PBUILDERPLACE/$NAME/result/ /"

if $(echo ${UBUNTU_SUITES[@]} | grep -q "$DIST"); then
	case $ARCH in
		armel|lpia)
			if [ -z "$OTHERMIRROR" ]; then
				OTHERMIRROR="deb http://$UBUNTU_PORTS_MIRROR/ubuntu-ports/ $DIST-security $COMPONENTS | deb http://$UBUNTU_PORTS_MIRROR/ubuntu-ports/ $DIST-updates $COMPONENTS"
			else
				OTHERMIRROR="$OTHERMIRROR | deb http://$UBUNTU_PORTS_MIRROR/ubuntu-ports/ $DIST-security $COMPONENTS | deb http://$UBUNTU_PORTS_MIRROR/ubuntu-ports/ $DIST-updates $COMPONENTS"
			fi
		;;
		*)
			if [ -z "$OTHERMIRROR" ]; then
				OTHERMIRROR="deb http://$UBUNTU_MIRROR/ubuntu/ $DIST-security $COMPONENTS | deb http://$UBUNTU_MIRROR/ubuntu/ $DIST-updates $COMPONENTS"
			else
				OTHERMIRROR="$OTHERMIRROR | deb http://$UBUNTU_MIRROR/ubuntu/ $DIST-security $COMPONENTS | deb http://$UBUNTU_MIRROR/ubuntu/ $DIST-updates $COMPONENTS"
			fi
		;;
	esac
fi

# ccache
sudo mkdir -p $PBUILDERPLACE/ccache
sudo chmod a+w $PBUILDERPLACE/ccache
export CCACHE_DIR="$PBUILDERPLACE/ccache"
export PATH="/usr/lib/ccache:${PATH}"
BINDMOUNTS="${CCACHE_DIR} $PBUILDERPLACE/$NAME/result"

# build dependencies + ccache

BUILDDEPENDS="cdbs m4 autoconf automake automake1.4 automake1.7 automake1.9 libtool pkg-config texinfo zlib1g-dev libpng12-dev libjpeg62-dev libfreetype6-dev xorg-dev libx11-dev libx11-xcb-dev x11proto-.*-dev libdbus-1-dev libdbus-glib-1-dev dbus dbus-x11 hal libhal-dev libhal-storage-dev libpam0g-dev libpam-runtime librsvg2-dev libinotifytools0-dev inotify-tools curl libcurl3 libcurl3-openssl-dev libcurl4-openssl-dev openssl openssl-blacklist libungif4-dev libungif4g libtiff4-dev cvs libmpd-dev libasound2-dev libxine1 locales wpasupplicant git gettext git-core subversion libdirectfb-bin libdirectfb-dev libxslt1-dev libx11* xsltproc flex bison python-dbus python-setuptools libdirectfb-dev python-all-dev python-pyrex thunar mpd xorg-dev doxygen"
EXTRAPACKAGES="$BUILDDEPENDS ccache"
