#!/bin/bash
#
# Begin exchange.SlackBuild

NAME=exchange
BUILD=1jp
CWD=$(pwd)

# Get functions
. ../functions
set_env

# Go to source code
cd ../../../PROTO/${NAME}
prepare_src

# Configure
CFLAGS=${SCFLAGS} CXXFLAGS=${SCFLAGS} \
  ./autogen.sh \
    --prefix=/usr \
    --libdir=${LIBDIR} \
    --build=${ARCH}-slackware-linux

# Install
make_install
install_doc AUTHORS COPYING* ChangeLog INSTALL README TODO

# Build the package
post_clean
pack_slack

# End exchange.SlackBuild
