<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddComment extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('comment', array (
  'id' => 
  array (
    'primary' => true,
    'autoincrement' => true,
    'type' => 'integer',
    'length' => 4,
  ),
  'comment' => 
  array (
    'type' => 'string',
    'length' => 2147483647,
  ),
  'application_id' => 
  array (
    'type' => 'integer',
    'length' => 4,
  ),
  'madule_id' => 
  array (
    'type' => 'integer',
    'length' => 4,
  ),
  'theme_id' => 
  array (
    'type' => 'integer',
    'length' => 4,
  ),
  'user_id' => 
  array (
    'type' => 'integer',
    'length' => 4,
  ),
  'created_at' => 
  array (
    'type' => 'timestamp',
    'length' => 25,
  ),
  'updated_at' => 
  array (
    'type' => 'timestamp',
    'length' => 25,
  ),
), array (
  'indexes' => 
  array (
  ),
  'primary' => 
  array (
    0 => 'id',
  ),
));
	}

	public function down()
	{
		$this->dropTable('comment');
	}
}