<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddRating extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('rating', array (
  'id' => 
  array (
    'primary' => true,
    'autoincrement' => true,
    'type' => 'integer',
    'length' => 4,
  ),
  'value' => 
  array (
    'type' => 'integer',
    'length' => 4,
  ),
  'application_id' => 
  array (
    'type' => 'integer',
    'length' => 4,
  ),
  'madule_id' => 
  array (
    'type' => 'integer',
    'length' => 4,
  ),
  'theme_id' => 
  array (
    'type' => 'integer',
    'length' => 4,
  ),
  'user_id' => 
  array (
    'type' => 'integer',
    'length' => 4,
  ),
), array (
  'indexes' => 
  array (
  ),
  'primary' => 
  array (
    0 => 'id',
  ),
));
	}

	public function down()
	{
		$this->dropTable('rating');
	}
}