<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddUser extends Doctrine_Migration
{
	public function up()
	{
		$this->createTable('user', array (
  'id' => 
  array (
    'primary' => true,
    'autoincrement' => true,
    'type' => 'integer',
    'length' => 4,
  ),
  'name' => 
  array (
    'type' => 'string',
    'length' => 255,
  ),
  'email' => 
  array (
    'type' => 'string',
    'length' => 255,
  ),
  'password' => 
  array (
    'type' => 'string',
    'length' => 255,
  ),
  'role' => 
  array (
    'type' => 'integer',
    'length' => 4,
  ),
  'hash' => 
  array (
    'type' => 'string',
    'length' => 50,
  ),
  'api_key' => 
  array (
    'type' => 'string',
    'length' => 50,
  ),
  'active' => 
  array (
    'type' => 'boolean',
    'length' => 25,
  ),
  'created_at' => 
  array (
    'type' => 'timestamp',
    'length' => 25,
  ),
  'updated_at' => 
  array (
    'type' => 'timestamp',
    'length' => 25,
  ),
), array (
  'indexes' => 
  array (
  ),
  'primary' => 
  array (
    0 => 'id',
  ),
));
	}

	public function down()
	{
		$this->dropTable('user');
	}
}