<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplyForeignKeyConstraints extends Doctrine_Migration
{
	public function up()
	{
		$this->createForeignKey('theme_theme_group', array (
  'local' => 'theme_id',
  'foreign' => 'id',
  'foreignTable' => 'theme',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'theme_theme_group_theme_theme_id_id',
));		$this->createForeignKey('theme_theme_group', array (
  'local' => 'theme_group_id',
  'foreign' => 'id',
  'foreignTable' => 'theme_group',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'theme_theme_group_theme_group_theme_group_id_id',
));		$this->createForeignKey('application', array (
  'local' => 'user_id',
  'foreign' => 'id',
  'foreignTable' => 'user',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'application_user_user_id_id',
));		$this->createForeignKey('madule', array (
  'local' => 'user_id',
  'foreign' => 'id',
  'foreignTable' => 'user',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'madule_user_user_id_id',
));		$this->createForeignKey('madule', array (
  'local' => 'application_id',
  'foreign' => 'id',
  'foreignTable' => 'application',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'madule_application_application_id_id',
));		$this->createForeignKey('comment', array (
  'local' => 'application_id',
  'foreign' => 'id',
  'foreignTable' => 'application',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'comment_application_application_id_id',
));		$this->createForeignKey('comment', array (
  'local' => 'madule_id',
  'foreign' => 'id',
  'foreignTable' => 'madule',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'comment_madule_madule_id_id',
));		$this->createForeignKey('comment', array (
  'local' => 'theme_id',
  'foreign' => 'id',
  'foreignTable' => 'theme',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'comment_theme_theme_id_id',
));		$this->createForeignKey('comment', array (
  'local' => 'user_id',
  'foreign' => 'id',
  'foreignTable' => 'user',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'comment_user_user_id_id',
));		$this->createForeignKey('rating', array (
  'local' => 'application_id',
  'foreign' => 'id',
  'foreignTable' => 'application',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'rating_application_application_id_id',
));		$this->createForeignKey('rating', array (
  'local' => 'madule_id',
  'foreign' => 'id',
  'foreignTable' => 'madule',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'rating_madule_madule_id_id',
));		$this->createForeignKey('rating', array (
  'local' => 'theme_id',
  'foreign' => 'id',
  'foreignTable' => 'theme',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'rating_theme_theme_id_id',
));		$this->createForeignKey('rating', array (
  'local' => 'user_id',
  'foreign' => 'id',
  'foreignTable' => 'user',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'rating_user_user_id_id',
));		$this->createForeignKey('application_theme_group', array (
  'local' => 'application_id',
  'foreign' => 'id',
  'foreignTable' => 'application',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'application_theme_group_application_application_id_id',
));		$this->createForeignKey('application_theme_group', array (
  'local' => 'theme_group_id',
  'foreign' => 'id',
  'foreignTable' => 'theme_group',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'application_theme_group_theme_group_theme_group_id_id',
));		$this->createForeignKey('theme', array (
  'local' => 'user_id',
  'foreign' => 'id',
  'foreignTable' => 'user',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'theme_user_user_id_id',
));		$this->createForeignKey('object_theme_group', array (
  'local' => 'object_id',
  'foreign' => 'id',
  'foreignTable' => 'object',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'object_theme_group_object_object_id_id',
));		$this->createForeignKey('object_theme_group', array (
  'local' => 'theme_group_id',
  'foreign' => 'id',
  'foreignTable' => 'theme_group',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'object_theme_group_theme_group_theme_group_id_id',
));		$this->createForeignKey('object', array (
  'local' => 'user_id',
  'foreign' => 'id',
  'foreignTable' => 'user',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'object_user_user_id_id',
));		$this->createForeignKey('madule_theme_group', array (
  'local' => 'madule_id',
  'foreign' => 'id',
  'foreignTable' => 'madule',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'madule_theme_group_madule_madule_id_id',
));		$this->createForeignKey('madule_theme_group', array (
  'local' => 'theme_group_id',
  'foreign' => 'id',
  'foreignTable' => 'theme_group',
  'onUpdate' => NULL,
  'onDelete' => NULL,
  'name' => 'madule_theme_group_theme_group_theme_group_id_id',
));
	}

	public function down()
	{
		$this->dropForeignKey('theme_theme_group', 'theme_theme_group_theme_theme_id_id');
		$this->dropForeignKey('theme_theme_group', 'theme_theme_group_theme_group_theme_group_id_id');
		$this->dropForeignKey('application', 'application_user_user_id_id');
		$this->dropForeignKey('madule', 'madule_user_user_id_id');
		$this->dropForeignKey('madule', 'madule_application_application_id_id');
		$this->dropForeignKey('comment', 'comment_application_application_id_id');
		$this->dropForeignKey('comment', 'comment_madule_madule_id_id');
		$this->dropForeignKey('comment', 'comment_theme_theme_id_id');
		$this->dropForeignKey('comment', 'comment_user_user_id_id');
		$this->dropForeignKey('rating', 'rating_application_application_id_id');
		$this->dropForeignKey('rating', 'rating_madule_madule_id_id');
		$this->dropForeignKey('rating', 'rating_theme_theme_id_id');
		$this->dropForeignKey('rating', 'rating_user_user_id_id');
		$this->dropForeignKey('application_theme_group', 'application_theme_group_application_application_id_id');
		$this->dropForeignKey('application_theme_group', 'application_theme_group_theme_group_theme_group_id_id');
		$this->dropForeignKey('theme', 'theme_user_user_id_id');
		$this->dropForeignKey('object_theme_group', 'object_theme_group_object_object_id_id');
		$this->dropForeignKey('object_theme_group', 'object_theme_group_theme_group_theme_group_id_id');
		$this->dropForeignKey('object', 'object_user_user_id_id');
		$this->dropForeignKey('madule_theme_group', 'madule_theme_group_madule_madule_id_id');
		$this->dropForeignKey('madule_theme_group', 'madule_theme_group_theme_group_theme_group_id_id');

	}
}