<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Metadata extends Doctrine_Migration
{
	public function up()
	{
		$this->addColumn('theme', 'author', 'string', array('length' => 255));
		$this->addColumn('theme', 'license', 'string', array('length' => 255));
		$this->addColumn('theme', 'version', 'string', array('length' => 255));
	}

	public function down()
	{
		$this->removeColumn('theme', 'version');
		$this->removeColumn('theme', 'license');
		$this->removeColumn('theme', 'author');
	}
}