#!/bin/sh
##############################################################################
# queries sizes of your enlightenment cache                                  #
# Copyright 1999 The Rasterman                                               #
##############################################################################

export PATH=$PATH:"/usr/local/enlightenment/bin:/usr/enlightenment/bin:/opt/enlightenment/bin:/usr/local/bin"

if [ $# -lt 1 ]; then
  echo "usage:"
  echo "    "$0" [ all | pager | bgsel | config ]"
  exit
fi

if [ $1 = "all" ]; then
  VAL=`du -s $HOME/.enlightenment/cached/pager $HOME/.enlightenment/cached/bgsel $HOME/.enlightenment/cached/cfg | awk '{printf("%s ", $1);}'`
  TOT=0
  for I in $VAL; do
    TOT=$[ $TOT + $I ];
  done
  eesh -e "dialog_ok Your caches are using $TOT Kb of disk space."
  exit
fi

if [ $1 = "pager" ]; then
  VAL=`du -s $HOME/.enlightenment/cached/pager | awk '{printf("%s", $1);}'`
  eesh -e "dialog_ok Your pager background cache is using $VAL Kb of disk space."
  exit
fi

if [ $1 = "config" ]; then
  VAL=`du -s $HOME/.enlightenment/cached/cfg | awk '{printf("%s", $1);}'`
  eesh -e "dialog_ok Your config file cache is using $VAL Kb of disk space."
  exit
fi

if [ $1 = "bgsel" ]; then
  VAL=`du -s $HOME/.enlightenment/cached/bgsel | awk '{printf("%s", $1);}'`
  eesh -e "dialog_ok Your background selector cache is using $VAL Kb of disk space."
  exit
fi
