#!/bin/sh
##############################################################################
# cleans up parts of your enlightenment cache                                #
#
# Copyright (C) 1999-2006 Carsten Haitzler, Geoff Harrison and various contributors
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies of the Software, its documentation and marketing & publicity
# materials, and acknowledgment shall be given in the documentation, materials
# and software packages that this Software was used.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##############################################################################

PATH=$PATH:$EBIN:$EROOT/scripts
export PATH

if [ $# -lt 1 ]; then
  echo "usage:"
  echo "    "$0" [ all | pager | bgsel | config ]"
  exit
fi

if [ $1 = "all" ]; then
  rm -rf $ECACHEDIR/cached/*/* >/dev/null 2>&1
  rm -rf $ECACHEDIR/cached/*/.* >/dev/null 2>&1
  eesh -e "dialog_ok All caches purged."
  exit
fi

if [ $1 = "pager" ]; then
  rm -rf $ECACHEDIR/cached/pager/* >/dev/null 2>&1
  rm -rf $ECACHEDIR/cached/pager/.* >/dev/null 2>&1
  eesh -e "dialog_ok Pager background cache purged."
  exit
fi

if [ $1 = "config" ]; then
  rm -rf $ECACHEDIR/cached/cfg/* >/dev/null 2>&1
  rm -rf $ECACHEDIR/cached/cfg/.* >/dev/null 2>&1
  eesh -e "dialog_ok Config file cache purged."
  exit
fi

if [ $1 = "bgsel" ]; then
  rm -rf $ECACHEDIR/cached/bgsel/* >/dev/null 2>&1
  rm -rf $ECACHEDIR/cached/bgsel/.* >/dev/null 2>&1
  eesh -e "dialog_ok Background selector cache purged."
  exit
fi
