#!/bin/bash

edb_ed menu.db add /normal str resources/pics/normal.png
edb_ed menu.db add /hilighted str resources/pics/hilighted.png
edb_ed menu.db add /active str resources/pics/active.png

edb_ed menu.db add /menu/box/count int 18

edb_ed menu.db add /menu/box/0/name str top
edb_ed menu.db add /menu/box/0/count int 8

edb_ed menu.db add /menu/box/0/0/label str " File "
edb_ed menu.db add /menu/box/0/0/pic str NULL
edb_ed menu.db add /menu/box/0/0/action_class int 1 
edb_ed menu.db add /menu/box/0/0/param str "file.menu"

edb_ed menu.db add /menu/box/0/1/label str " Edit "
edb_ed menu.db add /menu/box/0/1/pic str NULL
edb_ed menu.db add /menu/box/0/1/action_class int 1
edb_ed menu.db add /menu/box/0/1/param str "edit.menu"

edb_ed menu.db add /menu/box/0/2/label str " View "
edb_ed menu.db add /menu/box/0/2/pic str NULL
edb_ed menu.db add /menu/box/0/2/action_class int 1
edb_ed menu.db add /menu/box/0/2/param str "view.menu"

edb_ed menu.db add /menu/box/0/3/label str " Context "
edb_ed menu.db add /menu/box/0/3/pic str NULL
edb_ed menu.db add /menu/box/0/3/action_class int 1
edb_ed menu.db add /menu/box/0/3/param str "topcontext.menu"

edb_ed menu.db add /menu/box/0/4/label str " Draw "
edb_ed menu.db add /menu/box/0/4/pic str NULL
edb_ed menu.db add /menu/box/0/4/action_class int 1
edb_ed menu.db add /menu/box/0/4/param str "draw.menu"

edb_ed menu.db add /menu/box/0/5/label str " Modify "
edb_ed menu.db add /menu/box/0/5/pic str NULL
edb_ed menu.db add /menu/box/0/5/action_class int 1
edb_ed menu.db add /menu/box/0/5/param str "modify.menu"

edb_ed menu.db add /menu/box/0/6/label str " Layers "
edb_ed menu.db add /menu/box/0/6/pic str NULL
edb_ed menu.db add /menu/box/0/6/action_class int 1
edb_ed menu.db add /menu/box/0/6/param str "layers.menu"

edb_ed menu.db add /menu/box/0/7/label str " Help "
edb_ed menu.db add /menu/box/0/7/pic str NULL
edb_ed menu.db add /menu/box/0/7/action_class int 1
edb_ed menu.db add /menu/box/0/7/param str "help.menu"



edb_ed menu.db add /menu/box/1/name str file.menu
edb_ed menu.db add /menu/box/1/count int 10

edb_ed menu.db add /menu/box/1/0/label str " New "
edb_ed menu.db add /menu/box/1/0/pic str NULL
edb_ed menu.db add /menu/box/1/0/action_class int 0
edb_ed menu.db add /menu/box/1/0/param str "new_drawing"

edb_ed menu.db add /menu/box/1/1/label str " Open "
edb_ed menu.db add /menu/box/1/1/pic str NULL
edb_ed menu.db add /menu/box/1/1/action_class int 0
edb_ed menu.db add /menu/box/1/1/param str "open"

edb_ed menu.db add /menu/box/1/2/label str " Save "
edb_ed menu.db add /menu/box/1/2/pic str NULL
edb_ed menu.db add /menu/box/1/2/action_class int 0
edb_ed menu.db add /menu/box/1/2/param str "save"

edb_ed menu.db add /menu/box/1/3/label str " Save as... "
edb_ed menu.db add /menu/box/1/3/pic str NULL
edb_ed menu.db add /menu/box/1/3/action_class int 0
edb_ed menu.db add /menu/box/1/3/param str "save_as"

edb_ed menu.db add /menu/box/1/4/label str " Sep "
edb_ed menu.db add /menu/box/1/4/pic str NULL
edb_ed menu.db add /menu/box/1/4/action_class int 3
edb_ed menu.db add /menu/box/1/4/param str "-"

edb_ed menu.db add /menu/box/1/5/label str " Paper size "
edb_ed menu.db add /menu/box/1/5/pic str NULL
edb_ed menu.db add /menu/box/1/5/action_class int 2
edb_ed menu.db add /menu/box/1/5/param str "paper_sizes.menu"

edb_ed menu.db add /menu/box/1/6/label str " Sep "
edb_ed menu.db add /menu/box/1/6/pic str NULL
edb_ed menu.db add /menu/box/1/6/action_class int 3
edb_ed menu.db add /menu/box/1/6/param str "-"

edb_ed menu.db add /menu/box/1/7/label str " Print "
edb_ed menu.db add /menu/box/1/7/pic str NULL
edb_ed menu.db add /menu/box/1/7/action_class int 2
edb_ed menu.db add /menu/box/1/7/param str "print.menu"

edb_ed menu.db add /menu/box/1/8/label str " Sep "
edb_ed menu.db add /menu/box/1/8/pic str NULL
edb_ed menu.db add /menu/box/1/8/action_class int 3
edb_ed menu.db add /menu/box/1/8/param str "-"

edb_ed menu.db add /menu/box/1/9/label str " Quit "
edb_ed menu.db add /menu/box/1/9/pic str NULL
edb_ed menu.db add /menu/box/1/9/action_class int 0
edb_ed menu.db add /menu/box/1/9/param str "_exit"


edb_ed menu.db add /menu/box/2/name str "paper_sizes.menu"
edb_ed menu.db add /menu/box/2/count int 10

edb_ed menu.db add /menu/box/2/0/label str " A4 portrait "
edb_ed menu.db add /menu/box/2/0/pic str NULL
edb_ed menu.db add /menu/box/2/0/action_class int 0
edb_ed menu.db add /menu/box/2/0/param str "new_drawing|4|0|1|210 297"

edb_ed menu.db add /menu/box/2/1/label str " A4 landscape "
edb_ed menu.db add /menu/box/2/1/pic str NULL
edb_ed menu.db add /menu/box/2/1/action_class int 0
edb_ed menu.db add /menu/box/2/1/param str "new_drawing|4|0|1|297 210"

edb_ed menu.db add /menu/box/2/2/label str " A3 portrait "
edb_ed menu.db add /menu/box/2/2/pic str NULL
edb_ed menu.db add /menu/box/2/2/action_class int 0
edb_ed menu.db add /menu/box/2/2/param str "new_drawing|4|0|1|297 420"

edb_ed menu.db add /menu/box/2/3/label str " A3 landscape "
edb_ed menu.db add /menu/box/2/3/pic str NULL
edb_ed menu.db add /menu/box/2/3/action_class int 0
edb_ed menu.db add /menu/box/2/3/param str "new_drawing|4|0|1|420 297"

edb_ed menu.db add /menu/box/2/4/label str " A2 portrait "
edb_ed menu.db add /menu/box/2/4/pic str NULL
edb_ed menu.db add /menu/box/2/4/action_class int 0
edb_ed menu.db add /menu/box/2/4/param str "new_drawing|4|0|1|420 594"

edb_ed menu.db add /menu/box/2/5/label str " A2 landscape "
edb_ed menu.db add /menu/box/2/5/pic str NULL
edb_ed menu.db add /menu/box/2/5/action_class int 0
edb_ed menu.db add /menu/box/2/5/param str "new_drawing|4|0|1|594 420"

edb_ed menu.db add /menu/box/2/6/label str " A1 portrait "
edb_ed menu.db add /menu/box/2/6/pic str NULL
edb_ed menu.db add /menu/box/2/6/action_class int 0
edb_ed menu.db add /menu/box/2/6/param str "new_drawing|4|0|1|594 841"

edb_ed menu.db add /menu/box/2/7/label str " A1 landscape "
edb_ed menu.db add /menu/box/2/7/pic str NULL
edb_ed menu.db add /menu/box/2/7/action_class int 0
edb_ed menu.db add /menu/box/2/7/param str "new_drawing|4|0|1|841 594"

edb_ed menu.db add /menu/box/2/8/label str " Sep "
edb_ed menu.db add /menu/box/2/8/pic str NULL
edb_ed menu.db add /menu/box/2/8/action_class int 3
edb_ed menu.db add /menu/box/2/8/param str "-"

edb_ed menu.db add /menu/box/2/9/label str " Another "
edb_ed menu.db add /menu/box/2/9/pic str NULL
edb_ed menu.db add /menu/box/2/9/action_class int 0
edb_ed menu.db add /menu/box/2/9/param str "new_drawing|4|0|1"





edb_ed menu.db add /menu/box/3/name str print.menu
edb_ed menu.db add /menu/box/3/count int 1

edb_ed menu.db add /menu/box/3/0/label str " Raster image "
edb_ed menu.db add /menu/box/3/0/pic str NULL
edb_ed menu.db add /menu/box/3/0/action_class int 0
edb_ed menu.db add /menu/box/3/0/param str "save_image"



edb_ed menu.db add /menu/box/4/name str edit.menu
edb_ed menu.db add /menu/box/4/count int 8

edb_ed menu.db add /menu/box/4/0/label str " Undo "
edb_ed menu.db add /menu/box/4/0/pic str NULL
edb_ed menu.db add /menu/box/4/0/action_class int 0
edb_ed menu.db add /menu/box/4/0/param str "undo"

edb_ed menu.db add /menu/box/4/1/label str " Redo "
edb_ed menu.db add /menu/box/4/1/pic str NULL
edb_ed menu.db add /menu/box/4/1/action_class int 0
edb_ed menu.db add /menu/box/4/1/param str "redo"

edb_ed menu.db add /menu/box/4/2/label str " Sep "
edb_ed menu.db add /menu/box/4/2/pic str NULL
edb_ed menu.db add /menu/box/4/2/action_class int 3
edb_ed menu.db add /menu/box/4/2/param str "-"

edb_ed menu.db add /menu/box/4/3/label str " Cut "
edb_ed menu.db add /menu/box/4/3/pic str NULL
edb_ed menu.db add /menu/box/4/3/action_class int 0
edb_ed menu.db add /menu/box/4/3/param str "cut|0 0"

edb_ed menu.db add /menu/box/4/4/label str " Copy "
edb_ed menu.db add /menu/box/4/4/pic str NULL
edb_ed menu.db add /menu/box/4/4/action_class int 0
edb_ed menu.db add /menu/box/4/4/param str "copy|0 0"

edb_ed menu.db add /menu/box/4/5/label str " Copy with base point "
edb_ed menu.db add /menu/box/4/5/pic str NULL
edb_ed menu.db add /menu/box/4/5/action_class int 0
edb_ed menu.db add /menu/box/4/5/param str "undo"

edb_ed menu.db add /menu/box/4/6/label str " Paste "
edb_ed menu.db add /menu/box/4/6/pic str NULL
edb_ed menu.db add /menu/box/4/6/action_class int 0
edb_ed menu.db add /menu/box/4/6/param str "paste"

edb_ed menu.db add /menu/box/4/7/label str " Paste to origin "
edb_ed menu.db add /menu/box/4/7/pic str NULL
edb_ed menu.db add /menu/box/4/7/action_class int 0
edb_ed menu.db add /menu/box/4/7/param str "paste|0 0"



edb_ed menu.db add /menu/box/5/name str view.menu
edb_ed menu.db add /menu/box/5/count int 5

edb_ed menu.db add /menu/box/5/0/label str " Toggle command line "
edb_ed menu.db add /menu/box/5/0/pic str NULL
edb_ed menu.db add /menu/box/5/0/action_class int 0
edb_ed menu.db add /menu/box/5/0/param str "cl_toggle"

edb_ed menu.db add /menu/box/5/1/label str " Toggle logs "
edb_ed menu.db add /menu/box/5/1/pic str NULL
edb_ed menu.db add /menu/box/5/1/action_class int 0
edb_ed menu.db add /menu/box/5/1/param str "log_toggle"

edb_ed menu.db add /menu/box/5/2/label str " Toggle info panel "
edb_ed menu.db add /menu/box/5/2/pic str NULL
edb_ed menu.db add /menu/box/5/2/action_class int 0
edb_ed menu.db add /menu/box/5/2/param str "info_toggle"

edb_ed menu.db add /menu/box/5/3/label str "Sep"
edb_ed menu.db add /menu/box/5/3/pic str NULL
edb_ed menu.db add /menu/box/5/3/action_class int 3
edb_ed menu.db add /menu/box/5/3/param str "-"

edb_ed menu.db add /menu/box/5/4/label str " Line weight toggle "
edb_ed menu.db add /menu/box/5/4/pic str NULL
edb_ed menu.db add /menu/box/5/4/action_class int 0
edb_ed menu.db add /menu/box/5/4/param str "_set_show_thickness|0"





edb_ed menu.db add /menu/box/6/name str context.menu
edb_ed menu.db add /menu/box/6/count int 7

edb_ed menu.db add /menu/box/6/0/label str "socket1"
edb_ed menu.db add /menu/box/6/0/pic str NULL
edb_ed menu.db add /menu/box/6/0/action_class int 4
edb_ed menu.db add /menu/box/6/0/param str " "

edb_ed menu.db add /menu/box/6/1/label str "Sep"
edb_ed menu.db add /menu/box/6/1/pic str NULL
edb_ed menu.db add /menu/box/6/1/action_class int 3
edb_ed menu.db add /menu/box/6/1/param str "-"

edb_ed menu.db add /menu/box/6/2/label str " Copy with base point "
edb_ed menu.db add /menu/box/6/2/pic str NULL
edb_ed menu.db add /menu/box/6/2/action_class int 0
edb_ed menu.db add /menu/box/6/2/param str "copy"

edb_ed menu.db add /menu/box/6/3/label str " Deselect all "
edb_ed menu.db add /menu/box/6/3/pic str NULL
edb_ed menu.db add /menu/box/6/3/action_class int 0
edb_ed menu.db add /menu/box/6/3/param str "deselect_all"

edb_ed menu.db add /menu/box/6/4/label str " Set text "
edb_ed menu.db add /menu/box/6/4/pic str NULL
edb_ed menu.db add /menu/box/6/4/action_class int 0
edb_ed menu.db add /menu/box/6/4/param str "set_text"

edb_ed menu.db add /menu/box/6/5/label str " Sep "
edb_ed menu.db add /menu/box/6/5/pic str NULL
edb_ed menu.db add /menu/box/6/5/action_class int 3
edb_ed menu.db add /menu/box/6/5/param str "-"

edb_ed menu.db add /menu/box/6/6/label str " Cancel "
edb_ed menu.db add /menu/box/6/6/pic str NULL
edb_ed menu.db add /menu/box/6/6/action_class int 0
edb_ed menu.db add /menu/box/6/6/param str "cancel"









edb_ed menu.db add /menu/box/7/name str layers.menu
edb_ed menu.db add /menu/box/7/count int 27

edb_ed menu.db add /menu/box/7/0/label str " Hide current layer "
edb_ed menu.db add /menu/box/7/0/pic str NULL
edb_ed menu.db add /menu/box/7/0/action_class int 0
edb_ed menu.db add /menu/box/7/0/param str "'hide_layer"

edb_ed menu.db add /menu/box/7/1/label str " Show current layer "
edb_ed menu.db add /menu/box/7/1/pic str NULL
edb_ed menu.db add /menu/box/7/1/action_class int 0
edb_ed menu.db add /menu/box/7/1/param str "'show layer"

edb_ed menu.db add /menu/box/7/2/label str " Hide all layers "
edb_ed menu.db add /menu/box/7/2/pic str NULL
edb_ed menu.db add /menu/box/7/2/action_class int 0
edb_ed menu.db add /menu/box/7/2/param str "'hide_layers"

edb_ed menu.db add /menu/box/7/3/label str " Show all layers "
edb_ed menu.db add /menu/box/7/3/pic str NULL
edb_ed menu.db add /menu/box/7/3/action_class int 0
edb_ed menu.db add /menu/box/7/3/param str "'show_layers"

edb_ed menu.db add /menu/box/7/4/label str "Sep"
edb_ed menu.db add /menu/box/7/4/pic str NULL
edb_ed menu.db add /menu/box/7/4/action_class int 3
edb_ed menu.db add /menu/box/7/4/param str "-"

edb_ed menu.db add /menu/box/7/5/label str " New Layer "
edb_ed menu.db add /menu/box/7/5/pic str NULL
edb_ed menu.db add /menu/box/7/5/action_class int 0
edb_ed menu.db add /menu/box/7/5/param str "'set_layer"

edb_ed menu.db add /menu/box/7/6/label str "Sep"
edb_ed menu.db add /menu/box/7/6/pic str NULL
edb_ed menu.db add /menu/box/7/6/action_class int 3
edb_ed menu.db add /menu/box/7/6/param str "-"

edb_ed menu.db add /menu/box/7/7/label str "layer0"
edb_ed menu.db add /menu/box/7/7/pic str NULL
edb_ed menu.db add /menu/box/7/7/action_class int 4
edb_ed menu.db add /menu/box/7/7/param str " "

edb_ed menu.db add /menu/box/7/8/label str "layer1"
edb_ed menu.db add /menu/box/7/8/pic str NULL
edb_ed menu.db add /menu/box/7/8/action_class int 4
edb_ed menu.db add /menu/box/7/8/param str " "

edb_ed menu.db add /menu/box/7/9/label str "layer2"
edb_ed menu.db add /menu/box/7/9/pic str NULL
edb_ed menu.db add /menu/box/7/9/action_class int 4
edb_ed menu.db add /menu/box/7/9/param str " "

edb_ed menu.db add /menu/box/7/10/label str "layer3"
edb_ed menu.db add /menu/box/7/10/pic str NULL
edb_ed menu.db add /menu/box/7/10/action_class int 4
edb_ed menu.db add /menu/box/7/10/param str " "

edb_ed menu.db add /menu/box/7/11/label str "layer4"
edb_ed menu.db add /menu/box/7/11/pic str NULL
edb_ed menu.db add /menu/box/7/11/action_class int 4
edb_ed menu.db add /menu/box/7/11/param str " "

edb_ed menu.db add /menu/box/7/12/label str "layer5"
edb_ed menu.db add /menu/box/7/12/pic str NULL
edb_ed menu.db add /menu/box/7/12/action_class int 4
edb_ed menu.db add /menu/box/7/12/param str " "

edb_ed menu.db add /menu/box/7/13/label str "layer6"
edb_ed menu.db add /menu/box/7/13/pic str NULL
edb_ed menu.db add /menu/box/7/13/action_class int 4
edb_ed menu.db add /menu/box/7/13/param str " "

edb_ed menu.db add /menu/box/7/14/label str "layer7"
edb_ed menu.db add /menu/box/7/14/pic str NULL
edb_ed menu.db add /menu/box/7/14/action_class int 4
edb_ed menu.db add /menu/box/7/14/param str " "

edb_ed menu.db add /menu/box/7/15/label str "layer8"
edb_ed menu.db add /menu/box/7/15/pic str NULL
edb_ed menu.db add /menu/box/7/15/action_class int 4
edb_ed menu.db add /menu/box/7/15/param str " "

edb_ed menu.db add /menu/box/7/16/label str "layer9"
edb_ed menu.db add /menu/box/7/16/pic str NULL
edb_ed menu.db add /menu/box/7/16/action_class int 4
edb_ed menu.db add /menu/box/7/16/param str " "

edb_ed menu.db add /menu/box/7/17/label str "layer10"
edb_ed menu.db add /menu/box/7/17/pic str NULL
edb_ed menu.db add /menu/box/7/17/action_class int 4
edb_ed menu.db add /menu/box/7/17/param str " "

edb_ed menu.db add /menu/box/7/18/label str "layer11"
edb_ed menu.db add /menu/box/7/18/pic str NULL
edb_ed menu.db add /menu/box/7/18/action_class int 4
edb_ed menu.db add /menu/box/7/18/param str " "

edb_ed menu.db add /menu/box/7/19/label str "layer12"
edb_ed menu.db add /menu/box/7/19/pic str NULL
edb_ed menu.db add /menu/box/7/19/action_class int 4
edb_ed menu.db add /menu/box/7/19/param str " "

edb_ed menu.db add /menu/box/7/20/label str "layer13"
edb_ed menu.db add /menu/box/7/20/pic str NULL
edb_ed menu.db add /menu/box/7/20/action_class int 4
edb_ed menu.db add /menu/box/7/20/param str " "

edb_ed menu.db add /menu/box/7/21/label str "layer14"
edb_ed menu.db add /menu/box/7/21/pic str NULL
edb_ed menu.db add /menu/box/7/21/action_class int 4
edb_ed menu.db add /menu/box/7/21/param str " "

edb_ed menu.db add /menu/box/7/22/label str "layer15"
edb_ed menu.db add /menu/box/7/22/pic str NULL
edb_ed menu.db add /menu/box/7/22/action_class int 4
edb_ed menu.db add /menu/box/7/22/param str " "

edb_ed menu.db add /menu/box/7/23/label str "layer16"
edb_ed menu.db add /menu/box/7/23/pic str NULL
edb_ed menu.db add /menu/box/7/23/action_class int 4
edb_ed menu.db add /menu/box/7/23/param str " "

edb_ed menu.db add /menu/box/7/24/label str "layer17"
edb_ed menu.db add /menu/box/7/24/pic str NULL
edb_ed menu.db add /menu/box/7/24/action_class int 4
edb_ed menu.db add /menu/box/7/24/param str " "

edb_ed menu.db add /menu/box/7/25/label str "layer18"
edb_ed menu.db add /menu/box/7/25/pic str NULL
edb_ed menu.db add /menu/box/7/25/action_class int 4
edb_ed menu.db add /menu/box/7/25/param str " "

edb_ed menu.db add /menu/box/7/26/label str "layer19"
edb_ed menu.db add /menu/box/7/26/pic str NULL
edb_ed menu.db add /menu/box/7/26/action_class int 4
edb_ed menu.db add /menu/box/7/26/param str " "








edb_ed menu.db add /menu/box/8/name str draw.menu
edb_ed menu.db add /menu/box/8/count int 15

edb_ed menu.db add /menu/box/8/0/label str " Point "
edb_ed menu.db add /menu/box/8/0/pic str NULL
edb_ed menu.db add /menu/box/8/0/action_class int 0
edb_ed menu.db add /menu/box/8/0/param str "'point"

edb_ed menu.db add /menu/box/8/1/label str " Line "
edb_ed menu.db add /menu/box/8/1/pic str NULL
edb_ed menu.db add /menu/box/8/1/action_class int 0
edb_ed menu.db add /menu/box/8/1/param str "'line"

edb_ed menu.db add /menu/box/8/2/label str " Rectangle "
edb_ed menu.db add /menu/box/8/2/pic str NULL
edb_ed menu.db add /menu/box/8/2/action_class int 0
edb_ed menu.db add /menu/box/8/2/param str "'rectangle"

edb_ed menu.db add /menu/box/8/3/label str " Circle "
edb_ed menu.db add /menu/box/8/3/pic str NULL
edb_ed menu.db add /menu/box/8/3/action_class int 0
edb_ed menu.db add /menu/box/8/3/param str "'circle"

edb_ed menu.db add /menu/box/8/4/label str " Arc "
edb_ed menu.db add /menu/box/8/4/pic str NULL
edb_ed menu.db add /menu/box/8/4/action_class int 0
edb_ed menu.db add /menu/box/8/4/param str "'arc"

edb_ed menu.db add /menu/box/8/5/label str " Ellipse "
edb_ed menu.db add /menu/box/8/5/pic str NULL
edb_ed menu.db add /menu/box/8/5/action_class int 0
edb_ed menu.db add /menu/box/8/5/param str "'ellipse"

edb_ed menu.db add /menu/box/8/6/label str " Elliptic arc "
edb_ed menu.db add /menu/box/8/6/pic str NULL
edb_ed menu.db add /menu/box/8/6/action_class int 0
edb_ed menu.db add /menu/box/8/6/param str "'earc"

edb_ed menu.db add /menu/box/8/7/label str " Text "
edb_ed menu.db add /menu/box/8/7/pic str NULL
edb_ed menu.db add /menu/box/8/7/action_class int 0
edb_ed menu.db add /menu/box/8/7/param str "'text"

edb_ed menu.db add /menu/box/8/8/label str " Image "
edb_ed menu.db add /menu/box/8/8/pic str NULL
edb_ed menu.db add /menu/box/8/8/action_class int 0
edb_ed menu.db add /menu/box/8/8/param str "'image"

edb_ed menu.db add /menu/box/8/9/label str " Sep "
edb_ed menu.db add /menu/box/8/9/pic str NULL
edb_ed menu.db add /menu/box/8/9/action_class int 3
edb_ed menu.db add /menu/box/8/9/param str "-"

edb_ed menu.db add /menu/box/8/10/label str " Horizontal dimension "
edb_ed menu.db add /menu/box/8/10/pic str NULL
edb_ed menu.db add /menu/box/8/10/action_class int 0
edb_ed menu.db add /menu/box/8/10/param str "'dim_h"

edb_ed menu.db add /menu/box/8/11/label str " Vertical dimension "
edb_ed menu.db add /menu/box/8/11/pic str NULL
edb_ed menu.db add /menu/box/8/11/action_class int 0
edb_ed menu.db add /menu/box/8/11/param str "'dim_v"

edb_ed menu.db add /menu/box/8/12/label str " Aligned dimension "
edb_ed menu.db add /menu/box/8/12/pic str NULL
edb_ed menu.db add /menu/box/8/12/action_class int 0
edb_ed menu.db add /menu/box/8/12/param str "'dim_a"

edb_ed menu.db add /menu/box/8/13/label str "Sep"
edb_ed menu.db add /menu/box/8/13/pic str NULL
edb_ed menu.db add /menu/box/8/13/action_class int 3
edb_ed menu.db add /menu/box/8/13/param str "-"

edb_ed menu.db add /menu/box/8/14/label str " Hatch "
edb_ed menu.db add /menu/box/8/14/pic str NULL
edb_ed menu.db add /menu/box/8/14/action_class int 0
edb_ed menu.db add /menu/box/8/14/param str "'hatch"






edb_ed menu.db add /menu/box/9/name str modify.menu
edb_ed menu.db add /menu/box/9/count int 15

edb_ed menu.db add /menu/box/9/0/label str " Move objects "
edb_ed menu.db add /menu/box/9/0/pic str NULL
edb_ed menu.db add /menu/box/9/0/action_class int 0
edb_ed menu.db add /menu/box/9/0/param str "'move"

edb_ed menu.db add /menu/box/9/1/label str " Rotate objects "
edb_ed menu.db add /menu/box/9/1/pic str NULL
edb_ed menu.db add /menu/box/9/1/action_class int 0
edb_ed menu.db add /menu/box/9/1/param str "'rotate"

edb_ed menu.db add /menu/box/9/2/label str "Sep"
edb_ed menu.db add /menu/box/9/2/pic str NULL
edb_ed menu.db add /menu/box/9/2/action_class int 3
edb_ed menu.db add /menu/box/9/2/param str "-"

edb_ed menu.db add /menu/box/9/3/label str " Clone objects "
edb_ed menu.db add /menu/box/9/3/pic str NULL
edb_ed menu.db add /menu/box/9/3/action_class int 0
edb_ed menu.db add /menu/box/9/3/param str "'clone"

edb_ed menu.db add /menu/box/9/4/label str " Mirror objects "
edb_ed menu.db add /menu/box/9/4/pic str NULL
edb_ed menu.db add /menu/box/9/4/action_class int 0
edb_ed menu.db add /menu/box/9/4/param str "'mirror"

edb_ed menu.db add /menu/box/9/5/label str " Create array of objects "
edb_ed menu.db add /menu/box/9/5/pic str NULL
edb_ed menu.db add /menu/box/9/5/action_class int 0
edb_ed menu.db add /menu/box/9/5/param str "'array"

edb_ed menu.db add /menu/box/9/6/label str " Create polar array of objects "
edb_ed menu.db add /menu/box/9/6/pic str NULL
edb_ed menu.db add /menu/box/9/6/action_class int 0
edb_ed menu.db add /menu/box/9/6/param str "'polar"

edb_ed menu.db add /menu/box/9/7/label str "Sep"
edb_ed menu.db add /menu/box/9/7/pic str NULL
edb_ed menu.db add /menu/box/9/7/action_class int 3
edb_ed menu.db add /menu/box/9/7/param str "-"

edb_ed menu.db add /menu/box/9/8/label str " Trim lines and points "
edb_ed menu.db add /menu/box/9/8/pic str NULL
edb_ed menu.db add /menu/box/9/8/action_class int 0
edb_ed menu.db add /menu/box/9/8/param str "'trim"

edb_ed menu.db add /menu/box/9/9/label str " Delete objects "
edb_ed menu.db add /menu/box/9/9/pic str NULL
edb_ed menu.db add /menu/box/9/9/action_class int 0
edb_ed menu.db add /menu/box/9/9/param str "'delete"

edb_ed menu.db add /menu/box/9/10/label str "Sep"
edb_ed menu.db add /menu/box/9/10/pic str NULL
edb_ed menu.db add /menu/box/9/10/action_class int 3
edb_ed menu.db add /menu/box/9/10/param str "-"

edb_ed menu.db add /menu/box/9/11/label str " Scale objects "
edb_ed menu.db add /menu/box/9/11/pic str NULL
edb_ed menu.db add /menu/box/9/11/action_class int 0
edb_ed menu.db add /menu/box/9/11/param str "'scale"

edb_ed menu.db add /menu/box/9/12/label str " Scale objects by XY "
edb_ed menu.db add /menu/box/9/12/pic str NULL
edb_ed menu.db add /menu/box/9/12/action_class int 0
edb_ed menu.db add /menu/box/9/12/param str "'scale_xy"

edb_ed menu.db add /menu/box/9/13/label str "Sep"
edb_ed menu.db add /menu/box/9/13/pic str NULL
edb_ed menu.db add /menu/box/9/13/action_class int 3
edb_ed menu.db add /menu/box/9/13/param str "-"

edb_ed menu.db add /menu/box/9/14/label str " Edit text "
edb_ed menu.db add /menu/box/9/14/pic str NULL
edb_ed menu.db add /menu/box/9/14/action_class int 0
edb_ed menu.db add /menu/box/9/14/param str "'set_text"




edb_ed menu.db add /menu/box/10/name str topcontext.menu
edb_ed menu.db add /menu/box/10/count int 12

edb_ed menu.db add /menu/box/10/0/label str " Solid thick line "
edb_ed menu.db add /menu/box/10/0/pic str NULL
edb_ed menu.db add /menu/box/10/0/action_class int 0
edb_ed menu.db add /menu/box/10/0/param str "_set_thickness|0,5|_set_line_style|solid"

edb_ed menu.db add /menu/box/10/1/label str " Solid thin line "
edb_ed menu.db add /menu/box/10/1/pic str NULL
edb_ed menu.db add /menu/box/10/1/action_class int 0
edb_ed menu.db add /menu/box/10/1/param str "_set_thickness|0,2|_set_line_style|solid"

edb_ed menu.db add /menu/box/10/2/label str " Dashed line "
edb_ed menu.db add /menu/box/10/2/pic str NULL
edb_ed menu.db add /menu/box/10/2/action_class int 0
edb_ed menu.db add /menu/box/10/2/param str "_set_thickness|0,2|set_line_style|dashed2"

edb_ed menu.db add /menu/box/10/3/label str " Dash-dot line "
edb_ed menu.db add /menu/box/10/3/pic str NULL
edb_ed menu.db add /menu/box/10/3/action_class int 0
edb_ed menu.db add /menu/box/10/3/param str "_set_thickness|0,2|_set_line_style|center2"

edb_ed menu.db add /menu/box/10/4/label str "Sep"
edb_ed menu.db add /menu/box/10/4/pic str NULL
edb_ed menu.db add /menu/box/10/4/action_class int 3
edb_ed menu.db add /menu/box/10/4/param str "-"

edb_ed menu.db add /menu/box/10/5/label str " Color "
edb_ed menu.db add /menu/box/10/5/pic str NULL
edb_ed menu.db add /menu/box/10/5/action_class int 2
edb_ed menu.db add /menu/box/10/5/param str "color.menu"

edb_ed menu.db add /menu/box/10/6/label str " Line style "
edb_ed menu.db add /menu/box/10/6/pic str NULL
edb_ed menu.db add /menu/box/10/6/action_class int 2
edb_ed menu.db add /menu/box/10/6/param str "linestyle.menu"

edb_ed menu.db add /menu/box/10/7/label str " Thickness "
edb_ed menu.db add /menu/box/10/7/pic str NULL
edb_ed menu.db add /menu/box/10/7/action_class int 2
edb_ed menu.db add /menu/box/10/7/param str "thickness.menu"

edb_ed menu.db add /menu/box/10/8/label str "Sep"
edb_ed menu.db add /menu/box/10/8/pic str NULL
edb_ed menu.db add /menu/box/10/8/action_class int 3
edb_ed menu.db add /menu/box/10/8/param str "-"

edb_ed menu.db add /menu/box/10/9/label str " Text style "
edb_ed menu.db add /menu/box/10/9/pic str NULL
edb_ed menu.db add /menu/box/10/9/action_class int 2
edb_ed menu.db add /menu/box/10/9/param str "textstyle.menu"

edb_ed menu.db add /menu/box/10/10/label str " Gravity "
edb_ed menu.db add /menu/box/10/10/pic str NULL
edb_ed menu.db add /menu/box/10/10/action_class int 2
edb_ed menu.db add /menu/box/10/10/param str "gravity.menu"

edb_ed menu.db add /menu/box/10/11/label str " Hatch style "
edb_ed menu.db add /menu/box/10/11/pic str NULL
edb_ed menu.db add /menu/box/10/11/action_class int 2
edb_ed menu.db add /menu/box/10/11/param str "hatchstyle.menu"




edb_ed menu.db add /menu/box/11/name str help.menu
edb_ed menu.db add /menu/box/11/count int 3

edb_ed menu.db add /menu/box/11/0/label str " About "
edb_ed menu.db add /menu/box/11/0/pic str NULL
edb_ed menu.db add /menu/box/11/0/action_class int 0
edb_ed menu.db add /menu/box/11/0/param str "logo"

edb_ed menu.db add /menu/box/11/1/label str "Sep"
edb_ed menu.db add /menu/box/11/1/pic str NULL
edb_ed menu.db add /menu/box/11/1/action_class int 3
edb_ed menu.db add /menu/box/11/1/param str "-"

edb_ed menu.db add /menu/box/11/2/label str " Help "
edb_ed menu.db add /menu/box/11/2/pic str NULL
edb_ed menu.db add /menu/box/11/2/action_class int 0
edb_ed menu.db add /menu/box/11/2/param str "help"



edb_ed menu.db add /menu/box/12/name str color.menu
edb_ed menu.db add /menu/box/12/count int 12

edb_ed menu.db add /menu/box/12/0/label str " Black "
edb_ed menu.db add /menu/box/12/0/pic str NULL
edb_ed menu.db add /menu/box/12/0/action_class int 0
edb_ed menu.db add /menu/box/12/0/param str "_set_color|0 0 0 220"

edb_ed menu.db add /menu/box/12/1/label str " Blue "
edb_ed menu.db add /menu/box/12/1/pic str NULL
edb_ed menu.db add /menu/box/12/1/action_class int 0
edb_ed menu.db add /menu/box/12/1/param str "_set_color|0 0 255 220"

edb_ed menu.db add /menu/box/12/2/label str " Green "
edb_ed menu.db add /menu/box/12/2/pic str NULL
edb_ed menu.db add /menu/box/12/2/action_class int 0
edb_ed menu.db add /menu/box/12/2/param str "_set_color|0 255 0 220"

edb_ed menu.db add /menu/box/12/3/label str " Cyan "
edb_ed menu.db add /menu/box/12/3/pic str NULL
edb_ed menu.db add /menu/box/12/3/action_class int 0
edb_ed menu.db add /menu/box/12/3/param str "_set_color|0 255 255 220"

edb_ed menu.db add /menu/box/12/4/label str " Red "
edb_ed menu.db add /menu/box/12/4/pic str NULL
edb_ed menu.db add /menu/box/12/4/action_class int 0
edb_ed menu.db add /menu/box/12/4/param str "_set_color|255 0 0 220"

edb_ed menu.db add /menu/box/12/5/label str " Magenta "
edb_ed menu.db add /menu/box/12/5/pic str NULL
edb_ed menu.db add /menu/box/12/5/action_class int 0
edb_ed menu.db add /menu/box/12/5/param str "_set_color|255 0 255 220"

edb_ed menu.db add /menu/box/12/6/label str " Yellow "
edb_ed menu.db add /menu/box/12/6/pic str NULL
edb_ed menu.db add /menu/box/12/6/action_class int 0
edb_ed menu.db add /menu/box/12/6/param str "_set_color|255 255 0 220"

edb_ed menu.db add /menu/box/12/7/label str " White "
edb_ed menu.db add /menu/box/12/7/pic str NULL
edb_ed menu.db add /menu/box/12/7/action_class int 0
edb_ed menu.db add /menu/box/12/7/param str "_set_color|255 255 255 220"

edb_ed menu.db add /menu/box/12/8/label str "Sep"
edb_ed menu.db add /menu/box/12/8/pic str NULL
edb_ed menu.db add /menu/box/12/8/action_class int 3
edb_ed menu.db add /menu/box/12/8/param str "-"

edb_ed menu.db add /menu/box/12/9/label str " Translucent grey "
edb_ed menu.db add /menu/box/12/9/pic str NULL
edb_ed menu.db add /menu/box/12/9/action_class int 0
edb_ed menu.db add /menu/box/12/9/param str "_set_color|100 100 100 100"

edb_ed menu.db add /menu/box/12/10/label str "Sep "
edb_ed menu.db add /menu/box/12/10/pic str NULL
edb_ed menu.db add /menu/box/12/10/action_class int 3
edb_ed menu.db add /menu/box/12/10/param str "-"

edb_ed menu.db add /menu/box/12/11/label str " Another color "
edb_ed menu.db add /menu/box/12/11/pic str NULL
edb_ed menu.db add /menu/box/12/11/action_class int 0
edb_ed menu.db add /menu/box/12/11/param str "set_color"







edb_ed menu.db add /menu/box/13/name str gravity.menu
edb_ed menu.db add /menu/box/13/count int 11

edb_ed menu.db add /menu/box/13/0/label str " Middle - Center "
edb_ed menu.db add /menu/box/13/0/pic str NULL
edb_ed menu.db add /menu/box/13/0/action_class int 0
edb_ed menu.db add /menu/box/13/0/param str "_set_gravity|MC"

edb_ed menu.db add /menu/box/13/1/label str " Middle - Left "
edb_ed menu.db add /menu/box/13/1/pic str NULL
edb_ed menu.db add /menu/box/13/1/action_class int 0
edb_ed menu.db add /menu/box/13/1/param str "_set_gravity|ML"

edb_ed menu.db add /menu/box/13/2/label str " Middle - Right "
edb_ed menu.db add /menu/box/13/2/pic str NULL
edb_ed menu.db add /menu/box/13/2/action_class int 0
edb_ed menu.db add /menu/box/13/2/param str "_set_gravity|MR"

edb_ed menu.db add /menu/box/13/3/label str "Sep"
edb_ed menu.db add /menu/box/13/3/pic str NULL
edb_ed menu.db add /menu/box/13/3/action_class int 3
edb_ed menu.db add /menu/box/13/3/param str "-"


edb_ed menu.db add /menu/box/13/4/label str " Top - Center "
edb_ed menu.db add /menu/box/13/4/pic str NULL
edb_ed menu.db add /menu/box/13/4/action_class int 0
edb_ed menu.db add /menu/box/13/4/param str "_set_gravity|TC"

edb_ed menu.db add /menu/box/13/5/label str " Top - Left "
edb_ed menu.db add /menu/box/13/5/pic str NULL
edb_ed menu.db add /menu/box/13/5/action_class int 0
edb_ed menu.db add /menu/box/13/5/param str "_set_gravity|TL"

edb_ed menu.db add /menu/box/13/6/label str " Top - Right "
edb_ed menu.db add /menu/box/13/6/pic str NULL
edb_ed menu.db add /menu/box/13/6/action_class int 0
edb_ed menu.db add /menu/box/13/6/param str "_set_gravity|TR"

edb_ed menu.db add /menu/box/13/7/label str "Sep"
edb_ed menu.db add /menu/box/13/7/pic str NULL
edb_ed menu.db add /menu/box/13/7/action_class int 3
edb_ed menu.db add /menu/box/13/7/param str "-"

edb_ed menu.db add /menu/box/13/8/label str " Bottom - Center "
edb_ed menu.db add /menu/box/13/8/pic str NULL
edb_ed menu.db add /menu/box/13/8/action_class int 0
edb_ed menu.db add /menu/box/13/8/param str "_set_gravity|BC"

edb_ed menu.db add /menu/box/13/9/label str " Bottom - Left "
edb_ed menu.db add /menu/box/13/9/pic str NULL
edb_ed menu.db add /menu/box/13/9/action_class int 0
edb_ed menu.db add /menu/box/13/9/param str "_set_gravity|BL"

edb_ed menu.db add /menu/box/13/10/label str " Bottom - Right "
edb_ed menu.db add /menu/box/13/10/pic str NULL
edb_ed menu.db add /menu/box/13/10/action_class int 0
edb_ed menu.db add /menu/box/13/10/param str "_set_gravity|BR"



edb_ed menu.db add /menu/box/14/name str linestyle.menu
edb_ed menu.db add /menu/box/14/count int 4

edb_ed menu.db add /menu/box/14/0/label str " Solid "
edb_ed menu.db add /menu/box/14/0/pic str NULL
edb_ed menu.db add /menu/box/14/0/action_class int 0
edb_ed menu.db add /menu/box/14/0/param str "_set_line_style|solid"

edb_ed menu.db add /menu/box/14/1/label str " Dashed "
edb_ed menu.db add /menu/box/14/1/pic str NULL
edb_ed menu.db add /menu/box/14/1/action_class int 0
edb_ed menu.db add /menu/box/14/1/param str "_set_line_style|dashed"

edb_ed menu.db add /menu/box/14/2/label str " Dash-doted "
edb_ed menu.db add /menu/box/14/2/pic str NULL
edb_ed menu.db add /menu/box/14/2/action_class int 0
edb_ed menu.db add /menu/box/14/2/param str "_set_line_style|center"

edb_ed menu.db add /menu/box/14/3/label str " Tooth "
edb_ed menu.db add /menu/box/14/3/pic str NULL
edb_ed menu.db add /menu/box/14/3/action_class int 0
edb_ed menu.db add /menu/box/14/3/param str "_set_line_style|tooth"



edb_ed menu.db add /menu/box/15/name str thickness.menu
edb_ed menu.db add /menu/box/15/count int 11

edb_ed menu.db add /menu/box/15/0/label str " 0,5 "
edb_ed menu.db add /menu/box/15/0/pic str NULL
edb_ed menu.db add /menu/box/15/0/action_class int 0
edb_ed menu.db add /menu/box/15/0/param str "_set_thickness|0,5"

edb_ed menu.db add /menu/box/15/1/label str " 0,2 "
edb_ed menu.db add /menu/box/15/1/pic str NULL
edb_ed menu.db add /menu/box/15/1/action_class int 0
edb_ed menu.db add /menu/box/15/1/param str "_set_thickness|0,2"

edb_ed menu.db add /menu/box/15/2/label str "Sep"
edb_ed menu.db add /menu/box/15/2/pic str NULL
edb_ed menu.db add /menu/box/15/2/action_class int 3
edb_ed menu.db add /menu/box/15/2/param str "-"

edb_ed menu.db add /menu/box/15/3/label str " 1,0 "
edb_ed menu.db add /menu/box/15/3/pic str NULL
edb_ed menu.db add /menu/box/15/3/action_class int 0
edb_ed menu.db add /menu/box/15/3/param str "_set_thickness|1,0"

edb_ed menu.db add /menu/box/15/4/label str " 0,7 "
edb_ed menu.db add /menu/box/15/4/pic str NULL
edb_ed menu.db add /menu/box/15/4/action_class int 0
edb_ed menu.db add /menu/box/15/4/param str "_set_thickness|0,7"

edb_ed menu.db add /menu/box/15/4/label str " 0,5 "
edb_ed menu.db add /menu/box/15/4/pic str NULL
edb_ed menu.db add /menu/box/15/4/action_class int 0
edb_ed menu.db add /menu/box/15/4/param str "_set_thickness|0,5"

edb_ed menu.db add /menu/box/15/5/label str " 0,3 "
edb_ed menu.db add /menu/box/15/5/pic str NULL
edb_ed menu.db add /menu/box/15/5/action_class int 0
edb_ed menu.db add /menu/box/15/5/param str "_set_thickness|0,3"

edb_ed menu.db add /menu/box/15/6/label str " 0,25 "
edb_ed menu.db add /menu/box/15/6/pic str NULL
edb_ed menu.db add /menu/box/15/6/action_class int 0
edb_ed menu.db add /menu/box/15/6/param str "_set_thickness|0,25"

edb_ed menu.db add /menu/box/15/7/label str " 0,2 "
edb_ed menu.db add /menu/box/15/7/pic str NULL
edb_ed menu.db add /menu/box/15/7/action_class int 0
edb_ed menu.db add /menu/box/15/7/param str "_set_thickness|0,2"

edb_ed menu.db add /menu/box/15/8/label str " 0,15 "
edb_ed menu.db add /menu/box/15/8/pic str NULL
edb_ed menu.db add /menu/box/15/8/action_class int 0
edb_ed menu.db add /menu/box/15/8/param str "_set_thickness|0,15"

edb_ed menu.db add /menu/box/15/9/label str " 0,1 "
edb_ed menu.db add /menu/box/15/9/pic str NULL
edb_ed menu.db add /menu/box/15/9/action_class int 0
edb_ed menu.db add /menu/box/15/9/param str "_set_thickness|0,1"

edb_ed menu.db add /menu/box/15/10/label str " 0,01 "
edb_ed menu.db add /menu/box/15/10/pic str NULL
edb_ed menu.db add /menu/box/15/10/action_class int 0
edb_ed menu.db add /menu/box/15/10/param str "_set_thickness|0,01"










edb_ed menu.db add /menu/box/16/name str textstyle.menu
edb_ed menu.db add /menu/box/16/count int 2

edb_ed menu.db add /menu/box/16/0/label str " GOST "
edb_ed menu.db add /menu/box/16/0/pic str NULL
edb_ed menu.db add /menu/box/16/0/action_class int 0
edb_ed menu.db add /menu/box/16/0/param str "_set_text_style|gost"

edb_ed menu.db add /menu/box/16/1/label str " Times "
edb_ed menu.db add /menu/box/16/1/pic str NULL
edb_ed menu.db add /menu/box/16/1/action_class int 0
edb_ed menu.db add /menu/box/16/1/param str "_set_text_style|times"





edb_ed menu.db add /menu/box/17/name str hatchstyle.menu
edb_ed menu.db add /menu/box/17/count int 2

edb_ed menu.db add /menu/box/17/0/label str " Metal "
edb_ed menu.db add /menu/box/17/0/pic str NULL
edb_ed menu.db add /menu/box/17/0/action_class int 0
edb_ed menu.db add /menu/box/17/0/param str "_set_hatch_style|metal"

edb_ed menu.db add /menu/box/17/1/label str " Glass "
edb_ed menu.db add /menu/box/17/1/pic str NULL
edb_ed menu.db add /menu/box/17/1/action_class int 0
edb_ed menu.db add /menu/box/17/1/param str "_set_text_style|glass"















