# Copyright (c) 2008 Simon Busch
#
# This file is part of python-elementary.
#
# python-elementary is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# python-elementary is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with python-elementary.  If not, see <http://www.gnu.org/licenses/>.
#

ELM_CURSOR_X                   = "x"
ELM_CURSOR_ARROW               = "arrow"
ELM_CURSOR_BASED_ARROW_DOWN    = "based_arrow_down"
ELM_CURSOR_BASED_ARROW_UP      = "based_arrow_up"
ELM_CURSOR_BOAT                = "boat"
ELM_CURSOR_BOGOSITY            = "bogosity"
ELM_CURSOR_BOTTOM_LEFT_CORNER  = "bottom_left_corner"
ELM_CURSOR_BOTTOM_RIGHT_CORNER = "bottom_right_corner"
ELM_CURSOR_BOTTOM_SIDE         = "bottom_side"
ELM_CURSOR_BOTTOM_TEE          = "bottom_tee"
ELM_CURSOR_BOX_SPIRAL          = "box_spiral"
ELM_CURSOR_CENTER_PTR          = "center_ptr"
ELM_CURSOR_CIRCLE              = "circle"
ELM_CURSOR_CLOCK               = "clock"
ELM_CURSOR_COFFEE_MUG          = "coffee_mug"
ELM_CURSOR_CROSS               = "cross"
ELM_CURSOR_CROSS_REVERSE       = "cross_reverse"
ELM_CURSOR_CROSSHAIR           = "crosshair"
ELM_CURSOR_DIAMOND_CROSS       = "diamond_cross"
ELM_CURSOR_DOT                 = "dot"
ELM_CURSOR_DOT_BOX_MASK        = "dot_box_mask"
ELM_CURSOR_DOUBLE_ARROW        = "double_arrow"
ELM_CURSOR_DRAFT_LARGE         = "draft_large"
ELM_CURSOR_DRAFT_SMALL         = "draft_small"
ELM_CURSOR_DRAPED_BOX          = "draped_box"
ELM_CURSOR_EXCHANGE            = "exchange"
ELM_CURSOR_FLEUR               = "fleur"
ELM_CURSOR_GOBBLER             = "gobbler"
ELM_CURSOR_GUMBY               = "gumby"
ELM_CURSOR_HAND1               = "hand1"
ELM_CURSOR_HAND2               = "hand2"
ELM_CURSOR_HEART               = "heart"
ELM_CURSOR_ICON                = "icon"
ELM_CURSOR_IRON_CROSS          = "iron_cross"
ELM_CURSOR_LEFT_PTR            = "left_ptr"
ELM_CURSOR_LEFT_SIDE           = "left_side"
ELM_CURSOR_LEFT_TEE            = "left_tee"
ELM_CURSOR_LEFTBUTTON          = "leftbutton"
ELM_CURSOR_LL_ANGLE            = "ll_angle"
ELM_CURSOR_LR_ANGLE            = "lr_angle"
ELM_CURSOR_MAN                 = "man"
ELM_CURSOR_MIDDLEBUTTON        = "middlebutton"
ELM_CURSOR_MOUSE               = "mouse"
ELM_CURSOR_PENCIL              = "pencil"
ELM_CURSOR_PIRATE              = "pirate"
ELM_CURSOR_PLUS                = "plus"
ELM_CURSOR_QUESTION_ARROW      = "question_arrow"
ELM_CURSOR_RIGHT_PTR           = "right_ptr"
ELM_CURSOR_RIGHT_SIDE          = "right_side"
ELM_CURSOR_RIGHT_TEE           = "right_tee"
ELM_CURSOR_RIGHTBUTTON         = "rightbutton"
ELM_CURSOR_RTL_LOGO            = "rtl_logo"
ELM_CURSOR_SAILBOAT            = "sailboat"
ELM_CURSOR_SB_DOWN_ARROW       = "sb_down_arrow"
ELM_CURSOR_SB_H_DOUBLE_ARROW   = "sb_h_double_arrow"
ELM_CURSOR_SB_LEFT_ARROW       = "sb_left_arrow"
ELM_CURSOR_SB_RIGHT_ARROW      = "sb_right_arrow"
ELM_CURSOR_SB_UP_ARROW         = "sb_up_arrow"
ELM_CURSOR_SB_V_DOUBLE_ARROW   = "sb_v_double_arrow"
ELM_CURSOR_SHUTTLE             = "shuttle"
ELM_CURSOR_SIZING              = "sizing"
ELM_CURSOR_SPIDER              = "spider"
ELM_CURSOR_SPRAYCAN            = "spraycan"
ELM_CURSOR_STAR                = "star"
ELM_CURSOR_TARGET              = "target"
ELM_CURSOR_TCROSS              = "tcross"
ELM_CURSOR_TOP_LEFT_ARROW      = "top_left_arrow"
ELM_CURSOR_TOP_LEFT_CORNER     = "top_left_corner"
ELM_CURSOR_TOP_RIGHT_CORNER    = "top_right_corner"
ELM_CURSOR_TOP_SIDE            = "top_side"
ELM_CURSOR_TOP_TEE             = "top_tee"
ELM_CURSOR_TREK                = "trek"
ELM_CURSOR_UL_ANGLE            = "ul_angle"
ELM_CURSOR_UMBRELLA            = "umbrella"
ELM_CURSOR_UR_ANGLE            = "ur_angle"
ELM_CURSOR_WATCH               = "watch"
ELM_CURSOR_XTERM               = "xterm"
