Summary: GUI Tool for Editing Enlightenment 0.16.x Menus
Name: e16menuedit
Version: 0.1.0
Release: 1%{?_vendorsuffix:.%{_vendorsuffix}}
Copyright: BSD-like
Group: User Interface/Desktops
Source: %{name}-%{version}.tar.gz
Packager: %{?_packager:%{_packager}}%{!?_packager:Michael Jennings <mej@eterm.org>}
Vendor: %{?_vendorinfo:%{_vendorinfo}}%{!?_vendorinfo:Enlightenment (http://www.enlightenment/org/)}
Distribution: %{?_distribution:%{_distribution}}%{!?_distribution:any}
BuildRequires: /usr/bin/gtk-config
#BuildSuggests: gtk-devel
Prefix: %{_prefix}
BuildRoot: /var/tmp/%{name}-%{version}-%{release}-root

%description
e16menuedit provides a graphical interface for managing user menus in
Enlightenment 0.16.x.

%prep
%setup -q 

%build
CFLAGS="%{?cflags:%{cflags}}%{!?cflags:$RPM_OPT_FLAGS}"
CXXFLAGS="%{?cxxflags:%{cxxflags}}%{!?cflags:$RPM_OPT_FLAGS}"
export CFLAGS CXXFLAGS

%configure --prefix=%{_prefix} %{?acflags}
%{__make} %{?_smp_mflags} %{?mflags}

%install
%{__make} install DESTDIR=$RPM_BUILD_ROOT %{?mflags_install}

%clean
test "x$RPM_BUILD_ROOT" != "x" && rm -rf $RPM_BUILD_ROOT

%files
%defattr(-, root, root)
%doc README COPYING AUTHORS ChangeLog 
%{_bindir}/%{name}

%changelog
* Tue Jul 20 2004 Mezzanine <mezzanine@kainx.org>
- Specfile auto-generated by Mezzanine

