#!/bin/sh

pfx=$1;
datestr=`date +%Y%m%d-%H%M-%Z`;

if [ -z $1 ]; then
    echo -e "build_cam_dirs.sh 0.1"
    echo -e "usage:\n  build_cam_dirs.sh <outputDirectory>\ndescription:"
    echo -e "  a shell script which generates output directories based on cam bookmarks\n  keys and adds the appropriate configuration line to ~/.fehrc."
else
    cp ~/.fehrc ~/.fehrc.bak;
    echo -e "\n# Cam Bookmark Themes." >> ~/.fehrc
    echo -e "# Generated by build_cam_dirs.sh on $datestr." >>~/.fehrc
    
    for i in `cat ~/.cam_bookmarks|sed 's/\(.*\)=.*/\1/'`; do
        echo $i"cam --output-dir $pfx/$i" >> ~/.fehrc
        mkdir $pfx/$i;
    done
fi
