#!/bin/sh

s=$1
test -z "$s" && s=$0

case "$s" in
*gnome|GNOME)
	WINDOW_MANAGER=e16
	export WINDOW_MANAGER
	exec gnome-session
	;;
*kde|KDE)
	KDEWM=e16
	export KDEWM
	exec startkde
	;;
*)
	exec e16
	;;
esac
