/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget *
create_main_win(void)
{
   GtkWidget *main_win;
   GtkWidget *vbox1;
   GtkWidget *menubar1;
   GtkWidget *_file;
   GtkWidget *_file_menu;
   GtkAccelGroup *_file_menu_accels;
   GtkWidget *new1;
   GtkWidget *open;
   GtkWidget *separator1;
   GtkWidget *recent_bg_mi;
   GtkWidget *separator2;
   GtkWidget *save;
   GtkWidget *save_as;
   GtkWidget *separator3;
   GtkWidget *quit;
   GtkWidget *notebook1;
   GtkWidget *label30;
   GtkWidget *label1;
   GtkWidget *vbox2;
   GtkWidget *vbox3;
   GtkWidget *hbox1;
   GtkWidget *label3;
   GtkObject *layer_num_adj;
   GtkWidget *layer_num;
   GtkWidget *button3;
   GtkWidget *button4;
   GtkWidget *hbox2;
   GtkWidget *button1;
   GtkWidget *button2;
   GtkWidget *frame11;
   GtkWidget *vbox10;
   GtkWidget *hbox14;
   GSList *hbox14_group = NULL;
   GtkWidget *type_image;
   GtkWidget *type_color;
   GtkWidget *type_gradient;
   GtkWidget *notebook2;
   GtkWidget *image_file_frame;
   GtkWidget *vbox5;
   GtkWidget *hbox5;
   GtkWidget *image_file;
   GtkWidget *button5;
   GtkWidget *hbox6;
   GtkWidget *inline_image;
   GtkWidget *label4;
   GtkWidget *frame4;
   GtkWidget *vbox6;
   GtkWidget *combo1;
   GList *combo1_items = NULL;
   GtkWidget *color_class_combo;
   GtkWidget *label5;
   GtkWidget *layer_scroll_follow;
   GtkWidget *vbox12;
   GtkWidget *hbox7;
   GtkWidget *label10;
   GtkObject *scroll_x_adj;
   GtkWidget *scroll_x;
   GtkWidget *label11;
   GtkObject *scroll_y_adj;
   GtkWidget *scroll_y;
   GtkWidget *label6;
   GtkWidget *frame6;
   GtkWidget *vbox7;
   GtkWidget *hbox8;
   GtkWidget *label12;
   GtkObject *pos_x_adj;
   GtkWidget *pos_x;
   GtkWidget *label13;
   GtkObject *pos_y_adj;
   GtkWidget *pos_y;
   GtkWidget *frame2;
   GtkWidget *hbox9;
   GtkWidget *label14;
   GtkObject *abs_x_adj;
   GtkWidget *abs_x;
   GtkWidget *label15;
   GtkObject *abs_y_adj;
   GtkWidget *abs_y;
   GtkWidget *label7;
   GtkWidget *frame7;
   GtkWidget *vbox8;
   GtkWidget *hbox10;
   GtkWidget *label16;
   GtkObject *size_w_adj;
   GtkWidget *size_w;
   GtkWidget *label17;
   GtkObject *size_h_adj;
   GtkWidget *size_h;
   GtkWidget *table1;
   GtkWidget *size_abs_w;
   GtkWidget *size_abs_h;
   GtkWidget *size_orig_w;
   GtkWidget *size_orig_h;
   GtkWidget *label8;
   GtkWidget *layer_fill_frame;
   GtkWidget *vbox9;
   GtkWidget *hbox12;
   GtkWidget *label18;
   GtkObject *fill_w_adj;
   GtkWidget *fill_w;
   GtkWidget *label19;
   GtkObject *fill_h_adj;
   GtkWidget *fill_h;
   GtkWidget *hbox13;
   GtkWidget *fill_orig_w;
   GtkWidget *fill_orig_h;
   GtkWidget *label9;
   GtkWidget *layer_color_frame;
   GtkWidget *vbox11;
   GtkWidget *color_box;
   GtkWidget *label20;
   GtkWidget *gradient_frame;
   GtkWidget *table2;
   GtkWidget *label22;
   GtkWidget *label23;
   GtkWidget *label24;
   GtkWidget *gradient_one_color_box;
   GtkWidget *gradient_two_color_box;
   GtkObject *gradient_angle_adj;
   GtkWidget *gradient_angle;
   GtkWidget *label21;
   GtkWidget *whocares;
   GtkWidget *vbox1492;
   GtkWidget *scale_preview;
   GtkWidget *screen_size_frame;
   GtkWidget *vbox14;
   GtkWidget *table3;
   GSList *export_size_group_group = NULL;
   GtkWidget *radiobutton1;
   GtkWidget *radiobutton2;
   GtkWidget *radiobutton3;
   GtkWidget *radiobutton4;
   GtkWidget *radiobutton5;
   GtkWidget *radiobutton6;
   GtkWidget *table5;
   GtkObject *export_screen_h_adj;
   GtkWidget *export_screen_h;
   GtkWidget *label26;
   GtkObject *export_screen_w_adj;
   GtkWidget *export_screen_w;
   GtkWidget *label25;
   GtkWidget *table4;
   GtkObject *export_xinerama_v_adj;
   GtkWidget *export_xinerama_v;
   GtkObject *export_xinerama_h_adj;
   GtkWidget *export_xinerama_h;
   GtkWidget *label28;
   GtkWidget *label27;
   GtkWidget *hbuttonbox1;
   GtkWidget *export_next_button;
   GtkWidget *label29;
   GtkAccelGroup *accel_group;

   accel_group = gtk_accel_group_new();

   main_win = gtk_window_new(GTK_WINDOW_TOPLEVEL);
   gtk_widget_set_name(main_win, "main_win");
   gtk_object_set_data(GTK_OBJECT(main_win), "main_win", main_win);
   gtk_widget_set_uposition(main_win, 0, 40);
   gtk_widget_set_usize(main_win, 280, -2);
   gtk_window_set_title(GTK_WINDOW(main_win), _("Ebony Controls"));
   gtk_window_set_default_size(GTK_WINDOW(main_win), 300, 300);
   gtk_window_set_policy(GTK_WINDOW(main_win), TRUE, TRUE, FALSE);
   gtk_window_set_wmclass(GTK_WINDOW(main_win), "Ebony", "Main");

   vbox1 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox1, "vbox1");
   gtk_widget_ref(vbox1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox1);
   gtk_container_add(GTK_CONTAINER(main_win), vbox1);

   menubar1 = gtk_menu_bar_new();
   gtk_widget_set_name(menubar1, "menubar1");
   gtk_widget_ref(menubar1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(menubar1);
   gtk_box_pack_start(GTK_BOX(vbox1), menubar1, FALSE, FALSE, 0);

   _file = gtk_menu_item_new_with_label(_("File"));
   gtk_widget_set_name(_file, "_file");
   gtk_widget_ref(_file);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "_file", _file,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(_file);
   gtk_container_add(GTK_CONTAINER(menubar1), _file);

   _file_menu = gtk_menu_new();
   gtk_widget_set_name(_file_menu, "_file_menu");
   gtk_widget_ref(_file_menu);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "_file_menu", _file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_menu_item_set_submenu(GTK_MENU_ITEM(_file), _file_menu);
   _file_menu_accels =
      gtk_menu_ensure_uline_accel_group(GTK_MENU(_file_menu));

   new1 = gtk_menu_item_new_with_label(_("New"));
   gtk_widget_set_name(new1, "new1");
   gtk_widget_ref(new1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "new1", new1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(new1);
   gtk_container_add(GTK_CONTAINER(_file_menu), new1);
   gtk_widget_add_accelerator(new1, "activate", accel_group, GDK_n,
                              GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

   open = gtk_menu_item_new_with_label(_("Open"));
   gtk_widget_set_name(open, "open");
   gtk_widget_ref(open);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "open", open,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(open);
   gtk_container_add(GTK_CONTAINER(_file_menu), open);
   gtk_widget_add_accelerator(open, "activate", accel_group, GDK_o,
                              GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

   separator1 = gtk_menu_item_new();
   gtk_widget_set_name(separator1, "separator1");
   gtk_widget_ref(separator1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "separator1", separator1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(separator1);
   gtk_container_add(GTK_CONTAINER(_file_menu), separator1);
   gtk_widget_set_sensitive(separator1, FALSE);

   recent_bg_mi = gtk_menu_item_new_with_label(_("Recent"));
   gtk_widget_set_name(recent_bg_mi, "recent_bg_mi");
   gtk_widget_ref(recent_bg_mi);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "recent_bg_mi",
                            recent_bg_mi,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(recent_bg_mi);
   gtk_container_add(GTK_CONTAINER(_file_menu), recent_bg_mi);

   separator2 = gtk_menu_item_new();
   gtk_widget_set_name(separator2, "separator2");
   gtk_widget_ref(separator2);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "separator2", separator2,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(separator2);
   gtk_container_add(GTK_CONTAINER(_file_menu), separator2);
   gtk_widget_set_sensitive(separator2, FALSE);

   save = gtk_menu_item_new_with_label(_("Save"));
   gtk_widget_set_name(save, "save");
   gtk_widget_ref(save);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "save", save,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(save);
   gtk_container_add(GTK_CONTAINER(_file_menu), save);
   gtk_widget_add_accelerator(save, "activate", accel_group, GDK_s,
                              GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

   save_as = gtk_menu_item_new_with_label(_("Save As"));
   gtk_widget_set_name(save_as, "save_as");
   gtk_widget_ref(save_as);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "save_as", save_as,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(save_as);
   gtk_container_add(GTK_CONTAINER(_file_menu), save_as);

   separator3 = gtk_menu_item_new();
   gtk_widget_set_name(separator3, "separator3");
   gtk_widget_ref(separator3);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "separator3", separator3,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(separator3);
   gtk_container_add(GTK_CONTAINER(_file_menu), separator3);
   gtk_widget_set_sensitive(separator3, FALSE);

   quit = gtk_menu_item_new_with_label(_("Quit"));
   gtk_widget_set_name(quit, "quit");
   gtk_widget_ref(quit);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "quit", quit,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(quit);
   gtk_container_add(GTK_CONTAINER(_file_menu), quit);
   gtk_widget_add_accelerator(quit, "activate", accel_group, GDK_q,
                              GDK_CONTROL_MASK, GTK_ACCEL_VISIBLE);

   notebook1 = gtk_notebook_new();
   gtk_widget_set_name(notebook1, "notebook1");
   gtk_widget_ref(notebook1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(notebook1);
   gtk_box_pack_start(GTK_BOX(vbox1), notebook1, TRUE, TRUE, 0);

   label30 = gtk_label_new(_("This tab is intentionally left blank."));
   gtk_widget_set_name(label30, "label30");
   gtk_widget_ref(label30);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label30);
   gtk_container_add(GTK_CONTAINER(notebook1), label30);

   label1 = gtk_label_new(_("Settings"));
   gtk_widget_set_name(label1, "label1");
   gtk_widget_ref(label1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label1);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook1),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook1), 0),
                              label1);

   vbox2 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox2, "vbox2");
   gtk_widget_ref(vbox2);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox2);
   gtk_container_add(GTK_CONTAINER(notebook1), vbox2);
   gtk_container_set_border_width(GTK_CONTAINER(vbox2), 3);

   vbox3 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox3, "vbox3");
   gtk_widget_ref(vbox3);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox3);
   gtk_box_pack_start(GTK_BOX(vbox2), vbox3, FALSE, TRUE, 0);

   hbox1 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox1, "hbox1");
   gtk_widget_ref(hbox1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox1);
   gtk_box_pack_start(GTK_BOX(vbox3), hbox1, FALSE, FALSE, 0);

   label3 = gtk_label_new(_("Layer Number"));
   gtk_widget_set_name(label3, "label3");
   gtk_widget_ref(label3);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label3);
   gtk_box_pack_start(GTK_BOX(hbox1), label3, TRUE, TRUE, 0);

   layer_num_adj = gtk_adjustment_new(0, 0, 100, 1, 10, 10);
   layer_num = gtk_spin_button_new(GTK_ADJUSTMENT(layer_num_adj), 1, 0);
   gtk_widget_set_name(layer_num, "layer_num");
   gtk_widget_ref(layer_num);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "layer_num", layer_num,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(layer_num);
   gtk_box_pack_start(GTK_BOX(hbox1), layer_num, FALSE, TRUE, 0);

   button3 = gtk_button_new_with_label(_("Add"));
   gtk_widget_set_name(button3, "button3");
   gtk_widget_ref(button3);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(button3);
   gtk_box_pack_start(GTK_BOX(hbox1), button3, TRUE, TRUE, 0);

   button4 = gtk_button_new_with_label(_("Delete"));
   gtk_widget_set_name(button4, "button4");
   gtk_widget_ref(button4);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(button4);
   gtk_box_pack_start(GTK_BOX(hbox1), button4, TRUE, TRUE, 0);

   hbox2 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox2, "hbox2");
   gtk_widget_ref(hbox2);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox2);
   gtk_box_pack_start(GTK_BOX(vbox3), hbox2, FALSE, TRUE, 0);

   button1 = gtk_button_new_with_label(_("Move Layer Up"));
   gtk_widget_set_name(button1, "button1");
   gtk_widget_ref(button1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(button1);
   gtk_box_pack_start(GTK_BOX(hbox2), button1, TRUE, TRUE, 0);

   button2 = gtk_button_new_with_label(_("Move Layer Down"));
   gtk_widget_set_name(button2, "button2");
   gtk_widget_ref(button2);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(button2);
   gtk_box_pack_start(GTK_BOX(hbox2), button2, TRUE, TRUE, 0);

   frame11 = gtk_frame_new(_("Layer Settings"));
   gtk_widget_set_name(frame11, "frame11");
   gtk_widget_ref(frame11);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "frame11", frame11,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(frame11);
   gtk_box_pack_start(GTK_BOX(vbox2), frame11, FALSE, TRUE, 2);
   gtk_container_set_border_width(GTK_CONTAINER(frame11), 4);

   vbox10 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox10, "vbox10");
   gtk_widget_ref(vbox10);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox10", vbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox10);
   gtk_container_add(GTK_CONTAINER(frame11), vbox10);

   hbox14 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox14, "hbox14");
   gtk_widget_ref(hbox14);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox14", hbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox14);
   gtk_box_pack_start(GTK_BOX(vbox10), hbox14, TRUE, TRUE, 0);

   type_image = gtk_radio_button_new_with_label(hbox14_group, _("Image"));
   hbox14_group = gtk_radio_button_group(GTK_RADIO_BUTTON(type_image));
   gtk_widget_set_name(type_image, "type_image");
   gtk_widget_ref(type_image);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "type_image", type_image,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(type_image);
   gtk_box_pack_start(GTK_BOX(hbox14), type_image, TRUE, FALSE, 0);

   type_color = gtk_radio_button_new_with_label(hbox14_group, _("Color"));
   hbox14_group = gtk_radio_button_group(GTK_RADIO_BUTTON(type_color));
   gtk_widget_set_name(type_color, "type_color");
   gtk_widget_ref(type_color);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "type_color", type_color,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(type_color);
   gtk_box_pack_start(GTK_BOX(hbox14), type_color, TRUE, FALSE, 0);

   type_gradient =
      gtk_radio_button_new_with_label(hbox14_group, _("Gradient"));
   hbox14_group = gtk_radio_button_group(GTK_RADIO_BUTTON(type_gradient));
   gtk_widget_set_name(type_gradient, "type_gradient");
   gtk_widget_ref(type_gradient);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "type_gradient",
                            type_gradient,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(type_gradient);
   gtk_box_pack_start(GTK_BOX(hbox14), type_gradient, TRUE, FALSE, 0);

   notebook2 = gtk_notebook_new();
   gtk_widget_set_name(notebook2, "notebook2");
   gtk_widget_ref(notebook2);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "notebook2", notebook2,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(notebook2);
   gtk_box_pack_start(GTK_BOX(vbox10), notebook2, TRUE, TRUE, 0);

   image_file_frame = gtk_frame_new(NULL);
   gtk_widget_set_name(image_file_frame, "image_file_frame");
   gtk_widget_ref(image_file_frame);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "image_file_frame",
                            image_file_frame,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(image_file_frame);
   gtk_container_add(GTK_CONTAINER(notebook2), image_file_frame);

   vbox5 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox5, "vbox5");
   gtk_widget_ref(vbox5);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox5);
   gtk_container_add(GTK_CONTAINER(image_file_frame), vbox5);

   hbox5 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox5, "hbox5");
   gtk_widget_ref(hbox5);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox5);
   gtk_box_pack_start(GTK_BOX(vbox5), hbox5, FALSE, TRUE, 0);

   image_file = gtk_entry_new_with_max_length(1024);
   gtk_widget_set_name(image_file, "image_file");
   gtk_widget_ref(image_file);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "image_file", image_file,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(image_file);
   gtk_box_pack_start(GTK_BOX(hbox5), image_file, TRUE, TRUE, 0);

   button5 = gtk_button_new_with_label(_("Select"));
   gtk_widget_set_name(button5, "button5");
   gtk_widget_ref(button5);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(button5);
   gtk_box_pack_start(GTK_BOX(hbox5), button5, FALSE, FALSE, 0);

   hbox6 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox6, "hbox6");
   gtk_widget_ref(hbox6);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox6);
   gtk_box_pack_start(GTK_BOX(vbox5), hbox6, FALSE, TRUE, 0);

   inline_image = gtk_check_button_new_with_label(_("Inline Image"));
   gtk_widget_set_name(inline_image, "inline_image");
   gtk_widget_ref(inline_image);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "inline_image",
                            inline_image,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(inline_image);
   gtk_box_pack_start(GTK_BOX(hbox6), inline_image, FALSE, FALSE, 0);

   label4 = gtk_label_new(_("Image"));
   gtk_widget_set_name(label4, "label4");
   gtk_widget_ref(label4);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label4);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook2),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook2), 0),
                              label4);

   frame4 = gtk_frame_new(NULL);
   gtk_widget_set_name(frame4, "frame4");
   gtk_widget_ref(frame4);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(frame4);
   gtk_container_add(GTK_CONTAINER(notebook2), frame4);

   vbox6 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox6, "vbox6");
   gtk_widget_ref(vbox6);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox6);
   gtk_container_add(GTK_CONTAINER(frame4), vbox6);

   combo1 = gtk_combo_new();
   gtk_widget_set_name(combo1, "combo1");
   gtk_widget_ref(combo1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "combo1", combo1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(combo1);
   gtk_box_pack_start(GTK_BOX(vbox6), combo1, FALSE, FALSE, 0);
   combo1_items = g_list_append(combo1_items, (gpointer) _("Base_Layer"));
   combo1_items =
      g_list_append(combo1_items, (gpointer) _("Tintable_Gradient"));
   gtk_combo_set_popdown_strings(GTK_COMBO(combo1), combo1_items);
   g_list_free(combo1_items);

   color_class_combo = GTK_COMBO(combo1)->entry;
   gtk_widget_set_name(color_class_combo, "color_class_combo");
   gtk_widget_ref(color_class_combo);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "color_class_combo",
                            color_class_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(color_class_combo);
   gtk_entry_set_text(GTK_ENTRY(color_class_combo), _("Base_Layer"));

   label5 = gtk_label_new(_("Color Class"));
   gtk_widget_set_name(label5, "label5");
   gtk_widget_ref(label5);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label5);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook2),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook2), 1),
                              label5);

   layer_scroll_follow = gtk_frame_new(NULL);
   gtk_widget_set_name(layer_scroll_follow, "layer_scroll_follow");
   gtk_widget_ref(layer_scroll_follow);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "layer_scroll_follow",
                            layer_scroll_follow,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(layer_scroll_follow);
   gtk_container_add(GTK_CONTAINER(notebook2), layer_scroll_follow);

   vbox12 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox12, "vbox12");
   gtk_widget_ref(vbox12);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox12", vbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox12);
   gtk_container_add(GTK_CONTAINER(layer_scroll_follow), vbox12);

   hbox7 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox7, "hbox7");
   gtk_widget_ref(hbox7);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox7);
   gtk_box_pack_start(GTK_BOX(vbox12), hbox7, FALSE, TRUE, 0);
   gtk_container_set_border_width(GTK_CONTAINER(hbox7), 3);

   label10 = gtk_label_new(_("X:"));
   gtk_widget_set_name(label10, "label10");
   gtk_widget_ref(label10);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label10);
   gtk_box_pack_start(GTK_BOX(hbox7), label10, TRUE, TRUE, 0);

   scroll_x_adj = gtk_adjustment_new(0, 0, 99999, 0.1, 1, 10);
   scroll_x = gtk_spin_button_new(GTK_ADJUSTMENT(scroll_x_adj), 1, 2);
   gtk_widget_set_name(scroll_x, "scroll_x");
   gtk_widget_ref(scroll_x);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "scroll_x", scroll_x,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(scroll_x);
   gtk_box_pack_start(GTK_BOX(hbox7), scroll_x, TRUE, TRUE, 0);

   label11 = gtk_label_new(_("Y:"));
   gtk_widget_set_name(label11, "label11");
   gtk_widget_ref(label11);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label11);
   gtk_box_pack_start(GTK_BOX(hbox7), label11, TRUE, TRUE, 0);

   scroll_y_adj = gtk_adjustment_new(0, 0, 99999, 0.1, 1, 10);
   scroll_y = gtk_spin_button_new(GTK_ADJUSTMENT(scroll_y_adj), 1, 2);
   gtk_widget_set_name(scroll_y, "scroll_y");
   gtk_widget_ref(scroll_y);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "scroll_y", scroll_y,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(scroll_y);
   gtk_box_pack_start(GTK_BOX(hbox7), scroll_y, TRUE, TRUE, 0);

   label6 = gtk_label_new(_("Scroll"));
   gtk_widget_set_name(label6, "label6");
   gtk_widget_ref(label6);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label6);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook2),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook2), 2),
                              label6);

   frame6 = gtk_frame_new(NULL);
   gtk_widget_set_name(frame6, "frame6");
   gtk_widget_ref(frame6);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "frame6", frame6,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(frame6);
   gtk_container_add(GTK_CONTAINER(notebook2), frame6);

   vbox7 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox7, "vbox7");
   gtk_widget_ref(vbox7);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox7);
   gtk_container_add(GTK_CONTAINER(frame6), vbox7);
   gtk_container_set_border_width(GTK_CONTAINER(vbox7), 4);

   hbox8 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox8, "hbox8");
   gtk_widget_ref(hbox8);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox8);
   gtk_box_pack_start(GTK_BOX(vbox7), hbox8, FALSE, TRUE, 0);
   gtk_container_set_border_width(GTK_CONTAINER(hbox8), 2);

   label12 = gtk_label_new(_("X:"));
   gtk_widget_set_name(label12, "label12");
   gtk_widget_ref(label12);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label12);
   gtk_box_pack_start(GTK_BOX(hbox8), label12, TRUE, TRUE, 0);

   pos_x_adj = gtk_adjustment_new(0, 0, 1, 0.01, 1, 1);
   pos_x = gtk_spin_button_new(GTK_ADJUSTMENT(pos_x_adj), 0.01, 2);
   gtk_widget_set_name(pos_x, "pos_x");
   gtk_widget_ref(pos_x);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "pos_x", pos_x,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(pos_x);
   gtk_box_pack_start(GTK_BOX(hbox8), pos_x, TRUE, TRUE, 0);

   label13 = gtk_label_new(_("Y:"));
   gtk_widget_set_name(label13, "label13");
   gtk_widget_ref(label13);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label13);
   gtk_box_pack_start(GTK_BOX(hbox8), label13, TRUE, TRUE, 0);

   pos_y_adj = gtk_adjustment_new(0, 0, 1, 0.01, 1, 1);
   pos_y = gtk_spin_button_new(GTK_ADJUSTMENT(pos_y_adj), 0.01, 2);
   gtk_widget_set_name(pos_y, "pos_y");
   gtk_widget_ref(pos_y);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "pos_y", pos_y,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(pos_y);
   gtk_box_pack_start(GTK_BOX(hbox8), pos_y, TRUE, TRUE, 0);

   frame2 = gtk_frame_new(_("Absolute Offset From Position:"));
   gtk_widget_set_name(frame2, "frame2");
   gtk_widget_ref(frame2);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(frame2);
   gtk_box_pack_start(GTK_BOX(vbox7), frame2, FALSE, TRUE, 0);
   gtk_container_set_border_width(GTK_CONTAINER(frame2), 2);

   hbox9 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox9, "hbox9");
   gtk_widget_ref(hbox9);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox9", hbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox9);
   gtk_container_add(GTK_CONTAINER(frame2), hbox9);
   gtk_container_set_border_width(GTK_CONTAINER(hbox9), 3);

   label14 = gtk_label_new(_("X:"));
   gtk_widget_set_name(label14, "label14");
   gtk_widget_ref(label14);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label14);
   gtk_box_pack_start(GTK_BOX(hbox9), label14, TRUE, TRUE, 0);

   abs_x_adj = gtk_adjustment_new(0, -9999, 99999, 1, 1, 10);
   abs_x = gtk_spin_button_new(GTK_ADJUSTMENT(abs_x_adj), 1, 0);
   gtk_widget_set_name(abs_x, "abs_x");
   gtk_widget_ref(abs_x);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "abs_x", abs_x,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(abs_x);
   gtk_box_pack_start(GTK_BOX(hbox9), abs_x, TRUE, TRUE, 0);

   label15 = gtk_label_new(_("Y:"));
   gtk_widget_set_name(label15, "label15");
   gtk_widget_ref(label15);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label15);
   gtk_box_pack_start(GTK_BOX(hbox9), label15, TRUE, TRUE, 0);

   abs_y_adj = gtk_adjustment_new(0, -9999, 99999, 1, 1, 10);
   abs_y = gtk_spin_button_new(GTK_ADJUSTMENT(abs_y_adj), 1, 0);
   gtk_widget_set_name(abs_y, "abs_y");
   gtk_widget_ref(abs_y);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "abs_y", abs_y,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(abs_y);
   gtk_box_pack_start(GTK_BOX(hbox9), abs_y, TRUE, TRUE, 0);

   label7 = gtk_label_new(_("Position"));
   gtk_widget_set_name(label7, "label7");
   gtk_widget_ref(label7);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label7);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook2),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook2), 3),
                              label7);

   frame7 = gtk_frame_new(NULL);
   gtk_widget_set_name(frame7, "frame7");
   gtk_widget_ref(frame7);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "frame7", frame7,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(frame7);
   gtk_container_add(GTK_CONTAINER(notebook2), frame7);

   vbox8 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox8, "vbox8");
   gtk_widget_ref(vbox8);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox8);
   gtk_container_add(GTK_CONTAINER(frame7), vbox8);

   hbox10 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox10, "hbox10");
   gtk_widget_ref(hbox10);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox10", hbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox10);
   gtk_box_pack_start(GTK_BOX(vbox8), hbox10, FALSE, TRUE, 0);

   label16 = gtk_label_new(_("Width: "));
   gtk_widget_set_name(label16, "label16");
   gtk_widget_ref(label16);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label16);
   gtk_box_pack_start(GTK_BOX(hbox10), label16, TRUE, TRUE, 0);

   size_w_adj = gtk_adjustment_new(0, 0, 9999, 0.01, 1, 10);
   size_w = gtk_spin_button_new(GTK_ADJUSTMENT(size_w_adj), 1, 2);
   gtk_widget_set_name(size_w, "size_w");
   gtk_widget_ref(size_w);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "size_w", size_w,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(size_w);
   gtk_box_pack_start(GTK_BOX(hbox10), size_w, TRUE, TRUE, 0);

   label17 = gtk_label_new(_("Height"));
   gtk_widget_set_name(label17, "label17");
   gtk_widget_ref(label17);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label17);
   gtk_box_pack_start(GTK_BOX(hbox10), label17, TRUE, TRUE, 0);

   size_h_adj = gtk_adjustment_new(0, 0, 9999, 0.01, 1, 10);
   size_h = gtk_spin_button_new(GTK_ADJUSTMENT(size_h_adj), 1, 2);
   gtk_widget_set_name(size_h, "size_h");
   gtk_widget_ref(size_h);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "size_h", size_h,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(size_h);
   gtk_box_pack_start(GTK_BOX(hbox10), size_h, TRUE, TRUE, 0);

   table1 = gtk_table_new(2, 2, FALSE);
   gtk_widget_set_name(table1, "table1");
   gtk_widget_ref(table1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(table1);
   gtk_box_pack_start(GTK_BOX(vbox8), table1, TRUE, TRUE, 0);

   size_abs_w = gtk_check_button_new_with_label(_("Absolute Width"));
   gtk_widget_set_name(size_abs_w, "size_abs_w");
   gtk_widget_ref(size_abs_w);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "size_abs_w", size_abs_w,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(size_abs_w);
   gtk_table_attach(GTK_TABLE(table1), size_abs_w, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

   size_abs_h = gtk_check_button_new_with_label(_("Absolute Height"));
   gtk_widget_set_name(size_abs_h, "size_abs_h");
   gtk_widget_ref(size_abs_h);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "size_abs_h", size_abs_h,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(size_abs_h);
   gtk_table_attach(GTK_TABLE(table1), size_abs_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

   size_orig_w = gtk_check_button_new_with_label(_("Original Width"));
   gtk_widget_set_name(size_orig_w, "size_orig_w");
   gtk_widget_ref(size_orig_w);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "size_orig_w", size_orig_w,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(size_orig_w);
   gtk_table_attach(GTK_TABLE(table1), size_orig_w, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL), (GtkAttachOptions) (0), 0,
                    0);

   size_orig_h = gtk_check_button_new_with_label(_("Original Height"));
   gtk_widget_set_name(size_orig_h, "size_orig_h");
   gtk_widget_ref(size_orig_h);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "size_orig_h", size_orig_h,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(size_orig_h);
   gtk_table_attach(GTK_TABLE(table1), size_orig_h, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL), (GtkAttachOptions) (0), 0,
                    0);

   label8 = gtk_label_new(_("Size"));
   gtk_widget_set_name(label8, "label8");
   gtk_widget_ref(label8);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label8);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook2),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook2), 4),
                              label8);

   layer_fill_frame = gtk_frame_new(NULL);
   gtk_widget_set_name(layer_fill_frame, "layer_fill_frame");
   gtk_widget_ref(layer_fill_frame);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "layer_fill_frame",
                            layer_fill_frame,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(layer_fill_frame);
   gtk_container_add(GTK_CONTAINER(notebook2), layer_fill_frame);

   vbox9 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox9, "vbox9");
   gtk_widget_ref(vbox9);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox9);
   gtk_container_add(GTK_CONTAINER(layer_fill_frame), vbox9);
   gtk_container_set_border_width(GTK_CONTAINER(vbox9), 3);

   hbox12 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox12, "hbox12");
   gtk_widget_ref(hbox12);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox12", hbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox12);
   gtk_box_pack_start(GTK_BOX(vbox9), hbox12, FALSE, TRUE, 2);
   gtk_container_set_border_width(GTK_CONTAINER(hbox12), 2);

   label18 = gtk_label_new(_("Width: "));
   gtk_widget_set_name(label18, "label18");
   gtk_widget_ref(label18);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label18);
   gtk_box_pack_start(GTK_BOX(hbox12), label18, TRUE, TRUE, 0);

   fill_w_adj = gtk_adjustment_new(0, 0, 9999, 0.01, 1, 10);
   fill_w = gtk_spin_button_new(GTK_ADJUSTMENT(fill_w_adj), 1, 2);
   gtk_widget_set_name(fill_w, "fill_w");
   gtk_widget_ref(fill_w);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "fill_w", fill_w,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(fill_w);
   gtk_box_pack_start(GTK_BOX(hbox12), fill_w, TRUE, TRUE, 0);

   label19 = gtk_label_new(_("Height"));
   gtk_widget_set_name(label19, "label19");
   gtk_widget_ref(label19);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label19);
   gtk_box_pack_start(GTK_BOX(hbox12), label19, TRUE, TRUE, 0);

   fill_h_adj = gtk_adjustment_new(0, 0, 9999, 0.01, 1, 10);
   fill_h = gtk_spin_button_new(GTK_ADJUSTMENT(fill_h_adj), 1, 2);
   gtk_widget_set_name(fill_h, "fill_h");
   gtk_widget_ref(fill_h);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "fill_h", fill_h,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(fill_h);
   gtk_box_pack_start(GTK_BOX(hbox12), fill_h, TRUE, TRUE, 0);

   hbox13 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox13, "hbox13");
   gtk_widget_ref(hbox13);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbox13", hbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox13);
   gtk_box_pack_start(GTK_BOX(vbox9), hbox13, FALSE, TRUE, 0);

   fill_orig_w = gtk_check_button_new_with_label(_("Original Width"));
   gtk_widget_set_name(fill_orig_w, "fill_orig_w");
   gtk_widget_ref(fill_orig_w);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "fill_orig_w", fill_orig_w,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(fill_orig_w);
   gtk_box_pack_start(GTK_BOX(hbox13), fill_orig_w, TRUE, TRUE, 0);

   fill_orig_h = gtk_check_button_new_with_label(_("Original Height"));
   gtk_widget_set_name(fill_orig_h, "fill_orig_h");
   gtk_widget_ref(fill_orig_h);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "fill_orig_h", fill_orig_h,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(fill_orig_h);
   gtk_box_pack_start(GTK_BOX(hbox13), fill_orig_h, TRUE, TRUE, 0);

   label9 = gtk_label_new(_("Fill"));
   gtk_widget_set_name(label9, "label9");
   gtk_widget_ref(label9);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label9);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook2),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook2), 5),
                              label9);

   layer_color_frame = gtk_frame_new(NULL);
   gtk_widget_set_name(layer_color_frame, "layer_color_frame");
   gtk_widget_ref(layer_color_frame);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "layer_color_frame",
                            layer_color_frame,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(layer_color_frame);
   gtk_container_add(GTK_CONTAINER(notebook2), layer_color_frame);

   vbox11 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox11, "vbox11");
   gtk_widget_ref(vbox11);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox11", vbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox11);
   gtk_container_add(GTK_CONTAINER(layer_color_frame), vbox11);

   color_box = gtk_drawing_area_new();
   gtk_widget_set_name(color_box, "color_box");
   gtk_widget_ref(color_box);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "color_box", color_box,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(color_box);
   gtk_box_pack_start(GTK_BOX(vbox11), color_box, FALSE, TRUE, 0);
   gtk_widget_set_usize(color_box, -2, 40);
   gtk_widget_set_events(color_box,
                         GDK_EXPOSURE_MASK | GDK_BUTTON_PRESS_MASK);

   label20 = gtk_label_new(_("Color"));
   gtk_widget_set_name(label20, "label20");
   gtk_widget_ref(label20);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label20);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook2),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook2), 6),
                              label20);

   gradient_frame = gtk_frame_new(NULL);
   gtk_widget_set_name(gradient_frame, "gradient_frame");
   gtk_widget_ref(gradient_frame);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "gradient_frame",
                            gradient_frame,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(gradient_frame);
   gtk_container_add(GTK_CONTAINER(notebook2), gradient_frame);

   table2 = gtk_table_new(3, 2, FALSE);
   gtk_widget_set_name(table2, "table2");
   gtk_widget_ref(table2);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(table2);
   gtk_container_add(GTK_CONTAINER(gradient_frame), table2);

   label22 = gtk_label_new(_("Source Color"));
   gtk_widget_set_name(label22, "label22");
   gtk_widget_ref(label22);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label22);
   gtk_table_attach(GTK_TABLE(table2), label22, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL), (GtkAttachOptions) (0), 0,
                    0);
   gtk_misc_set_alignment(GTK_MISC(label22), 0, 0.5);

   label23 = gtk_label_new(_("Destination Color"));
   gtk_widget_set_name(label23, "label23");
   gtk_widget_ref(label23);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label23);
   gtk_table_attach(GTK_TABLE(table2), label23, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL), (GtkAttachOptions) (0), 0,
                    0);
   gtk_misc_set_alignment(GTK_MISC(label23), 0, 0.5);

   label24 = gtk_label_new(_("Angle Offset"));
   gtk_widget_set_name(label24, "label24");
   gtk_widget_ref(label24);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label24);
   gtk_table_attach(GTK_TABLE(table2), label24, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL), (GtkAttachOptions) (0), 0,
                    0);
   gtk_misc_set_alignment(GTK_MISC(label24), 0, 0.5);

   gradient_one_color_box = gtk_drawing_area_new();
   gtk_widget_set_name(gradient_one_color_box, "gradient_one_color_box");
   gtk_widget_ref(gradient_one_color_box);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "gradient_one_color_box",
                            gradient_one_color_box,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(gradient_one_color_box);
   gtk_table_attach(GTK_TABLE(table2), gradient_one_color_box, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
   gtk_widget_set_usize(gradient_one_color_box, -2, 40);
   gtk_widget_set_events(gradient_one_color_box,
                         GDK_EXPOSURE_MASK | GDK_BUTTON_PRESS_MASK);

   gradient_two_color_box = gtk_drawing_area_new();
   gtk_widget_set_name(gradient_two_color_box, "gradient_two_color_box");
   gtk_widget_ref(gradient_two_color_box);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "gradient_two_color_box",
                            gradient_two_color_box,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(gradient_two_color_box);
   gtk_table_attach(GTK_TABLE(table2), gradient_two_color_box, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
   gtk_widget_set_usize(gradient_two_color_box, -2, 40);
   gtk_widget_set_events(gradient_two_color_box,
                         GDK_EXPOSURE_MASK | GDK_BUTTON_PRESS_MASK);

   gradient_angle_adj = gtk_adjustment_new(0, 0, 360, 1, 10, 10);
   gradient_angle =
      gtk_spin_button_new(GTK_ADJUSTMENT(gradient_angle_adj), 1, 0);
   gtk_widget_set_name(gradient_angle, "gradient_angle");
   gtk_widget_ref(gradient_angle);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "gradient_angle",
                            gradient_angle,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(gradient_angle);
   gtk_table_attach(GTK_TABLE(table2), gradient_angle, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

   label21 = gtk_label_new(_("Gradient"));
   gtk_widget_set_name(label21, "label21");
   gtk_widget_ref(label21);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label21);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook2),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook2), 7),
                              label21);

   whocares = gtk_label_new(_("Advanced"));
   gtk_widget_set_name(whocares, "whocares");
   gtk_widget_ref(whocares);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "whocares", whocares,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(whocares);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook1),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook1), 1),
                              whocares);

   vbox1492 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox1492, "vbox1492");
   gtk_widget_ref(vbox1492);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox1492", vbox1492,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox1492);
   gtk_container_add(GTK_CONTAINER(notebook1), vbox1492);

   scale_preview = gtk_check_button_new_with_label(_("Scale Preview"));
   gtk_widget_set_name(scale_preview, "scale_preview");
   gtk_widget_ref(scale_preview);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "scale_preview",
                            scale_preview,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(scale_preview);
   gtk_box_pack_start(GTK_BOX(vbox1492), scale_preview, FALSE, FALSE, 0);

   screen_size_frame = gtk_frame_new(_("Screen Size"));
   gtk_widget_set_name(screen_size_frame, "screen_size_frame");
   gtk_widget_ref(screen_size_frame);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "screen_size_frame",
                            screen_size_frame,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(screen_size_frame);
   gtk_box_pack_start(GTK_BOX(vbox1492), screen_size_frame, TRUE, TRUE, 0);
   gtk_container_set_border_width(GTK_CONTAINER(screen_size_frame), 2);
   gtk_widget_set_sensitive(screen_size_frame, FALSE);

   vbox14 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox14, "vbox14");
   gtk_widget_ref(vbox14);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "vbox14", vbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox14);
   gtk_container_add(GTK_CONTAINER(screen_size_frame), vbox14);

   table3 = gtk_table_new(3, 2, FALSE);
   gtk_widget_set_name(table3, "table3");
   gtk_widget_ref(table3);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(table3);
   gtk_box_pack_start(GTK_BOX(vbox14), table3, FALSE, FALSE, 0);

   radiobutton1 =
      gtk_radio_button_new_with_label(export_size_group_group, _("640x480"));
   export_size_group_group =
      gtk_radio_button_group(GTK_RADIO_BUTTON(radiobutton1));
   gtk_widget_set_name(radiobutton1, "radiobutton1");
   gtk_widget_ref(radiobutton1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "radiobutton1",
                            radiobutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(radiobutton1);
   gtk_table_attach(GTK_TABLE(table3), radiobutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

   radiobutton2 =
      gtk_radio_button_new_with_label(export_size_group_group, _("800x600"));
   export_size_group_group =
      gtk_radio_button_group(GTK_RADIO_BUTTON(radiobutton2));
   gtk_widget_set_name(radiobutton2, "radiobutton2");
   gtk_widget_ref(radiobutton2);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "radiobutton2",
                            radiobutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(radiobutton2);
   gtk_table_attach(GTK_TABLE(table3), radiobutton2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

   radiobutton3 =
      gtk_radio_button_new_with_label(export_size_group_group, _("1024x768"));
   export_size_group_group =
      gtk_radio_button_group(GTK_RADIO_BUTTON(radiobutton3));
   gtk_widget_set_name(radiobutton3, "radiobutton3");
   gtk_widget_ref(radiobutton3);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "radiobutton3",
                            radiobutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(radiobutton3);
   gtk_table_attach(GTK_TABLE(table3), radiobutton3, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
   gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(radiobutton3), TRUE);

   radiobutton4 =
      gtk_radio_button_new_with_label(export_size_group_group,
                                      _("1280x1024"));
   export_size_group_group =
      gtk_radio_button_group(GTK_RADIO_BUTTON(radiobutton4));
   gtk_widget_set_name(radiobutton4, "radiobutton4");
   gtk_widget_ref(radiobutton4);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "radiobutton4",
                            radiobutton4,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(radiobutton4);
   gtk_table_attach(GTK_TABLE(table3), radiobutton4, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

   radiobutton5 =
      gtk_radio_button_new_with_label(export_size_group_group,
                                      _("1600x1200"));
   export_size_group_group =
      gtk_radio_button_group(GTK_RADIO_BUTTON(radiobutton5));
   gtk_widget_set_name(radiobutton5, "radiobutton5");
   gtk_widget_ref(radiobutton5);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "radiobutton5",
                            radiobutton5,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(radiobutton5);
   gtk_table_attach(GTK_TABLE(table3), radiobutton5, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

   radiobutton6 =
      gtk_radio_button_new_with_label(export_size_group_group, _("Specify"));
   export_size_group_group =
      gtk_radio_button_group(GTK_RADIO_BUTTON(radiobutton6));
   gtk_widget_set_name(radiobutton6, "radiobutton6");
   gtk_widget_ref(radiobutton6);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "radiobutton6",
                            radiobutton6,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(radiobutton6);
   gtk_table_attach(GTK_TABLE(table3), radiobutton6, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

   table5 = gtk_table_new(2, 2, FALSE);
   gtk_widget_set_name(table5, "table5");
   gtk_widget_ref(table5);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "table5", table5,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(table5);
   gtk_box_pack_start(GTK_BOX(vbox14), table5, FALSE, TRUE, 2);

   export_screen_h_adj = gtk_adjustment_new(480, 240, 99999, 20, 200, 200);
   export_screen_h =
      gtk_spin_button_new(GTK_ADJUSTMENT(export_screen_h_adj), 1, 0);
   gtk_widget_set_name(export_screen_h, "export_screen_h");
   gtk_widget_ref(export_screen_h);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "export_screen_h",
                            export_screen_h,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(export_screen_h);
   gtk_table_attach(GTK_TABLE(table5), export_screen_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
   gtk_widget_set_sensitive(export_screen_h, FALSE);

   label26 = gtk_label_new(_("Screen Height"));
   gtk_widget_set_name(label26, "label26");
   gtk_widget_ref(label26);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label26);
   gtk_table_attach(GTK_TABLE(table5), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL), (GtkAttachOptions) (0), 0,
                    0);
   gtk_label_set_justify(GTK_LABEL(label26), GTK_JUSTIFY_LEFT);
   gtk_misc_set_alignment(GTK_MISC(label26), 0.1, 0.5);

   export_screen_w_adj = gtk_adjustment_new(640, 320, 99999, 20, 200, 200);
   export_screen_w =
      gtk_spin_button_new(GTK_ADJUSTMENT(export_screen_w_adj), 1, 0);
   gtk_widget_set_name(export_screen_w, "export_screen_w");
   gtk_widget_ref(export_screen_w);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "export_screen_w",
                            export_screen_w,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(export_screen_w);
   gtk_table_attach(GTK_TABLE(table5), export_screen_w, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
   gtk_widget_set_sensitive(export_screen_w, FALSE);

   label25 = gtk_label_new(_("Screen Width"));
   gtk_widget_set_name(label25, "label25");
   gtk_widget_ref(label25);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label25);
   gtk_table_attach(GTK_TABLE(table5), label25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
   gtk_label_set_justify(GTK_LABEL(label25), GTK_JUSTIFY_LEFT);
   gtk_misc_set_alignment(GTK_MISC(label25), 0.1, 0.5);

   table4 = gtk_table_new(2, 2, FALSE);
   gtk_widget_set_name(table4, "table4");
   gtk_widget_ref(table4);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(table4);
   gtk_box_pack_start(GTK_BOX(vbox14), table4, FALSE, TRUE, 0);

   export_xinerama_v_adj = gtk_adjustment_new(1, 1, 10, 1, 10, 10);
   export_xinerama_v =
      gtk_spin_button_new(GTK_ADJUSTMENT(export_xinerama_v_adj), 1, 0);
   gtk_widget_set_name(export_xinerama_v, "export_xinerama_v");
   gtk_widget_ref(export_xinerama_v);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "export_xinerama_v",
                            export_xinerama_v,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(export_xinerama_v);
   gtk_table_attach(GTK_TABLE(table4), export_xinerama_v, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

   export_xinerama_h_adj = gtk_adjustment_new(1, 1, 10, 1, 10, 10);
   export_xinerama_h =
      gtk_spin_button_new(GTK_ADJUSTMENT(export_xinerama_h_adj), 1, 0);
   gtk_widget_set_name(export_xinerama_h, "export_xinerama_h");
   gtk_widget_ref(export_xinerama_h);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "export_xinerama_h",
                            export_xinerama_h,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(export_xinerama_h);
   gtk_table_attach(GTK_TABLE(table4), export_xinerama_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

   label28 = gtk_label_new(_("Xinerama Vertical"));
   gtk_widget_set_name(label28, "label28");
   gtk_widget_ref(label28);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label28);
   gtk_table_attach(GTK_TABLE(table4), label28, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
   gtk_label_set_justify(GTK_LABEL(label28), GTK_JUSTIFY_LEFT);
   gtk_misc_set_alignment(GTK_MISC(label28), 0.1, 0.5);

   label27 = gtk_label_new(_("Xinerama Horizontal"));
   gtk_widget_set_name(label27, "label27");
   gtk_widget_ref(label27);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label27);
   gtk_table_attach(GTK_TABLE(table4), label27, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
   gtk_label_set_justify(GTK_LABEL(label27), GTK_JUSTIFY_LEFT);
   gtk_misc_set_alignment(GTK_MISC(label27), 0.1, 0.5);

   hbuttonbox1 = gtk_hbutton_box_new();
   gtk_widget_set_name(hbuttonbox1, "hbuttonbox1");
   gtk_widget_ref(hbuttonbox1);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbuttonbox1);
   gtk_box_pack_start(GTK_BOX(vbox14), hbuttonbox1, FALSE, TRUE, 0);
   gtk_container_set_border_width(GTK_CONTAINER(hbuttonbox1), 2);

   export_next_button = gtk_button_new_with_label(_("Export To Image"));
   gtk_widget_set_name(export_next_button, "export_next_button");
   gtk_widget_ref(export_next_button);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "export_next_button",
                            export_next_button,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(export_next_button);
   gtk_container_add(GTK_CONTAINER(hbuttonbox1), export_next_button);
   GTK_WIDGET_SET_FLAGS(export_next_button, GTK_CAN_DEFAULT);

   label29 = gtk_label_new(_("Preview"));
   gtk_widget_set_name(label29, "label29");
   gtk_widget_ref(label29);
   gtk_object_set_data_full(GTK_OBJECT(main_win), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(label29);
   gtk_notebook_set_tab_label(GTK_NOTEBOOK(notebook1),
                              gtk_notebook_get_nth_page(GTK_NOTEBOOK
                                                        (notebook1), 2),
                              label29);

   gtk_signal_connect(GTK_OBJECT(main_win), "delete_event",
                      GTK_SIGNAL_FUNC(on_main_win_delete_event), NULL);
   gtk_signal_connect(GTK_OBJECT(new1), "activate",
                      GTK_SIGNAL_FUNC(on_new_bg_activate), NULL);
   gtk_signal_connect(GTK_OBJECT(open), "activate",
                      GTK_SIGNAL_FUNC(on_open_bg_activate), NULL);
   gtk_signal_connect(GTK_OBJECT(recent_bg_mi), "activate",
                      GTK_SIGNAL_FUNC(on_recent_bg_mi_activate), NULL);
   gtk_signal_connect(GTK_OBJECT(save), "activate",
                      GTK_SIGNAL_FUNC(on_save_bg_activate), NULL);
   gtk_signal_connect(GTK_OBJECT(save_as), "activate",
                      GTK_SIGNAL_FUNC(on_save_bg_as_activate), NULL);
   gtk_signal_connect(GTK_OBJECT(quit), "activate",
                      GTK_SIGNAL_FUNC(on_quit_ebony_activate), NULL);
   gtk_signal_connect(GTK_OBJECT(layer_num), "changed",
                      GTK_SIGNAL_FUNC(on_layer_num_spin_button_changed),
                      NULL);
   gtk_signal_connect(GTK_OBJECT(button3), "clicked",
                      GTK_SIGNAL_FUNC(on_layer_add_clicked), NULL);
   gtk_signal_connect(GTK_OBJECT(button4), "clicked",
                      GTK_SIGNAL_FUNC(on_layer_delete_clicked), NULL);
   gtk_signal_connect(GTK_OBJECT(button1), "clicked",
                      GTK_SIGNAL_FUNC(on_move_layer_up_clicked), NULL);
   gtk_signal_connect(GTK_OBJECT(button2), "clicked",
                      GTK_SIGNAL_FUNC(on_move_layer_downclicked), NULL);
   gtk_signal_connect(GTK_OBJECT(type_image), "toggled",
                      GTK_SIGNAL_FUNC(on_layer_type_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(type_color), "toggled",
                      GTK_SIGNAL_FUNC(on_layer_type_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(type_gradient), "toggled",
                      GTK_SIGNAL_FUNC(on_layer_type_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(image_file), "changed",
                      GTK_SIGNAL_FUNC(on_image_file_entry_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(button5), "clicked",
                      GTK_SIGNAL_FUNC(on_file_select_button_clicked), NULL);
   gtk_signal_connect(GTK_OBJECT(inline_image), "toggled",
                      GTK_SIGNAL_FUNC(on_inline_image_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(color_class_combo), "changed",
                      GTK_SIGNAL_FUNC(on_color_class_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(scroll_x), "changed",
                      GTK_SIGNAL_FUNC(on_scroll_x_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(scroll_y), "changed",
                      GTK_SIGNAL_FUNC(on_scroll_y_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(pos_x), "changed",
                      GTK_SIGNAL_FUNC(on_pos_x_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(pos_y), "changed",
                      GTK_SIGNAL_FUNC(on_pos_y_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(abs_x), "changed",
                      GTK_SIGNAL_FUNC(on_pos_abs_x_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(abs_y), "changed",
                      GTK_SIGNAL_FUNC(on_pos_abs_y_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(size_w), "changed",
                      GTK_SIGNAL_FUNC(on_size_w_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(size_h), "changed",
                      GTK_SIGNAL_FUNC(on_size_h_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(size_abs_w), "toggled",
                      GTK_SIGNAL_FUNC(on_size_abs_w_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(size_abs_h), "toggled",
                      GTK_SIGNAL_FUNC(on_size_abs_h_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(size_orig_w), "toggled",
                      GTK_SIGNAL_FUNC(on_size_orig_w_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(size_orig_h), "toggled",
                      GTK_SIGNAL_FUNC(on_size_orig_h_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(fill_w), "changed",
                      GTK_SIGNAL_FUNC(on_fill_w_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(fill_h), "changed",
                      GTK_SIGNAL_FUNC(on_fill_h_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(fill_orig_w), "toggled",
                      GTK_SIGNAL_FUNC(on_fill_orig_w_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(fill_orig_h), "toggled",
                      GTK_SIGNAL_FUNC(on_fill_orig_h_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(color_box), "expose_event",
                      GTK_SIGNAL_FUNC(on_color_box_expose_event), NULL);
   gtk_signal_connect(GTK_OBJECT(color_box), "button_press_event",
                      GTK_SIGNAL_FUNC(on_color_box_button_release_event),
                      NULL);
   gtk_signal_connect(GTK_OBJECT(gradient_one_color_box), "expose_event",
                      GTK_SIGNAL_FUNC(on_gradient_one_expose_event), NULL);
   gtk_signal_connect(GTK_OBJECT(gradient_one_color_box),
                      "button_press_event",
                      GTK_SIGNAL_FUNC(on_gradient_one_button_release_event),
                      NULL);
   gtk_signal_connect(GTK_OBJECT(gradient_two_color_box),
                      "button_press_event",
                      GTK_SIGNAL_FUNC(on_gradient_two_button_release_event),
                      NULL);
   gtk_signal_connect(GTK_OBJECT(gradient_two_color_box), "expose_event",
                      GTK_SIGNAL_FUNC(on_gradient_two_expose_event), NULL);
   gtk_signal_connect(GTK_OBJECT(gradient_angle), "changed",
                      GTK_SIGNAL_FUNC(on_gradient_angle_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(scale_preview), "toggled",
                      GTK_SIGNAL_FUNC(on_scale_preview_toggled), NULL);
   gtk_signal_connect(GTK_OBJECT(radiobutton1), "toggled",
                      GTK_SIGNAL_FUNC(on_export_size_toggled), (gpointer) 0);
   gtk_signal_connect(GTK_OBJECT(radiobutton2), "toggled",
                      GTK_SIGNAL_FUNC(on_export_size_toggled), (gpointer) 1);
   gtk_signal_connect(GTK_OBJECT(radiobutton3), "toggled",
                      GTK_SIGNAL_FUNC(on_export_size_toggled), (gpointer) 2);
   gtk_signal_connect(GTK_OBJECT(radiobutton4), "toggled",
                      GTK_SIGNAL_FUNC(on_export_size_toggled), (gpointer) 3);
   gtk_signal_connect(GTK_OBJECT(radiobutton5), "toggled",
                      GTK_SIGNAL_FUNC(on_export_size_toggled), (gpointer) 4);
   gtk_signal_connect(GTK_OBJECT(radiobutton6), "toggled",
                      GTK_SIGNAL_FUNC(on_export_size_toggled), (gpointer) 5);
   gtk_signal_connect(GTK_OBJECT(export_screen_h), "changed",
                      GTK_SIGNAL_FUNC(on_export_screen_h_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(export_screen_w), "changed",
                      GTK_SIGNAL_FUNC(on_export_screen_w_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(export_xinerama_v), "changed",
                      GTK_SIGNAL_FUNC(on_export_xinerama_v_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(export_xinerama_h), "changed",
                      GTK_SIGNAL_FUNC(on_export_xinerama_h_changed), NULL);
   gtk_signal_connect(GTK_OBJECT(export_next_button), "clicked",
                      GTK_SIGNAL_FUNC(on_export_button_clicked), NULL);

   gtk_window_add_accel_group(GTK_WINDOW(main_win), accel_group);

   return main_win;
}

GtkWidget *
create_win_bg(void)
{
   GtkWidget *win_bg;
   GtkWidget *vbox13;
   GtkWidget *hbox15;
   GtkWidget *evas;
   GtkWidget *yscale;
   GtkWidget *xscale;
   GtkWidget *_ebony_statusbar;

   win_bg = gtk_window_new(GTK_WINDOW_TOPLEVEL);
   gtk_widget_set_name(win_bg, "win_bg");
   gtk_object_set_data(GTK_OBJECT(win_bg), "win_bg", win_bg);
   gtk_widget_set_uposition(win_bg, 30, -2);
   gtk_window_set_title(GTK_WINDOW(win_bg), _("Filename: "));
   gtk_window_set_default_size(GTK_WINDOW(win_bg), 400, 250);
   gtk_window_set_policy(GTK_WINDOW(win_bg), TRUE, TRUE, FALSE);
   gtk_window_set_wmclass(GTK_WINDOW(win_bg), "Ebony", "Background");

   vbox13 = gtk_vbox_new(FALSE, 0);
   gtk_widget_set_name(vbox13, "vbox13");
   gtk_widget_ref(vbox13);
   gtk_object_set_data_full(GTK_OBJECT(win_bg), "vbox13", vbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(vbox13);
   gtk_container_add(GTK_CONTAINER(win_bg), vbox13);
   gtk_container_set_border_width(GTK_CONTAINER(vbox13), 2);

   hbox15 = gtk_hbox_new(FALSE, 0);
   gtk_widget_set_name(hbox15, "hbox15");
   gtk_widget_ref(hbox15);
   gtk_object_set_data_full(GTK_OBJECT(win_bg), "hbox15", hbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(hbox15);
   gtk_box_pack_start(GTK_BOX(vbox13), hbox15, TRUE, TRUE, 0);
   gtk_container_set_border_width(GTK_CONTAINER(hbox15), 1);

   evas = gtk_drawing_area_new();
   gtk_widget_set_name(evas, "evas");
   gtk_widget_ref(evas);
   gtk_object_set_data_full(GTK_OBJECT(win_bg), "evas", evas,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(evas);
   gtk_box_pack_start(GTK_BOX(hbox15), evas, TRUE, TRUE, 2);
   gtk_widget_set_usize(evas, 200, 200);
   gtk_widget_set_events(evas, GDK_EXPOSURE_MASK);

   yscale =
      gtk_vscale_new(GTK_ADJUSTMENT(gtk_adjustment_new(0, 0, 1024, 0, 0, 0)));
   gtk_widget_set_name(yscale, "yscale");
   gtk_widget_ref(yscale);
   gtk_object_set_data_full(GTK_OBJECT(win_bg), "yscale", yscale,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(yscale);
   gtk_box_pack_start(GTK_BOX(hbox15), yscale, FALSE, FALSE, 0);

   xscale =
      gtk_hscale_new(GTK_ADJUSTMENT(gtk_adjustment_new(0, 0, 1024, 0, 0, 0)));
   gtk_widget_set_name(xscale, "xscale");
   gtk_widget_ref(xscale);
   gtk_object_set_data_full(GTK_OBJECT(win_bg), "xscale", xscale,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(xscale);
   gtk_box_pack_start(GTK_BOX(vbox13), xscale, FALSE, FALSE, 0);

   _ebony_statusbar = gtk_statusbar_new();
   gtk_widget_set_name(_ebony_statusbar, "_ebony_statusbar");
   gtk_widget_ref(_ebony_statusbar);
   gtk_object_set_data_full(GTK_OBJECT(win_bg), "_ebony_statusbar",
                            _ebony_statusbar,
                            (GtkDestroyNotify) gtk_widget_unref);
   gtk_widget_show(_ebony_statusbar);
   gtk_box_pack_start(GTK_BOX(vbox13), _ebony_statusbar, FALSE, FALSE, 0);

   gtk_signal_connect(GTK_OBJECT(win_bg), "delete_event",
                      GTK_SIGNAL_FUNC(on_win_bg_delete_event), NULL);
   gtk_signal_connect(GTK_OBJECT(win_bg), "key_press_event",
                      GTK_SIGNAL_FUNC(on_win_bg_button_press_event), NULL);
   gtk_signal_connect(GTK_OBJECT(evas), "configure_event",
                      GTK_SIGNAL_FUNC(on_bg_evas_configure_event), NULL);
   gtk_signal_connect(GTK_OBJECT(evas), "drag_data_received",
                      GTK_SIGNAL_FUNC(on_bg_evas_drag_data_received), NULL);
   gtk_signal_connect(GTK_OBJECT(evas), "expose_event",
                      GTK_SIGNAL_FUNC(on_evas_expose_event), NULL);

   return win_bg;
}
