/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <gdk/gdkx.h>

#include "interface.h"
#include "support.h"
#include "ebony.h"
#include "gtk_util.h"
#include "util.h"

void
init_globals(void)
{
   win_ref = NULL;
   ebony_status = NULL;
   bg_ref = NULL;

   recent_bgs = NULL;

   evas = NULL;
   bg = NULL;
   bl = NULL;
   idle = 0;
}

int
main(int argc, char *argv[])
{
   GtkWidget *main_win;
   GtkWidget *w;
   int rx, ry, rw, rh, rd;
   char bgfile[PATH_MAX];

   bgfile[0] = '\0';



#ifdef ENABLE_NLS
   bindtextdomain(PACKAGE, PACKAGE_LOCALE_DIR);
   textdomain(PACKAGE);
#endif

   init_globals();
   gtk_set_locale();
   gtk_init(&argc, &argv);

   add_pixmap_directory(PACKAGE_DATA_DIR "/pixmaps");
   add_pixmap_directory(PACKAGE_SOURCE_DIR "/pixmaps");

   /* 
    * The following code was added by Glade to create one of each component
    * (except popup menus), just so that you see something after building
    * the project. Delete any components that you don't want shown initially.
    */
   main_win = create_main_win();
   gtk_widget_show(main_win);
   win_ref = main_win;

   rebuild_bg_ref();

   gdk_window_get_geometry(GDK_ROOT_PARENT(), &rx, &ry, &rw, &rh, &rd);
   gtk_widget_realize(GTK_WIDGET(main_win));

   /* drawing area requests initialization */
   gdk_rgb_init();

   w = gtk_object_get_data(GTK_OBJECT(win_ref), "color_box");
   if (w)
      gtk_widget_realize(w);

   w = gtk_object_get_data(GTK_OBJECT(win_ref), "gradient_one_color_box");
   if (w)
      gtk_widget_realize(w);

   w = gtk_object_get_data(GTK_OBJECT(win_ref), "gradient_two_color_box");
   if (w)
      gtk_widget_realize(w);


   /* load the file passed as argv[1] or create a new bg */
   if (argv[1])
   {
      snprintf(bgfile, PATH_MAX, "%s", argv[1]);
      open_bg_named(bgfile);
   }
   else
      open_bg_named(PACKAGE_DATA_DIR "/pixmaps/ebony.bg.db");

   set_spin_value("layer_num", 0);

   gtk_main();
   return 0;
}
