.TH gozer 1 "Oct 26, 2000"
.SH NAME
gozer - a commandline text renderer
.SH SYNOPSIS
gozer [options] [file]
.SH DESCRIPTION
.B gozer
is a commandline text rendering utility for creating images from abitrary
text in antialised truetype fonts using optional fontstyles, wordwrapping and
layout control.
.B gozer
uses the
.B imlib2
library to create and save images.
.B gozer
has a few options, detailed below. Specify [file] as the filename to save
the rendered text to. Options can also be specified in an
.B rc file
, allowing you to save commonly used options (such as fontpaths) for reuse.
The
.B rc file
$HOME/.gozerrc is always parsed for default settings, and other rc files can
be specified on the commandline to override these options. See
.B RC FILES
for information on syntax.
.SH OPTIONS
.TP 5
.B -h, --help
display help output and exit.
.TP 5
.B -v, --version
output version information and exit.
.TP 5
.B -b, --background COL
use COL as the background color, see
.B COLOUR_DEFINITIONS
for syntax, default is transparent (0,0,0,0).
.TP 5
.B -f, --foreground COL
use COL as the foreground color. Default is white (255,255,255,255).
.TP 5
.B -F, --font STR
draw using font STR. Size is specified with the name, eg 'arial/12' for 12pt
arial, default is 20thcent/16 (a font supplied by gozer).
.TP 5
.B -j, --justification STR
justify text, allowed values for STR are left, right, center or block. Default is left.
.TP 5
.B -l, --line-spacing INT
separate multiple lines by INT pixels, default 1.
.TP 5
.B -p, --fontpath STR
colon seperated list of font directories to search for fonts in. Best used
in the RCFILE to save typing it each time.
.TP 5
.B -q, --quality INT
1-100, effects quality of output for certain formats, e.g. jpeg compression
(higher means higher quality).
.TP 5
.B -P, --pipe
Pipe input text from standard in instead of reading it from a file.
.TP 5
.B -r, --rc-file STR
use STR as the rc file to look for extra options, default is $HOME/.gozerrc
.TP 5
.B -s, --style STR
use STR as a file to load a fontstyle from, see
.B FONTSTYLES
for syntax.
.TP 5
.B -t, --text STR
use STR as text to draw.
.TP 5
.B -T, --textfile STR
read text to draw from file STR.
.TP 5
.B -w, --wrap INT
wordwrap the text to INT pixels.
.TP 5
.B -x, --x-offset INT
Offset text horizontally from top left by INT pixels.
.TP 5
.B -y, --y-offset INT
Offset text vertically from top left by INT pixels.
.SH RC FILES
rc file syntax is simple. The '#' character at the start of a line denotes
that the line is a comment, otherwise lines are started with the name of a
long option from the commandline (without prefixing the --), some whitespace
and the value of the option. E.g.
.br
fontpath /usr/share/truetype:/usr/local/share/truetype
.br
.B NOTE
that options in a --rc-file specified rc file
.B OVERRIDE
those from the commandline, but the $HOME/.gozerrc file is
.B always
read first for default settings.
.SH COLOUR_DEFINITIONS
You can define colours in 4 ways. Using the html style:
#RRGGBB (in which case alpha defaults to 255),
.br
#RRGGBBAA, or an alternative style:
.br
r,g,b or r,g,b,a (no spaces between commas please).
.br
eg for white text, either use #ffffff, #ffffffff, "255,255,255" or
"255,255,255,255". For red, #ff0000, #ff0000ff or "255,0,0" etc.
.SH FONTSTYLES
fontstyles can be defined in the EFM syntax (for compatibility only, these
are not as powerful), or the recommended syntax defined here.
.br
The first line contains the line:
.br
#Style
.br
The second, an optional style name,
.br
#NAME mystyle
.br
There follows a list of layers. Each is described by this rule:
.br
RED GREEN BLUE ALPHA X_OFFSET Y_OFFSET
.br
The special values or 0,0,0,0 for red, green, blue and alpha specify the
positioning of the actual text in it's selected colour.
.br
For example, the following style defines a very simple shadow for text:
.br
#Style
.br
#NAME shadow
.br
0 0 0 128 -3 -3
.br
0 0 0 0 0 0
.SH BUGS
None known.
.SH LICENSE
Copyright Tom Gilbert 2000
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to
deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in
all copies of the Software, its documentation and marketing & publicity
materials, and acknowledgment shall be given in the documentation, materials
and software packages that this Software was used.
.PP
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.PP
Email bugs and feature requests to
.br
.B <gozer_sucks@linuxbrit.co.uk>
