/**
 * @file Etk.h
 * @brief The file to include in an Etk project
 */
#ifndef _ETK_H_
#define _ETK_H_

#include "etk_main.h"
#include "etk_types.h"
#include "etk_utils.h"
#include "etk_type.h"
#include "etk_object.h"
#include "etk_signal.h"
#include "etk_signal_callback.h"
#include "etk_marshallers.h"
#include "etk_property.h"
#include "etk_string.h"

#include "etk_theme.h"
#include "etk_cache.h"
#include "etk_widget.h"
#include "etk_stock.h"
#include "etk_bin.h"
#include "etk_box.h"
#include "etk_hbox.h"
#include "etk_vbox.h"
#include "etk_table.h"
#include "etk_alignment.h"
#include "etk_frame.h"
#include "etk_paned.h"
#include "etk_scrolled_view.h"
#include "etk_viewport.h"
#include "etk_window.h"
#include "etk_dialog.h"
#include "etk_label.h"
#include "etk_image.h"
#include "etk_button.h"
#include "etk_toggle_button.h"
#include "etk_check_button.h"
#include "etk_radio_button.h"
#include "etk_text_buffer.h"
#include "etk_text_iter.h"
#include "etk_editable_text_object.h"
#include "etk_entry.h"
#include "etk_text_view.h"
#include "etk_canvas.h"
#include "etk_colorpicker.h"
#include "etk_colorpicker_vertical.h"
#include "etk_colorpicker_square.h"
#include "etk_tree.h"
#include "etk_tree_model.h"
#include "etk_range.h"
#include "etk_slider.h"
#include "etk_scrollbar.h"
#include "etk_separator.h"
#include "etk_menu_shell.h"
#include "etk_menu.h"
#include "etk_menu_bar.h"
#include "etk_menu_item.h"
#include "etk_statusbar.h"
#include "etk_filechooser_widget.h"
#include "etk_notebook.h"
#include "etk_progress_bar.h"
#include "etk_spin_button.h"
#include "etk_dnd.h"
#include "etk_clipboard.h"

#endif
