=head1 NAME

e-utils - enlightement utilities

=head1 SYNOPSIS

e-utils are various scripts and programs used by the enlightenment window manager. They are generally employed directly by enlightenment itself or through menu
selections.

=head1 DESCRIPTION

=item

B<e_cache_clean>, B<e_cache_query> - clean and query enlightenment's cache

=item

B<e_gen_menu>, B<e_gen_kde_menu>, B<e_gen_gnome_menu> - generate file.menu format files in $HOME/.enlightenment/

=item
B<enlightenment.install> - creates user startup script

=item

B<epp> - the enlightenment pre-processor, processes macros in enlightenment's config files

=item
B<dox> - enlightenment documentation viewer

=item

B<eesh> - enlightenment extended shell, sends IPC commands to enlightenment, see
eesh C<-h> for more info

=head1 AUTHOR

Laurence J. Lane <B<ljlane@debian.org>>

=head1 SEE ALSO

enlightenment(1)

