/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

/*******/
extern GdkVisual *gdk_vis;
extern GdkColormap *gdk_cmap;
/*******/

GtkWidget*
create_main (void)
{
  GtkWidget *main;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *flie1;
  GtkWidget *flie1_menu;
  GtkAccelGroup *flie1_menu_accels;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separator1;
  GtkWidget *preferences1;
  GtkWidget *separator2;
  GtkWidget *exit1;
  GtkWidget *edit1;
  GtkWidget *edit1_menu;
  GtkAccelGroup *edit1_menu_accels;
  GtkWidget *delete1;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *about1;
  GtkWidget *table1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *view;
  GtkWidget *alignment2;
  GtkWidget *vbox3;
  GtkWidget *toolbar3;
  GtkWidget *new_image;
  GtkWidget *new_icon;
  GtkWidget *new_text;
  GtkWidget *raise;
  GtkWidget *lower;
  GtkWidget *delete;
  GtkWidget *reset;
  GtkWidget *vbuttonbox1;
  GtkWidget *prop_apply;
  GtkWidget *prop_reset;
  GtkWidget *draft;
  GtkWidget *vbox2;
  GtkWidget *properties;
  GtkWidget *table5;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkObject *tl_abs_h_adj;
  GtkWidget *tl_abs_h;
  GtkObject *tl_abs_v_adj;
  GtkWidget *tl_abs_v;
  GtkObject *tl_rel_h_adj;
  GtkWidget *tl_rel_h;
  GtkObject *tl_adj_h_adj;
  GtkWidget *tl_adj_h;
  GtkObject *tl_adj_v_adj;
  GtkWidget *tl_adj_v;
  GtkObject *tl_rel_v_adj;
  GtkWidget *tl_rel_v;
  GtkWidget *tl_rel_combo;
  GtkWidget *tl_rel;
  GtkWidget *hseparator4;
  GtkWidget *hseparator3;
  GtkWidget *label29;
  GtkWidget *label28;
  GtkWidget *label27;
  GtkWidget *label26;
  GtkWidget *label5;
  GtkWidget *table8;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkObject *br_abs_h_adj;
  GtkWidget *br_abs_h;
  GtkObject *br_abs_v_adj;
  GtkWidget *br_abs_v;
  GtkObject *br_rel_h_adj;
  GtkWidget *br_rel_h;
  GtkObject *br_adj_h_adj;
  GtkWidget *br_adj_h;
  GtkObject *br_adj_v_adj;
  GtkWidget *br_adj_v;
  GtkObject *br_rel_v_adj;
  GtkWidget *br_rel_v;
  GtkWidget *br_rel_combo;
  GtkWidget *br_rel;
  GtkWidget *hseparator8;
  GtkWidget *hseparator9;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label6;
  GtkWidget *table4;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkObject *content_alignment_h_adj;
  GtkWidget *content_alignment_h;
  GtkObject *content_alignment_v_adj;
  GtkWidget *content_alignment_v;
  GtkObject *aspect_h_adj;
  GtkWidget *aspect_h;
  GtkObject *aspect_v_adj;
  GtkWidget *aspect_v;
  GtkWidget *hseparator2;
  GtkWidget *aspect;
  GtkWidget *label23;
  GtkWidget *label20;
  GtkWidget *label7;
  GtkWidget *table3;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkObject *min_h_adj;
  GtkWidget *min_h;
  GtkObject *min_v_adj;
  GtkWidget *min_v;
  GtkObject *max_h_adj;
  GtkWidget *max_h;
  GtkObject *max_v_adj;
  GtkWidget *max_v;
  GtkObject *step_h_adj;
  GtkWidget *step_h;
  GtkObject *step_v_adj;
  GtkWidget *step_v;
  GtkWidget *use_contents_h;
  GtkWidget *use_contents_v;
  GtkWidget *hseparator1;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label8;
  GtkWidget *scrolledwindow4;
  GtkWidget *sync_list;
  GtkWidget *label14;
  GtkWidget *label9;
  GtkWidget *table2;
  GtkWidget *name;
  GtkWidget *class_combo;
  GList *class_combo_items = NULL;
  GtkWidget *class;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *type;
  GtkWidget *type_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *label10;
  GtkWidget *table7;
  GtkObject *border_l_adj;
  GtkWidget *border_l;
  GtkObject *border_r_adj;
  GtkWidget *border_r;
  GtkObject *border_t_adj;
  GtkWidget *border_t;
  GtkObject *border_b_adj;
  GtkWidget *border_b;
  GtkWidget *hseparator7;
  GtkWidget *img_normal;
  GtkWidget *img_hilited;
  GtkWidget *img_clicked;
  GtkWidget *img_disabled;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label60;
  GtkWidget *tile_h_combo;
  GList *tile_h_combo_items = NULL;
  GtkWidget *tile_h;
  GtkWidget *tile_v_combo;
  GList *tile_v_combo_items = NULL;
  GtkWidget *tile_v;
  GtkWidget *browse_clicked;
  GtkWidget *borwse_hilited;
  GtkWidget *browse_normal;
  GtkWidget *browse_disabled;
  GtkWidget *label36;
  GtkWidget *table9;
  GtkObject *bit_pad_l_adj;
  GtkWidget *bit_pad_l;
  GtkObject *bit_min_h_adj;
  GtkWidget *bit_min_h;
  GtkObject *bit_min_v_adj;
  GtkWidget *bit_min_v;
  GtkObject *bit_max_h_adj;
  GtkWidget *bit_max_h;
  GtkObject *bit_max_v_adj;
  GtkWidget *bit_max_v;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkObject *bit_pad_r_adj;
  GtkWidget *bit_pad_r;
  GtkObject *bit_pad_t_adj;
  GtkWidget *bit_pad_t;
  GtkObject *bit_pad_b_adj;
  GtkWidget *bit_pad_b;
  GtkObject *bit_inset_l_adj;
  GtkWidget *bit_inset_l;
  GtkObject *bit_inset_r_adj;
  GtkWidget *bit_inset_r;
  GtkObject *bit_inset_t_adj;
  GtkWidget *bit_inset_t;
  GtkObject *bit_inset_b_adj;
  GtkWidget *bit_inset_b;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label52;
  GtkWidget *hbuttonbox1;
  GtkWidget *frame1;
  GtkWidget *zoom;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow3;
  GtkWidget *images;
  GtkWidget *label1;
  GtkWidget *scrolledwindow2;
  GtkWidget *states;
  GtkWidget *label2;
  GtkWidget *hbox1;
  GtkWidget *file;
  GtkWidget *label48;
  GtkWidget *x;
  GtkWidget *label49;
  GtkWidget *y;
  GtkWidget *label50;
  GtkWidget *width;
  GtkWidget *label51;
  GtkWidget *height;

  main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (main), "main", main);
  gtk_window_set_title (GTK_WINDOW (main), _("Etcher"));
  gtk_window_set_policy (GTK_WINDOW (main), FALSE, TRUE, TRUE);
  gtk_window_set_wmclass (GTK_WINDOW (main), "Main", "Etcher");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (main), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (main), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  flie1 = gtk_menu_item_new_with_label (_("File"));
  gtk_widget_ref (flie1);
  gtk_object_set_data_full (GTK_OBJECT (main), "flie1", flie1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (flie1);
  gtk_container_add (GTK_CONTAINER (menubar1), flie1);

  flie1_menu = gtk_menu_new ();
  gtk_widget_ref (flie1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main), "flie1_menu", flie1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (flie1), flie1_menu);
  flie1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (flie1_menu));

  open1 = gtk_menu_item_new_with_label (_("Open..."));
  gtk_widget_ref (open1);
  gtk_object_set_data_full (GTK_OBJECT (main), "open1", open1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (flie1_menu), open1);

  save1 = gtk_menu_item_new_with_label (_("Save"));
  gtk_widget_ref (save1);
  gtk_object_set_data_full (GTK_OBJECT (main), "save1", save1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (flie1_menu), save1);

  save_as1 = gtk_menu_item_new_with_label (_("Save As..."));
  gtk_widget_ref (save_as1);
  gtk_object_set_data_full (GTK_OBJECT (main), "save_as1", save_as1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (flie1_menu), save_as1);

  separator1 = gtk_menu_item_new ();
  gtk_widget_ref (separator1);
  gtk_object_set_data_full (GTK_OBJECT (main), "separator1", separator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (flie1_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  preferences1 = gtk_menu_item_new_with_label (_("Preferences..."));
  gtk_widget_ref (preferences1);
  gtk_object_set_data_full (GTK_OBJECT (main), "preferences1", preferences1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (preferences1);
  gtk_container_add (GTK_CONTAINER (flie1_menu), preferences1);

  separator2 = gtk_menu_item_new ();
  gtk_widget_ref (separator2);
  gtk_object_set_data_full (GTK_OBJECT (main), "separator2", separator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (flie1_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  exit1 = gtk_menu_item_new_with_label (_("Exit"));
  gtk_widget_ref (exit1);
  gtk_object_set_data_full (GTK_OBJECT (main), "exit1", exit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit1);
  gtk_container_add (GTK_CONTAINER (flie1_menu), exit1);

  edit1 = gtk_menu_item_new_with_label (_("Edit"));
  gtk_widget_ref (edit1);
  gtk_object_set_data_full (GTK_OBJECT (main), "edit1", edit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit1);
  gtk_container_add (GTK_CONTAINER (menubar1), edit1);

  edit1_menu = gtk_menu_new ();
  gtk_widget_ref (edit1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main), "edit1_menu", edit1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (edit1), edit1_menu);
  edit1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (edit1_menu));

  delete1 = gtk_menu_item_new_with_label (_("Delete"));
  gtk_widget_ref (delete1);
  gtk_object_set_data_full (GTK_OBJECT (main), "delete1", delete1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), delete1);

  help1 = gtk_menu_item_new_with_label (_("Help"));
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (main), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar1), help1);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help1));

  help1_menu = gtk_menu_new ();
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (main), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  about1 = gtk_menu_item_new_with_label (_("About"));
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (main), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about1);

  table1 = gtk_table_new (3, 3, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (main), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (main), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_table_attach (GTK_TABLE (table1), scrolledwindow1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_widget_set_usize (scrolledwindow1, 300, 260);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow1), 2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (main), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

   /*******/
   gtk_widget_push_visual(gdk_vis);
   gtk_widget_push_colormap(gdk_cmap);
   /*******/
   
   view = gtk_drawing_area_new ();
   
   /*******/
   gtk_widget_pop_visual();
   gtk_widget_pop_colormap();
   /*******/
   
  gtk_widget_ref (view);
  gtk_object_set_data_full (GTK_OBJECT (main), "view", view,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (view);
  gtk_container_add (GTK_CONTAINER (viewport1), view);
  gtk_widget_set_events (view, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_ref (alignment2);
  gtk_object_set_data_full (GTK_OBJECT (main), "alignment2", alignment2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (alignment2);
  gtk_table_attach (GTK_TABLE (table1), alignment2, 0, 1, 1, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (main), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (alignment2), vbox3);

  toolbar3 = gtk_toolbar_new (GTK_ORIENTATION_VERTICAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar3);
  gtk_object_set_data_full (GTK_OBJECT (main), "toolbar3", toolbar3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar3);
  gtk_box_pack_start (GTK_BOX (vbox3), toolbar3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar3), 2);

  new_image = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Image"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (new_image);
  gtk_object_set_data_full (GTK_OBJECT (main), "new_image", new_image,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (new_image);

  new_icon = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Icon"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (new_icon);
  gtk_object_set_data_full (GTK_OBJECT (main), "new_icon", new_icon,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (new_icon);
  gtk_widget_set_sensitive (new_icon, FALSE);

  new_text = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Text"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (new_text);
  gtk_object_set_data_full (GTK_OBJECT (main), "new_text", new_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (new_text);
  gtk_widget_set_sensitive (new_text, FALSE);

  raise = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Raise"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (raise);
  gtk_object_set_data_full (GTK_OBJECT (main), "raise", raise,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (raise);

  lower = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Lower"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (lower);
  gtk_object_set_data_full (GTK_OBJECT (main), "lower", lower,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lower);

  delete = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Delete"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (delete);
  gtk_object_set_data_full (GTK_OBJECT (main), "delete", delete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delete);

  reset = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Reset"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (reset);
  gtk_object_set_data_full (GTK_OBJECT (main), "reset", reset,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (reset);

  vbuttonbox1 = gtk_vbutton_box_new ();
  gtk_widget_ref (vbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (main), "vbuttonbox1", vbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), vbuttonbox1, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (vbuttonbox1), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (vbuttonbox1), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (vbuttonbox1), 0, 0);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (vbuttonbox1), 0, 0);

  prop_apply = gtk_button_new_with_label (_("Apply"));
  gtk_widget_ref (prop_apply);
  gtk_object_set_data_full (GTK_OBJECT (main), "prop_apply", prop_apply,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (prop_apply);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), prop_apply);
  GTK_WIDGET_SET_FLAGS (prop_apply, GTK_CAN_DEFAULT);

  prop_reset = gtk_button_new_with_label (_("Reset"));
  gtk_widget_ref (prop_reset);
  gtk_object_set_data_full (GTK_OBJECT (main), "prop_reset", prop_reset,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (prop_reset);
  gtk_container_add (GTK_CONTAINER (vbuttonbox1), prop_reset);
  GTK_WIDGET_SET_FLAGS (prop_reset, GTK_CAN_DEFAULT);

  draft = gtk_toggle_button_new_with_label (_("Draft"));
  gtk_widget_ref (draft);
  gtk_object_set_data_full (GTK_OBJECT (main), "draft", draft,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (draft);
  gtk_table_attach (GTK_TABLE (table1), draft, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (draft), 2);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (draft), TRUE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (main), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_table_attach (GTK_TABLE (table1), vbox2, 1, 2, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  properties = gtk_notebook_new ();
  gtk_widget_ref (properties);
  gtk_object_set_data_full (GTK_OBJECT (main), "properties", properties,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (properties);
  gtk_box_pack_start (GTK_BOX (vbox2), properties, TRUE, TRUE, 0);
  gtk_widget_set_usize (properties, 360, -2);
  gtk_container_set_border_width (GTK_CONTAINER (properties), 2);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (properties), GTK_POS_BOTTOM);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (properties), TRUE);
  gtk_notebook_set_tab_hborder (GTK_NOTEBOOK (properties), 0);
  gtk_notebook_set_tab_vborder (GTK_NOTEBOOK (properties), 0);
  gtk_notebook_popup_enable (GTK_NOTEBOOK (properties));

  table5 = gtk_table_new (7, 3, FALSE);
  gtk_widget_ref (table5);
  gtk_object_set_data_full (GTK_OBJECT (main), "table5", table5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (properties), table5);
  gtk_container_set_border_width (GTK_CONTAINER (table5), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table5), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table5), 2);

  label24 = gtk_label_new (_("Horizontal"));
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (main), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table5), label24, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label25 = gtk_label_new (_("Vertical"));
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (main), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table5), label25, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  tl_abs_h_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  tl_abs_h = gtk_spin_button_new (GTK_ADJUSTMENT (tl_abs_h_adj), 1, 0);
  gtk_widget_ref (tl_abs_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "tl_abs_h", tl_abs_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tl_abs_h);
  gtk_table_attach (GTK_TABLE (table5), tl_abs_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  tl_abs_v_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  tl_abs_v = gtk_spin_button_new (GTK_ADJUSTMENT (tl_abs_v_adj), 1, 0);
  gtk_widget_ref (tl_abs_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "tl_abs_v", tl_abs_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tl_abs_v);
  gtk_table_attach (GTK_TABLE (table5), tl_abs_v, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  tl_rel_h_adj = gtk_adjustment_new (1.49012e-08, 0, 100, 0.1, 10, 10);
  tl_rel_h = gtk_spin_button_new (GTK_ADJUSTMENT (tl_rel_h_adj), 1, 1);
  gtk_widget_ref (tl_rel_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "tl_rel_h", tl_rel_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tl_rel_h);
  gtk_table_attach (GTK_TABLE (table5), tl_rel_h, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  tl_adj_h_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  tl_adj_h = gtk_spin_button_new (GTK_ADJUSTMENT (tl_adj_h_adj), 1, 0);
  gtk_widget_ref (tl_adj_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "tl_adj_h", tl_adj_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tl_adj_h);
  gtk_table_attach (GTK_TABLE (table5), tl_adj_h, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  tl_adj_v_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  tl_adj_v = gtk_spin_button_new (GTK_ADJUSTMENT (tl_adj_v_adj), 1, 0);
  gtk_widget_ref (tl_adj_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "tl_adj_v", tl_adj_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tl_adj_v);
  gtk_table_attach (GTK_TABLE (table5), tl_adj_v, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  tl_rel_v_adj = gtk_adjustment_new (0, 0, 100, 0.1, 10, 10);
  tl_rel_v = gtk_spin_button_new (GTK_ADJUSTMENT (tl_rel_v_adj), 1, 1);
  gtk_widget_ref (tl_rel_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "tl_rel_v", tl_rel_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tl_rel_v);
  gtk_table_attach (GTK_TABLE (table5), tl_rel_v, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  tl_rel_combo = gtk_combo_new ();
  gtk_widget_ref (tl_rel_combo);
  gtk_object_set_data_full (GTK_OBJECT (main), "tl_rel_combo", tl_rel_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tl_rel_combo);
  gtk_table_attach (GTK_TABLE (table5), tl_rel_combo, 1, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  tl_rel = GTK_COMBO (tl_rel_combo)->entry;
  gtk_widget_ref (tl_rel);
  gtk_object_set_data_full (GTK_OBJECT (main), "tl_rel", tl_rel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tl_rel);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator4);
  gtk_object_set_data_full (GTK_OBJECT (main), "hseparator4", hseparator4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator4);
  gtk_table_attach (GTK_TABLE (table5), hseparator4, 0, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator3);
  gtk_object_set_data_full (GTK_OBJECT (main), "hseparator3", hseparator3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator3);
  gtk_table_attach (GTK_TABLE (table5), hseparator3, 0, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label29 = gtk_label_new (_("Relative Pre-Adjust"));
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (main), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table5), label29, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 7.45058e-09, 0.5);

  label28 = gtk_label_new (_("Relative Location"));
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (main), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table5), label28, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 7.45058e-09, 0.5);

  label27 = gtk_label_new (_("Relative to Bit Name"));
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (main), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table5), label27, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 7.45058e-09, 0.5);

  label26 = gtk_label_new (_("Pixel Location"));
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (main), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table5), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 7.45058e-09, 0.5);

  label5 = gtk_label_new (_("Top Left"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (main), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (properties), gtk_notebook_get_nth_page (GTK_NOTEBOOK (properties), 0), label5);

  table8 = gtk_table_new (7, 3, FALSE);
  gtk_widget_ref (table8);
  gtk_object_set_data_full (GTK_OBJECT (main), "table8", table8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table8);
  gtk_container_add (GTK_CONTAINER (properties), table8);
  gtk_container_set_border_width (GTK_CONTAINER (table8), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 2);

  label42 = gtk_label_new (_("Horizontal"));
  gtk_widget_ref (label42);
  gtk_object_set_data_full (GTK_OBJECT (main), "label42", label42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label42);
  gtk_table_attach (GTK_TABLE (table8), label42, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label43 = gtk_label_new (_("Vertical"));
  gtk_widget_ref (label43);
  gtk_object_set_data_full (GTK_OBJECT (main), "label43", label43,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label43);
  gtk_table_attach (GTK_TABLE (table8), label43, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  br_abs_h_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  br_abs_h = gtk_spin_button_new (GTK_ADJUSTMENT (br_abs_h_adj), 1, 0);
  gtk_widget_ref (br_abs_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "br_abs_h", br_abs_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (br_abs_h);
  gtk_table_attach (GTK_TABLE (table8), br_abs_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  br_abs_v_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  br_abs_v = gtk_spin_button_new (GTK_ADJUSTMENT (br_abs_v_adj), 1, 0);
  gtk_widget_ref (br_abs_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "br_abs_v", br_abs_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (br_abs_v);
  gtk_table_attach (GTK_TABLE (table8), br_abs_v, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  br_rel_h_adj = gtk_adjustment_new (1.49012e-08, 0, 100, 0.1, 10, 10);
  br_rel_h = gtk_spin_button_new (GTK_ADJUSTMENT (br_rel_h_adj), 1, 1);
  gtk_widget_ref (br_rel_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "br_rel_h", br_rel_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (br_rel_h);
  gtk_table_attach (GTK_TABLE (table8), br_rel_h, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  br_adj_h_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  br_adj_h = gtk_spin_button_new (GTK_ADJUSTMENT (br_adj_h_adj), 1, 0);
  gtk_widget_ref (br_adj_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "br_adj_h", br_adj_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (br_adj_h);
  gtk_table_attach (GTK_TABLE (table8), br_adj_h, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  br_adj_v_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  br_adj_v = gtk_spin_button_new (GTK_ADJUSTMENT (br_adj_v_adj), 1, 0);
  gtk_widget_ref (br_adj_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "br_adj_v", br_adj_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (br_adj_v);
  gtk_table_attach (GTK_TABLE (table8), br_adj_v, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  br_rel_v_adj = gtk_adjustment_new (0, 0, 100, 0.1, 10, 10);
  br_rel_v = gtk_spin_button_new (GTK_ADJUSTMENT (br_rel_v_adj), 1, 1);
  gtk_widget_ref (br_rel_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "br_rel_v", br_rel_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (br_rel_v);
  gtk_table_attach (GTK_TABLE (table8), br_rel_v, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  br_rel_combo = gtk_combo_new ();
  gtk_widget_ref (br_rel_combo);
  gtk_object_set_data_full (GTK_OBJECT (main), "br_rel_combo", br_rel_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (br_rel_combo);
  gtk_table_attach (GTK_TABLE (table8), br_rel_combo, 1, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  br_rel = GTK_COMBO (br_rel_combo)->entry;
  gtk_widget_ref (br_rel);
  gtk_object_set_data_full (GTK_OBJECT (main), "br_rel", br_rel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (br_rel);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator8);
  gtk_object_set_data_full (GTK_OBJECT (main), "hseparator8", hseparator8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator8);
  gtk_table_attach (GTK_TABLE (table8), hseparator8, 0, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator9 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator9);
  gtk_object_set_data_full (GTK_OBJECT (main), "hseparator9", hseparator9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator9);
  gtk_table_attach (GTK_TABLE (table8), hseparator9, 0, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label44 = gtk_label_new (_("Pixel Location"));
  gtk_widget_ref (label44);
  gtk_object_set_data_full (GTK_OBJECT (main), "label44", label44,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table8), label44, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label44), 7.45058e-09, 0.5);

  label45 = gtk_label_new (_("Relative to Bit Name"));
  gtk_widget_ref (label45);
  gtk_object_set_data_full (GTK_OBJECT (main), "label45", label45,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table8), label45, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label45), 7.45058e-09, 0.5);

  label46 = gtk_label_new (_("Relative Location"));
  gtk_widget_ref (label46);
  gtk_object_set_data_full (GTK_OBJECT (main), "label46", label46,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table8), label46, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label46), 7.45058e-09, 0.5);

  label47 = gtk_label_new (_("Relative Pre-Adjust"));
  gtk_widget_ref (label47);
  gtk_object_set_data_full (GTK_OBJECT (main), "label47", label47,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table8), label47, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label47), 7.45058e-09, 0.5);

  label6 = gtk_label_new (_("Bottom Right"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (main), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (properties), gtk_notebook_get_nth_page (GTK_NOTEBOOK (properties), 1), label6);

  table4 = gtk_table_new (5, 3, FALSE);
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (main), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (properties), table4);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 2);

  label21 = gtk_label_new (_("Horizontal"));
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (main), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table4), label21, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label22 = gtk_label_new (_("Vertical"));
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (main), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table4), label22, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  content_alignment_h_adj = gtk_adjustment_new (0, 0, 100, 0.1, 10, 10);
  content_alignment_h = gtk_spin_button_new (GTK_ADJUSTMENT (content_alignment_h_adj), 1, 1);
  gtk_widget_ref (content_alignment_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "content_alignment_h", content_alignment_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (content_alignment_h);
  gtk_table_attach (GTK_TABLE (table4), content_alignment_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  content_alignment_v_adj = gtk_adjustment_new (0, 0, 100, 0.1, 10, 10);
  content_alignment_v = gtk_spin_button_new (GTK_ADJUSTMENT (content_alignment_v_adj), 1, 1);
  gtk_widget_ref (content_alignment_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "content_alignment_v", content_alignment_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (content_alignment_v);
  gtk_table_attach (GTK_TABLE (table4), content_alignment_v, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  aspect_h_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  aspect_h = gtk_spin_button_new (GTK_ADJUSTMENT (aspect_h_adj), 1, 0);
  gtk_widget_ref (aspect_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "aspect_h", aspect_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (aspect_h);
  gtk_table_attach (GTK_TABLE (table4), aspect_h, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  aspect_v_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  aspect_v = gtk_spin_button_new (GTK_ADJUSTMENT (aspect_v_adj), 1, 0);
  gtk_widget_ref (aspect_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "aspect_v", aspect_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (aspect_v);
  gtk_table_attach (GTK_TABLE (table4), aspect_v, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator2);
  gtk_object_set_data_full (GTK_OBJECT (main), "hseparator2", hseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator2);
  gtk_table_attach (GTK_TABLE (table4), hseparator2, 0, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  aspect = gtk_check_button_new_with_label (_("Retain Aspect Ratio"));
  gtk_widget_ref (aspect);
  gtk_object_set_data_full (GTK_OBJECT (main), "aspect", aspect,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (aspect);
  gtk_table_attach (GTK_TABLE (table4), aspect, 0, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label23 = gtk_label_new (_("Aspect Ratio"));
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (main), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table4), label23, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 7.45058e-09, 0.5);

  label20 = gtk_label_new (_("Content Alignment"));
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (main), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table4), label20, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 7.45058e-09, 0.5);

  label7 = gtk_label_new (_("Misc"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (main), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (properties), gtk_notebook_get_nth_page (GTK_NOTEBOOK (properties), 2), label7);

  table3 = gtk_table_new (7, 3, FALSE);
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (main), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (properties), table3);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 2);

  label15 = gtk_label_new (_("Horizontal"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (main), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table3), label15, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label16 = gtk_label_new (_("Vertical"));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (main), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table3), label16, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  min_h_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  min_h = gtk_spin_button_new (GTK_ADJUSTMENT (min_h_adj), 1, 0);
  gtk_widget_ref (min_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "min_h", min_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (min_h);
  gtk_table_attach (GTK_TABLE (table3), min_h, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  min_v_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  min_v = gtk_spin_button_new (GTK_ADJUSTMENT (min_v_adj), 1, 0);
  gtk_widget_ref (min_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "min_v", min_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (min_v);
  gtk_table_attach (GTK_TABLE (table3), min_v, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  max_h_adj = gtk_adjustment_new (99999, 0, 99999, 1, 10, 10);
  max_h = gtk_spin_button_new (GTK_ADJUSTMENT (max_h_adj), 1, 0);
  gtk_widget_ref (max_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "max_h", max_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (max_h);
  gtk_table_attach (GTK_TABLE (table3), max_h, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  max_v_adj = gtk_adjustment_new (99999, 0, 99999, 1, 10, 10);
  max_v = gtk_spin_button_new (GTK_ADJUSTMENT (max_v_adj), 1, 0);
  gtk_widget_ref (max_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "max_v", max_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (max_v);
  gtk_table_attach (GTK_TABLE (table3), max_v, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  step_h_adj = gtk_adjustment_new (1, 1, 99999, 1, 10, 10);
  step_h = gtk_spin_button_new (GTK_ADJUSTMENT (step_h_adj), 1, 0);
  gtk_widget_ref (step_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "step_h", step_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (step_h);
  gtk_table_attach (GTK_TABLE (table3), step_h, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  step_v_adj = gtk_adjustment_new (1, 1, 99999, 1, 10, 10);
  step_v = gtk_spin_button_new (GTK_ADJUSTMENT (step_v_adj), 1, 0);
  gtk_widget_ref (step_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "step_v", step_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (step_v);
  gtk_table_attach (GTK_TABLE (table3), step_v, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  use_contents_h = gtk_check_button_new_with_label (_("Use Horizontal Size of Contents"));
  gtk_widget_ref (use_contents_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "use_contents_h", use_contents_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (use_contents_h);
  gtk_table_attach (GTK_TABLE (table3), use_contents_h, 0, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  use_contents_v = gtk_check_button_new_with_label (_("Use Vertical Size of Contents"));
  gtk_widget_ref (use_contents_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "use_contents_v", use_contents_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (use_contents_v);
  gtk_table_attach (GTK_TABLE (table3), use_contents_v, 0, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (main), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_table_attach (GTK_TABLE (table3), hseparator1, 0, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label17 = gtk_label_new (_("Min"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (main), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table3), label17, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 7.45058e-09, 0.5);

  label18 = gtk_label_new (_("Max"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (main), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table3), label18, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 7.45058e-09, 0.5);

  label19 = gtk_label_new (_("Stepping"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (main), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table3), label19, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 7.45058e-09, 0.5);

  label8 = gtk_label_new (_("Size"));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (main), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (properties), gtk_notebook_get_nth_page (GTK_NOTEBOOK (properties), 3), label8);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (main), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (properties), scrolledwindow4);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow4), 4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  sync_list = gtk_clist_new (1);
  gtk_widget_ref (sync_list);
  gtk_object_set_data_full (GTK_OBJECT (main), "sync_list", sync_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sync_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), sync_list);
  gtk_clist_set_column_width (GTK_CLIST (sync_list), 0, 80);
  gtk_clist_set_selection_mode (GTK_CLIST (sync_list), GTK_SELECTION_MULTIPLE);
  gtk_clist_column_titles_show (GTK_CLIST (sync_list));

  label14 = gtk_label_new (_("Propagate state to selected bits"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (main), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_clist_set_column_widget (GTK_CLIST (sync_list), 0, label14);

  label9 = gtk_label_new (_("State Sync"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (main), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (properties), gtk_notebook_get_nth_page (GTK_NOTEBOOK (properties), 4), label9);

  table2 = gtk_table_new (3, 2, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (main), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (properties), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 2);

  name = gtk_entry_new ();
  gtk_widget_ref (name);
  gtk_object_set_data_full (GTK_OBJECT (main), "name", name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (name);
  gtk_table_attach (GTK_TABLE (table2), name, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  class_combo = gtk_combo_new ();
  gtk_widget_ref (class_combo);
  gtk_object_set_data_full (GTK_OBJECT (main), "class_combo", class_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (class_combo);
  gtk_table_attach (GTK_TABLE (table2), class_combo, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  class_combo_items = g_list_append (class_combo_items, _("Decoration"));
  class_combo_items = g_list_append (class_combo_items, _("Title_Bar"));
  class_combo_items = g_list_append (class_combo_items, _("Close"));
  class_combo_items = g_list_append (class_combo_items, _("Iconify"));
  class_combo_items = g_list_append (class_combo_items, _("Raise"));
  class_combo_items = g_list_append (class_combo_items, _("Lower"));
  class_combo_items = g_list_append (class_combo_items, _("Raise_Lower"));
  class_combo_items = g_list_append (class_combo_items, _("Max_Size"));
  class_combo_items = g_list_append (class_combo_items, _("Full_Screen"));
  class_combo_items = g_list_append (class_combo_items, _("Shade"));
  class_combo_items = g_list_append (class_combo_items, _("Menu"));
  class_combo_items = g_list_append (class_combo_items, _("Resize"));
  class_combo_items = g_list_append (class_combo_items, _("Resize_Horizontal"));
  class_combo_items = g_list_append (class_combo_items, _("Resize_Vertical"));
  class_combo_items = g_list_append (class_combo_items, _("Icon"));
  class_combo_items = g_list_append (class_combo_items, _("State"));
  class_combo_items = g_list_append (class_combo_items, _("Load"));
  class_combo_items = g_list_append (class_combo_items, _("Geometry"));
  class_combo_items = g_list_append (class_combo_items, _("Scrollbar_Trough"));
  class_combo_items = g_list_append (class_combo_items, _("Scrollbar_Bar"));
  class_combo_items = g_list_append (class_combo_items, _("Scrollbar_Arrow1"));
  class_combo_items = g_list_append (class_combo_items, _("Scrollbar_Arrow2"));
  gtk_combo_set_popdown_strings (GTK_COMBO (class_combo), class_combo_items);
  g_list_free (class_combo_items);

  class = GTK_COMBO (class_combo)->entry;
  gtk_widget_ref (class);
  gtk_object_set_data_full (GTK_OBJECT (main), "class", class,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (class);
  gtk_entry_set_editable (GTK_ENTRY (class), FALSE);
  gtk_entry_set_text (GTK_ENTRY (class), _("Decoration"));

  label11 = gtk_label_new (_("Name"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (main), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table2), label11, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 7.45058e-09, 0.5);

  label12 = gtk_label_new (_("Class"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (main), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table2), label12, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 7.45058e-09, 0.5);

  label13 = gtk_label_new (_("Type"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (main), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table2), label13, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 7.45058e-09, 0.5);

  type = gtk_option_menu_new ();
  gtk_widget_ref (type);
  gtk_object_set_data_full (GTK_OBJECT (main), "type", type,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (type);
  gtk_table_attach (GTK_TABLE (table2), type, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  type_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Image"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Text"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Icon"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (type_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Hidden"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (type_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (type), type_menu);

  label10 = gtk_label_new (_("Properties"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (main), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (properties), gtk_notebook_get_nth_page (GTK_NOTEBOOK (properties), 5), label10);

  table7 = gtk_table_new (7, 5, FALSE);
  gtk_widget_ref (table7);
  gtk_object_set_data_full (GTK_OBJECT (main), "table7", table7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table7);
  gtk_container_add (GTK_CONTAINER (properties), table7);
  gtk_container_set_border_width (GTK_CONTAINER (table7), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table7), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table7), 2);

  border_l_adj = gtk_adjustment_new (0, 0, 99999, 1, 10, 10);
  border_l = gtk_spin_button_new (GTK_ADJUSTMENT (border_l_adj), 1, 0);
  gtk_widget_ref (border_l);
  gtk_object_set_data_full (GTK_OBJECT (main), "border_l", border_l,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (border_l);
  gtk_table_attach (GTK_TABLE (table7), border_l, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  border_r_adj = gtk_adjustment_new (0, 0, 99999, 1, 10, 10);
  border_r = gtk_spin_button_new (GTK_ADJUSTMENT (border_r_adj), 1, 0);
  gtk_widget_ref (border_r);
  gtk_object_set_data_full (GTK_OBJECT (main), "border_r", border_r,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (border_r);
  gtk_table_attach (GTK_TABLE (table7), border_r, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  border_t_adj = gtk_adjustment_new (0, 0, 99999, 1, 10, 10);
  border_t = gtk_spin_button_new (GTK_ADJUSTMENT (border_t_adj), 1, 0);
  gtk_widget_ref (border_t);
  gtk_object_set_data_full (GTK_OBJECT (main), "border_t", border_t,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (border_t);
  gtk_table_attach (GTK_TABLE (table7), border_t, 3, 4, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  border_b_adj = gtk_adjustment_new (0, 0, 99999, 1, 10, 10);
  border_b = gtk_spin_button_new (GTK_ADJUSTMENT (border_b_adj), 1, 0);
  gtk_widget_ref (border_b);
  gtk_object_set_data_full (GTK_OBJECT (main), "border_b", border_b,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (border_b);
  gtk_table_attach (GTK_TABLE (table7), border_b, 4, 5, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator7);
  gtk_object_set_data_full (GTK_OBJECT (main), "hseparator7", hseparator7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator7);
  gtk_table_attach (GTK_TABLE (table7), hseparator7, 0, 5, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  img_normal = gtk_entry_new ();
  gtk_widget_ref (img_normal);
  gtk_object_set_data_full (GTK_OBJECT (main), "img_normal", img_normal,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_normal);
  gtk_table_attach (GTK_TABLE (table7), img_normal, 1, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  img_hilited = gtk_entry_new ();
  gtk_widget_ref (img_hilited);
  gtk_object_set_data_full (GTK_OBJECT (main), "img_hilited", img_hilited,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_hilited);
  gtk_table_attach (GTK_TABLE (table7), img_hilited, 1, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  img_clicked = gtk_entry_new ();
  gtk_widget_ref (img_clicked);
  gtk_object_set_data_full (GTK_OBJECT (main), "img_clicked", img_clicked,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_clicked);
  gtk_table_attach (GTK_TABLE (table7), img_clicked, 1, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  img_disabled = gtk_entry_new ();
  gtk_widget_ref (img_disabled);
  gtk_object_set_data_full (GTK_OBJECT (main), "img_disabled", img_disabled,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (img_disabled);
  gtk_table_attach (GTK_TABLE (table7), img_disabled, 1, 4, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label61 = gtk_label_new (_("Horizontal"));
  gtk_widget_ref (label61);
  gtk_object_set_data_full (GTK_OBJECT (main), "label61", label61,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label61);
  gtk_table_attach (GTK_TABLE (table7), label61, 1, 2, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label62 = gtk_label_new (_("Vertical"));
  gtk_widget_ref (label62);
  gtk_object_set_data_full (GTK_OBJECT (main), "label62", label62,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label62);
  gtk_table_attach (GTK_TABLE (table7), label62, 3, 4, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label37 = gtk_label_new (_("Normal"));
  gtk_widget_ref (label37);
  gtk_object_set_data_full (GTK_OBJECT (main), "label37", label37,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table7), label37, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 7.45058e-09, 0.5);

  label38 = gtk_label_new (_("Hilited"));
  gtk_widget_ref (label38);
  gtk_object_set_data_full (GTK_OBJECT (main), "label38", label38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table7), label38, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 7.45058e-09, 0.5);

  label39 = gtk_label_new (_("Clicked"));
  gtk_widget_ref (label39);
  gtk_object_set_data_full (GTK_OBJECT (main), "label39", label39,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table7), label39, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label39), 7.45058e-09, 0.5);

  label40 = gtk_label_new (_("Disabled"));
  gtk_widget_ref (label40);
  gtk_object_set_data_full (GTK_OBJECT (main), "label40", label40,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table7), label40, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label40), 7.45058e-09, 0.5);

  label41 = gtk_label_new (_("Border Scaling"));
  gtk_widget_ref (label41);
  gtk_object_set_data_full (GTK_OBJECT (main), "label41", label41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label41);
  gtk_table_attach (GTK_TABLE (table7), label41, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label41), 7.45058e-09, 0.5);

  label60 = gtk_label_new (_("Image Fill"));
  gtk_widget_ref (label60);
  gtk_object_set_data_full (GTK_OBJECT (main), "label60", label60,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label60);
  gtk_table_attach (GTK_TABLE (table7), label60, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label60), 7.45058e-09, 0.5);

  tile_h_combo = gtk_combo_new ();
  gtk_widget_ref (tile_h_combo);
  gtk_object_set_data_full (GTK_OBJECT (main), "tile_h_combo", tile_h_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tile_h_combo);
  gtk_table_attach (GTK_TABLE (table7), tile_h_combo, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (tile_h_combo, 52, -2);
  gtk_combo_set_value_in_list (GTK_COMBO (tile_h_combo), TRUE, TRUE);
  tile_h_combo_items = g_list_append (tile_h_combo_items, _("Fill"));
  tile_h_combo_items = g_list_append (tile_h_combo_items, _("Tile"));
  tile_h_combo_items = g_list_append (tile_h_combo_items, _("Tile Integer"));
  gtk_combo_set_popdown_strings (GTK_COMBO (tile_h_combo), tile_h_combo_items);
  g_list_free (tile_h_combo_items);

  tile_h = GTK_COMBO (tile_h_combo)->entry;
  gtk_widget_ref (tile_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "tile_h", tile_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tile_h);
  gtk_entry_set_editable (GTK_ENTRY (tile_h), FALSE);
  gtk_entry_set_text (GTK_ENTRY (tile_h), _("Fill"));

  tile_v_combo = gtk_combo_new ();
  gtk_widget_ref (tile_v_combo);
  gtk_object_set_data_full (GTK_OBJECT (main), "tile_v_combo", tile_v_combo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tile_v_combo);
  gtk_table_attach (GTK_TABLE (table7), tile_v_combo, 4, 5, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (tile_v_combo, 52, -2);
  gtk_combo_set_value_in_list (GTK_COMBO (tile_v_combo), TRUE, TRUE);
  tile_v_combo_items = g_list_append (tile_v_combo_items, _("Fill"));
  tile_v_combo_items = g_list_append (tile_v_combo_items, _("Tile"));
  tile_v_combo_items = g_list_append (tile_v_combo_items, _("Tile Integer"));
  gtk_combo_set_popdown_strings (GTK_COMBO (tile_v_combo), tile_v_combo_items);
  g_list_free (tile_v_combo_items);

  tile_v = GTK_COMBO (tile_v_combo)->entry;
  gtk_widget_ref (tile_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "tile_v", tile_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tile_v);
  gtk_entry_set_editable (GTK_ENTRY (tile_v), FALSE);
  gtk_entry_set_text (GTK_ENTRY (tile_v), _("Fill"));

  browse_clicked = gtk_button_new_with_label (_("Browse..."));
  gtk_widget_ref (browse_clicked);
  gtk_object_set_data_full (GTK_OBJECT (main), "browse_clicked", browse_clicked,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (browse_clicked);
  gtk_table_attach (GTK_TABLE (table7), browse_clicked, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  borwse_hilited = gtk_button_new_with_label (_("Browse..."));
  gtk_widget_ref (borwse_hilited);
  gtk_object_set_data_full (GTK_OBJECT (main), "borwse_hilited", borwse_hilited,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (borwse_hilited);
  gtk_table_attach (GTK_TABLE (table7), borwse_hilited, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse_normal = gtk_button_new_with_label (_("Browse..."));
  gtk_widget_ref (browse_normal);
  gtk_object_set_data_full (GTK_OBJECT (main), "browse_normal", browse_normal,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (browse_normal);
  gtk_table_attach (GTK_TABLE (table7), browse_normal, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browse_disabled = gtk_button_new_with_label (_("Browse..."));
  gtk_widget_ref (browse_disabled);
  gtk_object_set_data_full (GTK_OBJECT (main), "browse_disabled", browse_disabled,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (browse_disabled);
  gtk_table_attach (GTK_TABLE (table7), browse_disabled, 4, 5, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label36 = gtk_label_new (_("Image"));
  gtk_widget_ref (label36);
  gtk_object_set_data_full (GTK_OBJECT (main), "label36", label36,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label36);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (properties), gtk_notebook_get_nth_page (GTK_NOTEBOOK (properties), 6), label36);

  table9 = gtk_table_new (5, 5, FALSE);
  gtk_widget_ref (table9);
  gtk_object_set_data_full (GTK_OBJECT (main), "table9", table9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table9);
  gtk_container_add (GTK_CONTAINER (properties), table9);
  gtk_container_set_border_width (GTK_CONTAINER (table9), 4);
  gtk_table_set_row_spacings (GTK_TABLE (table9), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table9), 2);

  bit_pad_l_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  bit_pad_l = gtk_spin_button_new (GTK_ADJUSTMENT (bit_pad_l_adj), 1, 0);
  gtk_widget_ref (bit_pad_l);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_pad_l", bit_pad_l,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_pad_l);
  gtk_table_attach (GTK_TABLE (table9), bit_pad_l, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bit_min_h_adj = gtk_adjustment_new (0, 0, 9999, 1, 10, 10);
  bit_min_h = gtk_spin_button_new (GTK_ADJUSTMENT (bit_min_h_adj), 1, 0);
  gtk_widget_ref (bit_min_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_min_h", bit_min_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_min_h);
  gtk_table_attach (GTK_TABLE (table9), bit_min_h, 1, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bit_min_v_adj = gtk_adjustment_new (0, 0, 9999, 1, 10, 10);
  bit_min_v = gtk_spin_button_new (GTK_ADJUSTMENT (bit_min_v_adj), 1, 0);
  gtk_widget_ref (bit_min_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_min_v", bit_min_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_min_v);
  gtk_table_attach (GTK_TABLE (table9), bit_min_v, 3, 5, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bit_max_h_adj = gtk_adjustment_new (0, 0, 9999, 1, 10, 10);
  bit_max_h = gtk_spin_button_new (GTK_ADJUSTMENT (bit_max_h_adj), 1, 0);
  gtk_widget_ref (bit_max_h);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_max_h", bit_max_h,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_max_h);
  gtk_table_attach (GTK_TABLE (table9), bit_max_h, 1, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bit_max_v_adj = gtk_adjustment_new (0, 0, 99999, 1, 10, 10);
  bit_max_v = gtk_spin_button_new (GTK_ADJUSTMENT (bit_max_v_adj), 1, 0);
  gtk_widget_ref (bit_max_v);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_max_v", bit_max_v,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_max_v);
  gtk_table_attach (GTK_TABLE (table9), bit_max_v, 3, 5, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label53 = gtk_label_new (_("Horizontal"));
  gtk_widget_ref (label53);
  gtk_object_set_data_full (GTK_OBJECT (main), "label53", label53,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label53);
  gtk_table_attach (GTK_TABLE (table9), label53, 1, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label54 = gtk_label_new (_("Vertical"));
  gtk_widget_ref (label54);
  gtk_object_set_data_full (GTK_OBJECT (main), "label54", label54,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table9), label54, 3, 5, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  bit_pad_r_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  bit_pad_r = gtk_spin_button_new (GTK_ADJUSTMENT (bit_pad_r_adj), 1, 0);
  gtk_widget_ref (bit_pad_r);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_pad_r", bit_pad_r,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_pad_r);
  gtk_table_attach (GTK_TABLE (table9), bit_pad_r, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bit_pad_t_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  bit_pad_t = gtk_spin_button_new (GTK_ADJUSTMENT (bit_pad_t_adj), 1, 0);
  gtk_widget_ref (bit_pad_t);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_pad_t", bit_pad_t,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_pad_t);
  gtk_table_attach (GTK_TABLE (table9), bit_pad_t, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bit_pad_b_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  bit_pad_b = gtk_spin_button_new (GTK_ADJUSTMENT (bit_pad_b_adj), 1, 0);
  gtk_widget_ref (bit_pad_b);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_pad_b", bit_pad_b,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_pad_b);
  gtk_table_attach (GTK_TABLE (table9), bit_pad_b, 4, 5, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bit_inset_l_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  bit_inset_l = gtk_spin_button_new (GTK_ADJUSTMENT (bit_inset_l_adj), 1, 0);
  gtk_widget_ref (bit_inset_l);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_inset_l", bit_inset_l,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_inset_l);
  gtk_table_attach (GTK_TABLE (table9), bit_inset_l, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bit_inset_r_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  bit_inset_r = gtk_spin_button_new (GTK_ADJUSTMENT (bit_inset_r_adj), 1, 0);
  gtk_widget_ref (bit_inset_r);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_inset_r", bit_inset_r,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_inset_r);
  gtk_table_attach (GTK_TABLE (table9), bit_inset_r, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bit_inset_t_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  bit_inset_t = gtk_spin_button_new (GTK_ADJUSTMENT (bit_inset_t_adj), 1, 0);
  gtk_widget_ref (bit_inset_t);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_inset_t", bit_inset_t,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_inset_t);
  gtk_table_attach (GTK_TABLE (table9), bit_inset_t, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bit_inset_b_adj = gtk_adjustment_new (0, -99999, 99999, 1, 10, 10);
  bit_inset_b = gtk_spin_button_new (GTK_ADJUSTMENT (bit_inset_b_adj), 1, 0);
  gtk_widget_ref (bit_inset_b);
  gtk_object_set_data_full (GTK_OBJECT (main), "bit_inset_b", bit_inset_b,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bit_inset_b);
  gtk_table_attach (GTK_TABLE (table9), bit_inset_b, 4, 5, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label55 = gtk_label_new (_("Min Size"));
  gtk_widget_ref (label55);
  gtk_object_set_data_full (GTK_OBJECT (main), "label55", label55,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label55);
  gtk_table_attach (GTK_TABLE (table9), label55, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label55), 7.45058e-09, 0.5);

  label56 = gtk_label_new (_("Max Size"));
  gtk_widget_ref (label56);
  gtk_object_set_data_full (GTK_OBJECT (main), "label56", label56,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label56);
  gtk_table_attach (GTK_TABLE (table9), label56, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label56), 7.45058e-09, 0.5);

  label57 = gtk_label_new (_("Padding"));
  gtk_widget_ref (label57);
  gtk_object_set_data_full (GTK_OBJECT (main), "label57", label57,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label57);
  gtk_table_attach (GTK_TABLE (table9), label57, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label57), 7.45058e-09, 0.5);

  label58 = gtk_label_new (_("Insets"));
  gtk_widget_ref (label58);
  gtk_object_set_data_full (GTK_OBJECT (main), "label58", label58,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label58);
  gtk_table_attach (GTK_TABLE (table9), label58, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label58), 7.45058e-09, 0.5);

  label52 = gtk_label_new (_("Bit"));
  gtk_widget_ref (label52);
  gtk_object_set_data_full (GTK_OBJECT (main), "label52", label52,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label52);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (properties), gtk_notebook_get_nth_page (GTK_NOTEBOOK (properties), 7), label52);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (main), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (main), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_table_attach (GTK_TABLE (table1), frame1, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 2);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_IN);

  zoom = gtk_drawing_area_new ();
  gtk_widget_ref (zoom);
  gtk_object_set_data_full (GTK_OBJECT (main), "zoom", zoom,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (zoom);
  gtk_container_add (GTK_CONTAINER (frame1), zoom);
  gtk_widget_set_usize (zoom, 80, 80);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (main), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_table_attach (GTK_TABLE (table1), notebook1, 2, 3, 0, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_usize (notebook1, 150, -2);
  gtk_container_set_border_width (GTK_CONTAINER (notebook1), 2);
  gtk_notebook_set_tab_hborder (GTK_NOTEBOOK (notebook1), 0);
  gtk_notebook_set_tab_vborder (GTK_NOTEBOOK (notebook1), 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (main), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow3);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow3), 4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  images = gtk_clist_new (1);
  gtk_widget_ref (images);
  gtk_object_set_data_full (GTK_OBJECT (main), "images", images,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (images);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), images);
  gtk_clist_set_column_width (GTK_CLIST (images), 0, 80);
  gtk_clist_set_selection_mode (GTK_CLIST (images), GTK_SELECTION_BROWSE);
  gtk_clist_column_titles_hide (GTK_CLIST (images));

  label1 = gtk_label_new (_("Images"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (main), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (main), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow2);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow2), 4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  states = gtk_clist_new (1);
  gtk_widget_ref (states);
  gtk_object_set_data_full (GTK_OBJECT (main), "states", states,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (states);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), states);
  gtk_clist_set_column_width (GTK_CLIST (states), 0, 80);
  gtk_clist_set_selection_mode (GTK_CLIST (states), GTK_SELECTION_BROWSE);
  gtk_clist_column_titles_hide (GTK_CLIST (states));

  label2 = gtk_label_new (_("States"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (main), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (main), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_table_attach (GTK_TABLE (table1), hbox1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  file = gtk_entry_new ();
  gtk_widget_ref (file);
  gtk_object_set_data_full (GTK_OBJECT (main), "file", file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file);
  gtk_box_pack_start (GTK_BOX (hbox1), file, TRUE, TRUE, 0);
  gtk_widget_set_usize (file, 110, -2);
  gtk_entry_set_text (GTK_ENTRY (file), _("new_bits.db"));

  label48 = gtk_label_new (_("X"));
  gtk_widget_ref (label48);
  gtk_object_set_data_full (GTK_OBJECT (main), "label48", label48,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox1), label48, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label48), 2, 0);

  x = gtk_entry_new ();
  gtk_widget_ref (x);
  gtk_object_set_data_full (GTK_OBJECT (main), "x", x,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (x);
  gtk_box_pack_start (GTK_BOX (hbox1), x, TRUE, TRUE, 0);
  gtk_widget_set_usize (x, 40, -2);

  label49 = gtk_label_new (_("Y"));
  gtk_widget_ref (label49);
  gtk_object_set_data_full (GTK_OBJECT (main), "label49", label49,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox1), label49, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label49), 2, 0);

  y = gtk_entry_new ();
  gtk_widget_ref (y);
  gtk_object_set_data_full (GTK_OBJECT (main), "y", y,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (y);
  gtk_box_pack_start (GTK_BOX (hbox1), y, TRUE, TRUE, 0);
  gtk_widget_set_usize (y, 40, -2);

  label50 = gtk_label_new (_("Width"));
  gtk_widget_ref (label50);
  gtk_object_set_data_full (GTK_OBJECT (main), "label50", label50,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox1), label50, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label50), 2, 0);

  width = gtk_entry_new ();
  gtk_widget_ref (width);
  gtk_object_set_data_full (GTK_OBJECT (main), "width", width,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (width);
  gtk_box_pack_start (GTK_BOX (hbox1), width, TRUE, TRUE, 0);
  gtk_widget_set_usize (width, 40, -2);

  label51 = gtk_label_new (_("Height"));
  gtk_widget_ref (label51);
  gtk_object_set_data_full (GTK_OBJECT (main), "label51", label51,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox1), label51, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label51), 2, 0);

  height = gtk_entry_new ();
  gtk_widget_ref (height);
  gtk_object_set_data_full (GTK_OBJECT (main), "height", height,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (height);
  gtk_box_pack_start (GTK_BOX (hbox1), height, TRUE, TRUE, 0);
  gtk_widget_set_usize (height, 40, -2);

  gtk_signal_connect (GTK_OBJECT (main), "delete_event",
                      GTK_SIGNAL_FUNC (on_main_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (open1), "activate",
                      GTK_SIGNAL_FUNC (on_open1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save1), "activate",
                      GTK_SIGNAL_FUNC (on_save1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save_as1), "activate",
                      GTK_SIGNAL_FUNC (on_save_as1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (preferences1), "activate",
                      GTK_SIGNAL_FUNC (on_preferences1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit1), "activate",
                      GTK_SIGNAL_FUNC (on_exit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (delete1), "activate",
                      GTK_SIGNAL_FUNC (on_delete1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_about1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (view), "button_press_event",
                      GTK_SIGNAL_FUNC (on_view_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (view), "button_release_event",
                      GTK_SIGNAL_FUNC (on_view_button_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (view), "expose_event",
                      GTK_SIGNAL_FUNC (on_view_expose_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (view), "motion_notify_event",
                      GTK_SIGNAL_FUNC (on_view_motion_notify_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (view), "configure_event",
                      GTK_SIGNAL_FUNC (on_view_configure_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (view), "enter_notify_event",
                      GTK_SIGNAL_FUNC (on_view_enter_notify_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (view), "leave_notify_event",
                      GTK_SIGNAL_FUNC (on_view_leave_notify_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (new_image), "clicked",
                      GTK_SIGNAL_FUNC (on_new_image_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (new_icon), "clicked",
                      GTK_SIGNAL_FUNC (on_new_icon_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (new_text), "clicked",
                      GTK_SIGNAL_FUNC (on_new_text_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (raise), "clicked",
                      GTK_SIGNAL_FUNC (on_raise_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (lower), "clicked",
                      GTK_SIGNAL_FUNC (on_lower_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (delete), "clicked",
                      GTK_SIGNAL_FUNC (on_delete_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (reset), "clicked",
                      GTK_SIGNAL_FUNC (on_reset_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (prop_apply), "clicked",
                      GTK_SIGNAL_FUNC (on_prop_apply_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (prop_reset), "clicked",
                      GTK_SIGNAL_FUNC (on_prop_reset_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (draft), "toggled",
                      GTK_SIGNAL_FUNC (on_draft_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (zoom), "expose_event",
                      GTK_SIGNAL_FUNC (on_zoom_expose_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (zoom), "configure_event",
                      GTK_SIGNAL_FUNC (on_zoom_configure_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (images), "select_row",
                      GTK_SIGNAL_FUNC (on_images_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (states), "select_row",
                      GTK_SIGNAL_FUNC (on_states_select_row),
                      NULL);

  return main;
}

GtkWidget*
create_filesel (void)
{
  GtkWidget *filesel;
  GtkWidget *file_ok;
  GtkWidget *file_cancel;

  filesel = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (filesel), "filesel", filesel);
  gtk_container_set_border_width (GTK_CONTAINER (filesel), 10);
  gtk_window_set_position (GTK_WINDOW (filesel), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (filesel), TRUE);
  gtk_window_set_wmclass (GTK_WINDOW (filesel), "Filesel", "Etcher");

  file_ok = GTK_FILE_SELECTION (filesel)->ok_button;
  gtk_object_set_data (GTK_OBJECT (filesel), "file_ok", file_ok);
  gtk_widget_show (file_ok);
  GTK_WIDGET_SET_FLAGS (file_ok, GTK_CAN_DEFAULT);

  file_cancel = GTK_FILE_SELECTION (filesel)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (filesel), "file_cancel", file_cancel);
  gtk_widget_show (file_cancel);
  GTK_WIDGET_SET_FLAGS (file_cancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (filesel), "delete_event",
                      GTK_SIGNAL_FUNC (on_filesel_delete_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (file_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_file_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (file_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_file_cancel_clicked),
                      NULL);

  return filesel;
}

GtkWidget*
create_render_method (void)
{
  GtkWidget *render_method;
  GtkWidget *dialog_vbox1;
  GtkWidget *frame2;
  GtkWidget *label59;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox2;
  GtkWidget *software;
  GtkWidget *_3d_hardware;

  render_method = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (render_method), "render_method", render_method);
  gtk_window_set_title (GTK_WINDOW (render_method), _("Select your display method"));
  GTK_WINDOW (render_method)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (render_method), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (render_method), TRUE);
  gtk_window_set_policy (GTK_WINDOW (render_method), FALSE, TRUE, TRUE);
  gtk_window_set_wmclass (GTK_WINDOW (render_method), "Etcher", "Dialog");

  dialog_vbox1 = GTK_DIALOG (render_method)->vbox;
  gtk_object_set_data (GTK_OBJECT (render_method), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (render_method), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), frame2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 8);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_IN);

  label59 = gtk_label_new (_("Please select your preferred canvas display method.\n\nWARNING! 3D Accelerated Display may be VERY SLOW\nif your installation of OpenGL does not support 3D Hardware\nacceleration (i.e. it only does software rendering). If that is\nthe case choose software rendering."));
  gtk_widget_ref (label59);
  gtk_object_set_data_full (GTK_OBJECT (render_method), "label59", label59,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label59);
  gtk_container_add (GTK_CONTAINER (frame2), label59);
  gtk_misc_set_padding (GTK_MISC (label59), 10, 10);

  dialog_action_area1 = GTK_DIALOG (render_method)->action_area;
  gtk_object_set_data (GTK_OBJECT (render_method), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (render_method), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox2, TRUE, TRUE, 0);

  software = gtk_button_new_with_label (_("Software"));
  gtk_widget_ref (software);
  gtk_object_set_data_full (GTK_OBJECT (render_method), "software", software,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (software);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), software);
  GTK_WIDGET_SET_FLAGS (software, GTK_CAN_DEFAULT);

  _3d_hardware = gtk_button_new_with_label (_("3D Hardware"));
  gtk_widget_ref (_3d_hardware);
  gtk_object_set_data_full (GTK_OBJECT (render_method), "_3d_hardware", _3d_hardware,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (_3d_hardware);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), _3d_hardware);
  GTK_WIDGET_SET_FLAGS (_3d_hardware, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (software), "clicked",
                      GTK_SIGNAL_FUNC (on_software_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (_3d_hardware), "clicked",
                      GTK_SIGNAL_FUNC (on_3d_hardware_clicked),
                      NULL);

  return render_method;
}

