/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main (void);
GtkWidget* create_filesel (void);
GtkWidget* create_render_method (void);
GtkWidget* create_preferences (void);
