
/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget      *create_toplevel(void);
GtkWidget      *create_filesel(void);
GtkWidget      *create_render_method(void);
GtkWidget      *create_preferences(void);
GtkWidget      *create_add_state(void);
