/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.in by autoheader.  */
/* #undef ENABLE_NLS */
/* #undef HAVE_CATGETS */
/* #undef HAVE_GETTEXT */
/* #undef HAVE_LC_MESSAGES */
/* #undef HAVE_SHADOW */
/* #undef HAVE_STPCPY */
/* #undef HAVE_LIBSM */
/* #undef HAVE_PAM */
/* #undef PACKAGE_LOCALE_DIR */
#define PACKAGE_DATA_DIR "/usr/share/erss"
#define PACKAGE_SOURCE_DIR "/usr/src/app/misc/erss"
#define PACKAGE_CFG_DIR "/usr/etc"
#define PREFIX "/usr"
/* #undef ENTRANCE_XSESSION */
/* #undef HAVE_ECORE_GL_X11 */

/* Name of package */
#define PACKAGE "erss"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.0.2"
