#! /usr/bin/env python
# -*- coding: utf-8 -*-
# encoding: utf-8
# Calaos, 2010

def build(bld):
        pass
        bld.install_files('${PREFIX}/share/eskiss/levels',
                        ['000_begin.eet',
                         '001_level.eet',
                         '002_level.eet',
                         '003_level.eet',
                         '004_level.eet',
                         '005_level.eet',
                         '006_level.eet',
                         '007_level.eet',
                         '008_level.eet',
                         '009_level.eet',
                         '010_level.eet',
                         '011_level.eet',
                        ])
