# this is ugh... not good, will change for the better soon :)

all:
	@echo "Compiling Electric Eyes 2..."
	@echo
	rm -rf ee2 core
	gcc -Wall -Wunused -O2 ee2.c -o ee2 `gtk-config --cflags` `gtk-config --libs` -lImlib2
	@echo
	@echo "Compiled... dont run make install, just ./ee2"
	@echo
	
	
