#!/usr/bin/perl

# A simple contact manager / calander for the ipaq
# Copyright 2001 Geoff 'Mandrake' Harrison <mandrake@mandrake.net>
# All Rights Reserved
# http://mandrake.net

use Gtk;
use Gtk::Atoms;
use Gtk::Keysyms;

init Gtk;

$last_row = -1;
sub exit_application {

	open TODOLIST, ">$ENV{HOME}/.contacts/todo";
	foreach(@todolist) {
		my %item = %$_;
		print TODOLIST
			"$item{text}::$item{startdate}::$item{enddate}::$item{priority}\n";
	}
	close TODOLIST;
	open NOTESFILE, ">$ENV{HOME}/.contacts/notes";
	print NOTESFILE $notes_text->get_chars(0,$notes_text->get_length);
	close NOTESFILE;
	Gtk->exit(0);
}

sub selected_contact {

	my($widget,$row,$col,$event) = @_;  

	if($last_row == $row) {
		$notebook->set_page(4);
		return;
	}
	$last_row = $row;

}

sub add_new_todo {

	$todo{text}->set_text("");
	$todo{datestart}->set_text(`date`);
	$todo{priority}->set_text("3");
	$notebook->set_page(5);
	$todo{text}->grab_focus();

}

sub add_new_todo_item {

	my %item;
	$item{text} = $todo{text}->get_text();
	$item{datestart} = $todo{datestart}->get_text();
	$item{dateend} = $todo{dateend}->get_text();
	$item{priority} = $todo{priority}->get_text();
	$item{checkbox} = new Gtk::CheckButton "$item{text}";
	$todo{vbox}->pack_start($item{checkbox},0,0,3);
	$item{checkbox}->show();
	push @todolist,\%item;

	$notebook->set_page(2);

}

sub create_contacts_page {

	my $page = new Gtk::VBox(0,0);
	
	my $scrolled_window = new Gtk::ScrolledWindow(undef,undef);
	$scrolled_window->set_policy('never','always');
	$page->pack_start($scrolled_window,1,1,0);
	$scrolled_window->show();

	my $clist = new_with_titles Gtk::CList("Name","Number");
	$scrolled_window->add($clist);
	$clist->show();
	$clist->set_selection_mode('extended');
	$clist->signal_connect('select-row',\&selected_contact);

# This is some test data

	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->append("Geoff Harrison","412-555-1212");
	$clist->columns_autosize();

# end test data

	my $hbox = new Gtk::HBox(0,0);
	$page->pack_start($hbox,0,1,0);
	$hbox->show();

	my $button = new Gtk::Button "Add";
	$hbox->pack_start($button,1,1,0);
	$button->show();

	$button = new Gtk::Button "Delete";
	$hbox->pack_start($button,1,1,0);
	$button->show();

	$button = new Gtk::Button "Prefs";
	$hbox->pack_start($button,1,1,0);
	$button->show();

	$page->show();
	return $page;
}

sub create_calendar_page {

	my $page = new Gtk::VBox(0,0);
	
	my $scrolled_window = new Gtk::ScrolledWindow(undef,undef);

	$str = `cal`;
	chomp($str);
	my $label = new Gtk::Label $str;
	$page->pack_start($label,1,1,0);
	$label->show();

	$page->show();
	return $page;
}

sub create_todo_page {

	my $page = new Gtk::VBox(0,0);
	
	my $scrolled_window = new Gtk::ScrolledWindow(undef,undef);
	$scrolled_window->set_policy('never','always');
	$page->pack_start($scrolled_window,1,1,0);
	$scrolled_window->show();

	my $vbox = new Gtk::VBox(0,0);
	$scrolled_window->add_with_viewport($vbox);
	$vbox->show();

	open TODOLIST,"$ENV{HOME}/.contacts/todo";
	while(<TODOLIST>) {
		my %todoitem;
		chomp;
		($todoitem{text},$todoitem{startdate},$todoitem{enddate},$todoitem{priority})
			= split /\:\:/;
		$todoitem{checkbox} = new Gtk::CheckButton $todoitem{text};
		$vbox->pack_start($todoitem{checkbox},0,0,3);
		$todoitem{checkbox}->can_focus(0);
		$todoitem{checkbox}->show();

		push @todolist, \%todoitem;

	}
	close TODOLIST;

	$todo{vbox} = $vbox;

	my $hbox = new Gtk::HBox(0,0);
	$page->pack_start($hbox,0,1,0);
	$hbox->show();

	my $button = new Gtk::Button "Add";
	$hbox->pack_start($button,1,1,0);
	$button->show();
	$button->signal_connect('clicked', \&add_new_todo);

	$button = new Gtk::ToggleButton "Details";
	$hbox->pack_start($button,1,1,0);
	$button->show();

	$button = new Gtk::ToggleButton "View Expired";
	$hbox->pack_start($button,1,1,0);
	$button->show();

	$page->show();
	return $page;
}

sub create_notes_page {

	my $page = new Gtk::VBox(0,0);
	
	my $scrolled_window = new Gtk::ScrolledWindow(undef,undef);
	$scrolled_window->set_policy('never','always');
	$page->pack_start($scrolled_window,1,1,0);
	$scrolled_window->show();

	$notes_text = new Gtk::Text;
	$notes_text->set_word_wrap(0);
	$notes_text->show();
	$notes_text->set_editable(1);
	$scrolled_window->add($notes_text);

	if(-e "$ENV{HOME}/.contacts/notes") {
		open NOTESFILE, "<$ENV{HOME}/.contacts/notes";
		while(<NOTESFILE>) {
			$notes_text->insert(undef,$notes_text->style->black,undef,$_);
		}
		close NOTESFILE;
	}
	$page->show();
	return $page;
}

sub create_contact_detail_page {

	my $page = new Gtk::VBox(0,0);
	
	my $scrolled_window = new Gtk::ScrolledWindow(undef,undef);
	$scrolled_window->set_policy('never','always');
	$page->pack_start($scrolled_window,1,1,0);
	$scrolled_window->show();

	my $button = new Gtk::Button "Return to Contact List";
	$page->pack_start($button,0,1,0);
	$button->show();
	$button->signal_connect('clicked', sub { $notebook->set_page(0); });

	$page->show();
	return $page;
}

sub create_new_todo_page {
	my $page = new Gtk::VBox(0,0);
	
	my $table = new Gtk::Table(2,2,0);
	$page->pack_start($table,1,1,0);
	$table->show();

	my $label = new Gtk::Label "Todo: ";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,0,1,[-fill],0,0,0);
	$label->show();

	$todo{text} = new Gtk::Entry;
	$table->attach($todo{text},1,2,0,1,[-expand,-fill],[-fill],0,0);
	$todo{text}->show();

	$label = new Gtk::Label "Date Added: ";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,1,2,[-fill],0,0,0);
	$label->show();

	$todo{datestart} = new Gtk::Entry;
	$table->attach($todo{datestart},1,2,1,2,[-expand,-fill],[-fill],0,0);
	$todo{datestart}->show();

	$label = new Gtk::Label " Date Completed: ";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,2,3,[-fill],0,0,0);
	$label->show();

	$todo{dateend} = new Gtk::Entry;
	$table->attach($todo{dateend},1,2,2,3,[-expand,-fill],[-fill],0,0);
	$todo{dateend}->show();

	$label = new Gtk::Label " Priority: ";
	$label->set_alignment(1,1);
	$table->attach($label,0,1,3,4,[-fill],0,0,0);
	$label->show();

	$todo{priority} = new Gtk::Entry;
	$table->attach($todo{priority},1,2,3,4,[-expand,-fill],[-fill],0,0);
	$todo{priority}->show();

	my $hbox = new Gtk::HBox(0,0);
	$page->pack_start($hbox,0,1,0);
	$hbox->show();

	my $button = new Gtk::Button "Add This Item";
	$hbox->pack_start($button,1,1,0);
	$button->show();
	$button->signal_connect('clicked', \&add_new_todo_item);

	$button = new Gtk::Button "Cancel";
	$hbox->pack_start($button,1,1,0);
	$button->signal_connect('clicked', sub { $notebook->set_page(2);});
	$button->show();

	$page->show();
	return $page;
}

sub create_main_window {
	my $main_vbox = new Gtk::VBox(0,0);
	$main_vbox->show();

	my $omenu = new Gtk::OptionMenu;
	my $menu  = new Gtk::Menu;

	$omenu->set_menu($menu);
	$omenu->show();
	$menu->show();

	my $menuitem = new Gtk::MenuItem("Contacts");
	$menuitem->signal_connect('activate', sub { $notebook->set_page(0); });
	$menuitem->show();
	$menu->append($menuitem);
	$omenu->set_history(0);

	$menuitem = new Gtk::MenuItem("Calendar");
	$menuitem->signal_connect('activate', sub { $notebook->set_page(1); });
	$menuitem->show();
	$menu->append($menuitem);

	$menuitem = new Gtk::MenuItem("Todo List");
	$menuitem->signal_connect('activate', sub { $notebook->set_page(2); });
	$menuitem->show();
	$menu->append($menuitem);

	$menuitem = new Gtk::MenuItem("Notes");
	$menuitem->signal_connect('activate', sub { $notebook->set_page(3);
			$notes_text->grab_focus();});
	$menuitem->show();
	$menu->append($menuitem);

	$main_vbox->pack_start($omenu,0,1,0);

	$notebook = new Gtk::Notebook;
	$notebook->append_page(create_contacts_page());
	$notebook->append_page(create_calendar_page());
	$notebook->append_page(create_todo_page());
	$notebook->append_page(create_notes_page());
	$notebook->append_page(create_contact_detail_page());
	$notebook->append_page(create_new_todo_page());
	$notebook->show();
	$notebook->set_show_border(0);
	$notebook->set_show_tabs(0);
	$main_vbox->pack_start($notebook,1,1,0);

	return $main_vbox;
}

if(!(-e "$ENV{HOME}/.contacts")) {
	mkdir "$ENV{HOME}/.contacts", 0700;
}
$main_window = new Gtk::Window '-toplevel';
$main_window->set_title("Personal Information Manager");
$main_window->set_policy(1,1,0);

$main_window->add(create_main_window());

$main_window->signal_connect('destroy',\&exit_application);
$main_window->signal_connect('delete_event',\&exit_application);

$main_window->show();

Gtk->main();
