#define EDJE_DOC                             1
#define EDJE_EMBRYO                          2
#define EDJE_COLLECTIONS                     3
#define EDJE_LB                              4
#define EDJE_RB                              5
#define EDJE_DATA                            6
#define EDJE_DOT                             7
#define EDJE_PROPERTY                        8
#define EDJE_ID                              9
#define EDJE_SEMICOLON                      10
#define EDJE_STYLES                         11
#define EDJE_STYLE                          12
#define EDJE_SET                            13
#define EDJE_IMAGE                          14
#define EDJE_EXTERNALS                      15
#define EDJE_FONTS                          16
#define EDJE_FONT                           17
#define EDJE_COLOR_CLASSES                  18
#define EDJE_COLOR_CLASS                    19
#define EDJE_PROGRAMS                       20
#define EDJE_PROGRAM                        21
#define EDJE_IMAGES                         22
#define EDJE_LOSSY                          23
#define EDJE_GROUP                          24
#define EDJE_PARTS                          25
#define EDJE_PART                           26
#define EDJE_DRAGABLE                       27
#define EDJE_DESCRIPTION                    28
#define EDJE_PARAMS                         29
#define EDJE_PERSPECTIVE                    30
#define EDJE_FILL                           31
#define EDJE_ORIGIN                         32
#define EDJE_SIZE                           33
#define EDJE_TEXT                           34
#define EDJE_BOX                            35
#define EDJE_MAP                            36
#define EDJE_ROTATION                       37
#define EDJE_REL1                           38
#define EDJE_REL2                           39
