.TH feh-cam 1 "29 Oct 2000" "cam"
.SH NAME
.HP
feh-cam - a utility for viewing live webcam images
.SH SYNOPSIS
.HP 
feh-cam [options]
.P
.SH DESCRIPTION
.HP
.I feh-cam 
is a Perl wrapper for feh that simplifies viewing webcams. feh-cam uses                                                                                       keyed bookmarks.
.I feh 
image viewer. It helps manage viewing your favorite webcam sites with feh.
.HP
Type
.I "feh-cam -h"
at a command line for usage information.
.P
.SH SEE ALSO
.HP
feh(1)

