#!/bin/sh
cp ./evoak.c.in ./evoak.c
for I in `find ./src/lib -name "Evoak.h" -print`; do
  cat $I >> ./evoak.c
done
#for I in `find ./src/lib -name "*.c" -print`; do
#  cat $I >> ./evoak.c
#done
rm -rf ./doc/html ./doc/latex ./doc/man
doxygen
cp doc/img/*.png doc/html/
rm -f evoak_docs.tar evoak_docs.tar.gz
tar -cvf evoak_docs.tar doc/html doc/man doc/latex
gzip -9 evoak_docs.tar
exit 0
