#!/bin/bash
#goodtime/6 is also good
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test should create an index print with a title."
echo ""
$FEH $1 --font 20thcent/10 --title-font 20thcent/24 -V -o _test14.jpg -i --thumb-width 100 --thumb-height 100 testimages
echo ""
