#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This should invoke index mode"
echo "Ensure the background is transparent :)"
echo ""
$FEH $1 -qV --index --bg trans testimages/*
echo ""
