#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test should quietly open and display a single image"
echo "No options are specified on the commandline."
echo ""
$FEH $1 testimages/nell05.jpg
echo ""
