#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test should create a montage containing the contents of the"
echo "testimages directory, recursively. There should be some pngs in there"
echo ""
$FEH $1 -r -V -o _test10.jpg -m --thumb-width 100 --thumb-height 100 testimages
echo ""
