#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This should invoke list mode"
echo "Ensure the output makes sense :)"
echo ""
$FEH $1 -qV -L "test output. filename=%f, name=%n, width=%w, height=%h" testimages/*
echo ""
