#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test should open 4 images in 4 separate windows. It is important"
echo "that zooming works for each image individually, and that each image"
echo "can be closed individually, or all together with a right-click"
echo ""
$FEH $1 -Vw testimages/nurding01.jpg testimages/nurding02.jpg testimages/nurding03.jpg testimages/nell01.jpg
echo ""
