#!/bin/bash
echo ""
echo "Hehe. This is an evil test."
echo "This should open all the test images in one window each."
echo "Progressive loading should function, and the process should not"
echo "take too long"
echo ""
./feh $1 -V testimages/*.jpg
echo ""
