#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test should create a montage of pngs on a png. Transparency"
echo "should be maintained, even when zooming. The pngs should not be"
echo "stretched larger than they actually are, even though thumbnails"
echo "of 100x100 pixels have been requested"
echo ""
$FEH $1 -r -V -o _test8.jpg -m --bg testimages/pngs/bg.png --thumb-width 100 --thumb-height 100 testimages/pngs/*.png
echo ""
