#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This should invoke slideshow mode"
echo "Click mouse button 1 to change slides"
echo "There is no caching, so HUGE slideshows should not create"
echo "any extra overhead"
echo "Be sure to test the key controls!"
echo ""
$FEH $1 -V testimages/*.jpg
echo ""
