#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test should create an index print with no title or background."
echo "The font should be legible"
echo ""
$FEH $1 --font helmetr/10 -V -o _test14.jpg -i --thumb-width 100 --thumb-height 100 testimages
echo ""
