#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test creates a montage with a background and 100x100 pixel thumbnails"
echo ""
$FEH $1 -mVo _test01.jpg --bg testimages/heidi.jpg --thumb-width 100 --thumb-height 100 testimages
echo ""
