#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test creates a montage of 100x100 pixel thumbnails and stretches"
echo "them out of shape as necessary, ignoring aspect ratio"
echo ""
$FEH $1 -m --ignore-aspect -Vo _test02.jpg --bg testimages/heidi.jpg --thumb-width 100 --thumb-height 100 testimages
echo ""
