#!/bin/bash
echo ""
echo "This test is designed to fail, in order to test error handling"
echo "The app should output meaningful information to diagnose failure"
echo ""
./feh $1 -V Makefile.am main.c feh.h
echo ""
