#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This should invoke slideshow mode"
echo "Click mouse button 1 to change slides"
echo "The windows should be borderless"
echo ""
$FEH $1 -V --borderless testimages/*.jpg
echo ""
