#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test should be the same as the other slideshow test"
echo "But without progressive loading"
echo "Be sure to test the key controls!"
echo ""
$FEH $1 -V --no-progressive testimages/nurding01.jpg testimages/nurding02.jpg testimages/nurding03.jpg testimages/nell01.jpg
echo ""
