#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This is a HUGE image, it should still generate quickly though"
echo ""
$FEH $1 -V -O _test20.jpg -m --thumb-width 400 --thumb-height 400 --limit-width 1200 testimages
echo ""
