#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "Check the images are actually kinda transparent ;-)"
echo ""
$FEH $1 -V -o _test11.jpg --alpha 70 -m --bg testimages/heidi.jpg --thumb-width 100 --thumb-height 100 testimages
echo ""
