#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test should create a png on png montage, but this time the -s"
echo "option has been selected to stretch the pngs beyond their original"
echo "size if necessary. Transparency should be maintained"
echo ""
$FEH $1 --stretch -V -o _test13.jpg -m --bg testimages/pngs/bg.png --thumb-width 100 --thumb-height 100 testimages/pngs
echo ""
