#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
DELAY="3"
echo ""
echo "This should invoke slideshow mode"
echo "The slides should change after $DELAY seconds automatically"
echo "The timer will be paused while zooming"
echo ""
$FEH $1 --slideshow-delay $DELAY -V testimages/*.jpg
echo ""
