#!/bin/bash
echo ""
echo "This should invoke slideshow mode"
echo "Click mouse button 1 to change slides"
echo "There is no caching, so HUGE slideshows should not create"
echo "any extra overhead"
echo "Be sure to test the key controls!"
echo ""
./feh $1 -V -S testimages/nurding01.jpg testimages/nurding02.jpg testimages/nurding03.jpg testimages/nell01.jpg
echo ""
