#!/bin/bash
[ -x ./feh ] && {
FEH="./feh"
} || {
FEH="feh"
}
echo ""
echo "This test creates a montage, but the verbose option is not used, so"
echo "the app should be quiet, and only output to stdout on error"
echo ""
$FEH $1 -o _test01.jpg -m --bg testimages/heidi.jpg --thumb-width 100 --thumb-height 100 testimages
echo ""
