### A simplistic Edje Makefile 

all: eplayer.edc
	 edje_cc -v -id images eplayer.edc eplayer.eet


clean: eplayer.eet
	rm -f eplayer.eet core


preview: eplayer.eet
	edje eplayer.eet eplayer
	




  ####   #    #  #####   #####   #       ######   #####  ######   ####   #    #
 #    #  #    #  #    #  #    #  #       #          #    #       #    #  #    #
 #       #    #  #    #  #    #  #       #####      #    #####   #       ######
 #       #    #  #    #  #    #  #       #          #    #       #       #    #
 #    #  #    #  #    #  #    #  #       #          #    #       #    #  #    #
  ####    ####   #####   #####   ######  ######     #    ######   ####   #    #

