#!/bin/bash

function set_env {

  LC_ALL=POSIX
  TMP=${TMP:-/tmp}
  PKG=${TMP}/package-${NAME}

  if [ -z "${ARCH}" ]; then
    case "$( uname -m )" in
      i?86) ARCH=i486 ;;
      arm*) ARCH=arm ;;
      *) ARCH=$( uname -m ) ;;
    esac
  fi

  if [ "${RELEASE}" == 1 ]; then
    DEBUG=""
  else
    DEBUG="-O0 -g -ggdb3"
  fi

  SCFLAGS="-O2 -fomit-frame-pointer -pipe"
  if [ "${ARCH}" = "i486" ]; then
    SCFLAGS="${SCFLAGS} -march=i486 -mtune=i686 ${DEBUG} ${ECFLAGS}"
    LIBDIR="/usr/lib"
    MFLAGS="-j2"
  elif [ "${ARCH}" = "x86_64" ]; then
    SCFLAGS="${SCFLAGS} -fPIC ${DEBUG} ${ECFLAGS}"
    LIBDIR="/usr/lib64"
    MFLAGS="-j3"
  fi

  if [ ! -d ${TMP} ]; then
    mkdir -p ${TMP}
  fi
  rm -rf ${PKG}
  mkdir -p ${PKG}

}

function prepare_src {

  VERSION=r`svn info | grep Revision | cut -d ' ' -f2`

  find . \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) -exec chmod 755 {} \;
  find . \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

  if [ -f Makefile ]; then
    make maintainer-clean
  fi

}

function make_install {

  make ${MFLAGS}
  make DESTDIR=${PKG} install

}

function install_doc {

  mkdir -p ${PKG}/usr/doc/${NAME}-${VERSION}
  install -m644 ${@} ${PKG}/usr/doc/${NAME}-${VERSION}/

}

function api_doc {

  make doc
  mkdir -p ${PKG}/usr/doc/EFL/api
  cp -r doc/html ${PKG}/usr/doc/EFL/api/${NAME}
  ln -s /usr/doc/EFL/api/${NAME} ${PKG}/usr/doc/${NAME}-${VERSION}/html

}

function post_clean {

  if [ -d ${PKG}/usr/share/${NAME}/examples ]; then
    mkdir -p ${PKG}/usr/doc/EFL/examples
    mv ${PKG}/usr/share/${NAME}/examples ${PKG}/usr/doc/EFL/examples/${NAME}
    ln -s /usr/doc/EFL/examples/${NAME} ${PKG}/usr/doc/${NAME}-${VERSION}/examples
  fi
  
  make maintainer-clean

  if [ -d ${PKG}/usr/doc/EFL ]; then
    find ${PKG}/usr/doc/EFL -type f -exec chmod 644 {} \;
  fi

  if [ "${RELEASE}" == 1 ]; then
    find ${PKG} | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
    find ${PKG} | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  fi

}

function pack_slack {

  cd ${PKG}
  chown -R root:root .
  
  mkdir install
  install -m644 ${CWD}/slack-desc install/
  
  makepkg -l y -c n ${TMP}/${NAME}-${VERSION}-${ARCH}-${BUILD}.txz
  rm -rf ${PKG}

}
