.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ENNA "1" "January 2010" "Enna MediaCenter" "User Commands"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
Enna \- a powerful MediaCenter application based on EFL
.SH SYNOPSIS
.B enna
[\fIoptions \fR...]
.SH DESCRIPTION
This manual page documents briefly the \fBenna\fP command.
.PP
Enna is a Media Center application. Featuring a simple user interface, allows
the user to browse and play music and video files, browse pictures and play
photo slideshows, retrieve information (such as covers, fan art, song lyrics,
and much more) about the available media files on the Internet, build a
database of the available media and more.
.SH OPTIONS
.TP
\fB\-c\fR, (\fB\-\-config\fR):
specify the configuration file to be used.
.TP
\fB\-f\fR, (\fB\-\-fs\fR):
force fullscreen mode.
.TP
\fB\-h\fR, (\fB\-\-help\fR):
display a short help.
.TP
\fB\-t\fR, (\fB\-\-theme\fR):
specify the theme name to be used.
.HP
\fB\-g\fR, (\fB\-\-geometry\fR): specify the window geometry (the default is 1280x720)
.HP
\fB\-V\fR, (\fB\-\-version\fR): display Enna version number.
.SH AUTHOR
Enna was written by The Enna Project (http://enna.geexbox.org).
.PP
This manual page was written by Davide Cavalca <davide@geexbox.org>,
for the Debian project (but may be used by others).
