#!/bin/sh

set -e

. /usr/share/debconf/confmodule

THIS_PACKAGE=entrance
DEFAULT_DISPLAY_MANAGER_FILE=/etc/X11/default-display-manager

# creating entrance group if he isn't already there
if ! getent group entrance >/dev/null; then
        addgroup --system entrance
fi

# creating entrance user if he isn't already there
if ! getent passwd entrance >/dev/null; then
        adduser --system --ingroup entrance --home /var/lib/entrance entrance
	usermod -c "Enlightened Display Manager" entrance
	usermod -d "/var/lib/entrance"          entrance
	usermod -g "entrance"                   entrance
	usermod -s "/bin/false"            entrance
fi

if [ -d /var/lib/entrance ]; then
  chown -R entrance:entrance /var/lib/entrance
  chmod 0750 /var/lib/entrance
fi

# debconf is not a registry, so we only fiddle with the default file if it
# does not exist
db_get shared/default-x-display-manager
if [ "$RET" = "entranced" ]; then
  db_get entrance/daemon_name
  echo "$RET" > $DEFAULT_DISPLAY_MANAGER_FILE
fi
# debconf hangs if entrance gets started below without this
db_stop || true

entrance_running=

# NOTE: the binary on disk most likely has changed, so we can't use --exec
if start-stop-daemon --stop --quiet --name entrance --signal 0 --pid /var/run/entranced.pid; then
  entrance_running=yes
fi

if [ -d /var/state/entrance ]; then
  if [ "$entrance_running" ]; then
    echo "Note: obsolete directory /var/state/entrance cannot be removed when entrance"
    echo "is running.  Reinstall the entrance package (or remove the directory"
    echo "manually) when entrance is not running."
  else
    rm -r /var/state/entrance
  fi
fi

if [ -x /etc/init.d/entrance ]; then
  update-rc.d entrance defaults >/dev/null 2>&1
fi

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
# Automatically added by dh_scrollkeeper
if [ "$1" = "configure" ] && which scrollkeeper-update >/dev/null 2>&1; then
	scrollkeeper-update -q
fi
# End automatically added section


exit 0
