#include <Ewl.h>
#include "ewl_debug.h"
#include "ewl_macros.h"
#include "ewl_private.h"

static const Ewl_Stock_Item builtin_items [] = 
  {
    { EWL_STOCK_OK,          "ok" },
    { EWL_STOCK_APPLY,       "apply" },
    { EWL_STOCK_CANCEL,      "cancel" },
    { EWL_STOCK_OPEN,        "open" },
    { EWL_STOCK_PAUSE,       "pause" },
    { EWL_STOCK_PLAY,        "play" },
    { EWL_STOCK_SAVE,        "save" },
    { EWL_STOCK_STOP,        "stop" },
    { EWL_STOCK_REWIND,      "rewind" },
    { EWL_STOCK_FASTFORWARD, "fast forward" },
    { EWL_STOCK_QUIT,        "quit" },
    { EWL_STOCK_ARROW_UP,    "up" },
    { EWL_STOCK_HOME,        "home" },
  };

/* Return the label of the stock item if it exists */
/* Otherwise, return NULL */
/* The result must be freed when not used anymore */
char *
ewl_stock_label_get (const char *stock_id)
{
	int i, val, num;
	char *label = NULL;

	num = sizeof(builtin_items) / sizeof(Ewl_Stock_Item);
	for (i = 0; i < num ; i++) {
		val = strcmp (stock_id, builtin_items[i].stock_id);
		if (val == 0) {
			label = strdup (builtin_items[i].label);
			break;
		}
	}

	return label;
}


/**
 * @return Returns NULL on failure, a pointer to a new button on success.
 * @brief Allocate and initialize a new button with eventually a stock
 * icon.
 */
Ewl_Widget *ewl_button_stock_new(void)
{
	Ewl_Button_Stock *b;

	DENTER_FUNCTION(DLEVEL_STABLE);
  
	b = NEW(Ewl_Button_Stock, 1);
	if (!b)
		return NULL;
  
	ewl_button_stock_init(b);

	DRETURN_PTR(EWL_WIDGET(b), DLEVEL_STABLE);
}

/**
 * @param b: the button to initialize.
 * @param stock_id: set the stock Id or the label of the button @b to
 * @a stock_id.
 * @return Returns TRUE on success, FALSE otherwise.
 * @brief Initialize a button to starting values
 *
 * Initializes a button to default values and callbacks.
 */
int ewl_button_stock_init(Ewl_Button_Stock * b)
{
	Ewl_Widget *w;
	char       *label;
	char       *stock_id = EWL_STOCK_OK;
  
	DENTER_FUNCTION(DLEVEL_STABLE);
	DCHECK_PARAM_PTR_RET("b", b, 0);
 
	if (!ewl_button_init(EWL_BUTTON(b)))
		DRETURN_INT(FALSE, DLEVEL_STABLE);

	ewl_callback_append(EWL_WIDGET(b), EWL_CALLBACK_CLICKED,
			    ewl_button_stock_click_cb,
			    &(b->response_id));
	ewl_callback_append(EWL_WIDGET(b), EWL_CALLBACK_DESTROY,
			    ewl_button_stock_destroy_cb, NULL);

	label = ewl_stock_label_get(stock_id);

	if (label) {
		/* TODO : */
		/* mettre le theme ici ? */
		ewl_button_label_set(EWL_BUTTON(b), label);
		FREE(label);
	}
	else {
		ewl_button_label_set(EWL_BUTTON(b), stock_id);
	}

	/* Set the homogeneous flag to false, and add some space between image
	 * and label */
	ewl_box_homogeneous_set(EWL_BOX (b), FALSE);
	ewl_box_spacing_set(EWL_BOX (b), 6);
	ewl_object_padding_set(EWL_OBJECT(b), 0, 3, 3, 3);
	ewl_object_fill_policy_set(EWL_OBJECT(b), EWL_FLAG_FILL_VFILL |
						  EWL_FLAG_FILL_SHRINK);
  
	w = EWL_WIDGET(b);

	/* Create and setup the image for the button if it's desired */
	b->image_object = ewl_image_new();
	ewl_widget_appearance_set(b->image_object, stock_id);
	ewl_object_fill_policy_set(EWL_OBJECT(b->image_object),
				   EWL_FLAG_FILL_NONE);
	ewl_object_alignment_set(EWL_OBJECT(b->image_object),
				 EWL_FLAG_ALIGN_LEFT);
	ewl_container_child_prepend(EWL_CONTAINER(b), b->image_object);
	ewl_widget_show(b->image_object);

	/* Tweak the default alignment of the label */
	if (EWL_BUTTON(b)->label_object) {
		ewl_object_alignment_set(EWL_OBJECT(EWL_BUTTON(b)->label_object),
					 EWL_FLAG_ALIGN_CENTER);
	}
  
	DRETURN_INT(TRUE, DLEVEL_STABLE); 
}

/**
 * @param b: the button to set the stock id
 * @return Returns no value.
 * @brief Changes the stock id of the button.
 */
void ewl_button_stock_id_set(Ewl_Button_Stock *b, char *stock_id)
{
	char *label;

	DENTER_FUNCTION(DLEVEL_STABLE);
	DCHECK_PARAM_PTR("b", b);

	IF_FREE(b->stock_id);

	if (!stock_id)
		stock_id = EWL_STOCK_OK;
	b->stock_id = strdup(stock_id);

	label = ewl_stock_label_get(stock_id);
	if (label) {
		ewl_button_label_set(EWL_BUTTON(b), label);
		FREE(label);
	}
	else
		ewl_button_label_set(EWL_BUTTON(b), stock_id);

	ewl_widget_appearance_set(b->image_object, stock_id);

	DLEAVE_FUNCTION(DLEVEL_STABLE);
}

/**
 * @param b: the button to set the stock id
 * @return Returns no value.
 * @brief Changes the stock id of the button.
 */
char *ewl_button_stock_id_get(Ewl_Button_Stock *b)
{
	DENTER_FUNCTION(DLEVEL_STABLE);
	DCHECK_PARAM_PTR_RET("b", b, NULL);

	DRETURN_PTR(strdup(b->stock_id), DLEVEL_STABLE);
}

/**
 * @param b: the button to set the response id
 * @return Returns no value.
 * @brief Changes the response id generated by the button being clicked.
 */
void ewl_button_stock_response_id_set(Ewl_Button_Stock *b, int response_id)
{
	DENTER_FUNCTION(DLEVEL_STABLE);
	DCHECK_PARAM_PTR("b", b);

	b->response_id = response_id;

	DLEAVE_FUNCTION(DLEVEL_STABLE);
}

/**
 * @param b: Retrieve the current response id on a stock button.
 * @return Returns the current stock response.
 * @brief Retrieve the current stock response id the button generates.
 */
int ewl_button_stock_response_id_get(Ewl_Button_Stock *b)
{
	DENTER_FUNCTION(DLEVEL_STABLE);
	DCHECK_PARAM_PTR_RET("b", b, FALSE);

	DRETURN_INT(b->response_id, DLEVEL_STABLE);
}

/*
 * Internally used callbacks, override at your own risk.
 */

void
ewl_button_stock_click_cb (Ewl_Widget *w, void *ev __UNUSED__, void *data)
{
	ewl_callback_call_with_event_data (w, EWL_CALLBACK_VALUE_CHANGED, data);
}

void
ewl_button_stock_destroy_cb(Ewl_Widget *w, void *ev __UNUSED__, void *data)
{
	Ewl_Button_Stock *b = EWL_BUTTON_STOCK(w);

	IF_FREE(b->stock_id);
}
